---
sidebar: sidebar 
permalink: cli-upgrade-esxi.html 
keywords: administer, administering, cli, esxi, upgrade, esxi 7.0 
summary: Si ejecuta ONTAP Select en VMware ESXi, puede actualizar el software ESXi de una versión compatible con una versión anterior a ESXi 7,0 o posterior. Antes de actualizar, debe comprender el proceso y seleccionar el procedimiento de actualización adecuado. 
---
= Actualice a VMware ESXi 7.0 o posterior para ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si ejecuta ONTAP Select en VMware ESXi, puede actualizar el software ESXi de una versión compatible con una versión anterior a ESXi 7,0 o posterior. Antes de actualizar, debe comprender el proceso y seleccionar el procedimiento de actualización adecuado.



== Prepárese para actualizar VMware ESXi.

Prepare y seleccione el procedimiento de actualización adecuado para su entorno antes de actualizar el software ESXi en los hipervisores que alojan un clúster ONTAP Select .

.Pasos
. *Familiarízate con el proceso de actualización de VMware ESXi*
+
La actualización del software ESXi es un proceso que VMware describe y admite. El proceso de actualización del hipervisor forma parte del procedimiento de actualización más grande cuando se utiliza ONTAP Select. Consulte la documentación de VMware para obtener más información.

. *Seleccione un procedimiento de actualización*
+
Hay varios procedimientos de actualización disponibles. Debe seleccionar el procedimiento correspondiente según los siguientes criterios:

+
** El tamaño de clúster de ONTAP Select es compatible con los clústeres de un único nodo y de varios nodos.
** Uso de ONTAP Select Deploy
+
La actualización es posible tanto con como sin la utilidad Deploy.

+

TIP: Debe seleccionar un procedimiento de actualización que utilice la utilidad de administración de despliegue.

+
Realizar una actualización de ESXi mediante la utilidad de administración Deploy es la opción más general y resistente. Sin embargo, puede haber casos en los que Deploy no esté disponible o no se pueda utilizar. Por ejemplo, la actualización a ESXi 7.0 no es compatible con versiones anteriores de ONTAP Select ni con la utilidad de administración Deploy.

+
Si utiliza estas versiones anteriores e intenta realizar una actualización, la máquina virtual ONTAP Select se puede dejar en un estado en el que no se puede arrancar. En este caso, debe seleccionar un procedimiento de actualización que no utilice la puesta en marcha. Consulte link:https://mysupport.netapp.com/site/bugs-online/product/ONTAPSELECT/BURT/1172198["1172198"^] si quiere más información.



. *Actualizar la utilidad de administración de Deploy*
+
Antes de realizar un procedimiento de actualización utilizando la utilidad Deploy, es posible que deba actualizar su instancia de Deploy. En general, debería actualizar a la versión más reciente de Deploy. La utilidad Deploy debe ser compatible con la versión de ONTAP Select que esté utilizando.  Consulte ellink:reference_release_notes.html["Notas de la versión de ONTAP Select"] Para obtener más información.

. *Una vez finalizado el proceso de actualización*
+
Si selecciona un procedimiento de actualización que usa la utilidad de implementación, debe realizar una operación de actualización de clúster mediante implementar una vez que todos los nodos se han actualizado. Consulte actualización de la configuración de clúster de puesta en marcha para obtener más información.





== Actualice un clúster de un solo nodo mediante la puesta en marcha

Puede utilizar la utilidad de administración de puesta en marcha como parte del procedimiento para actualizar el hipervisor ESXi de VMware que aloja un clúster de un solo nodo de ONTAP Select.

.Pasos
. Inicie sesión en la CLI de la utilidad de implementación mediante SSH con la cuenta de administrador.
. Mueva el nodo al estado fuera de línea:
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. Actualice el host del hipervisor donde ONTAP Select se ejecuta a ESXi 7,0 o posterior mediante el procedimiento proporcionado por VMware.
. Pasar el nodo al estado en línea:
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. Después de que el nodo llegue, compruebe que el estado del clúster sea bueno.
+
Ejemplo:

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.Después de terminar
Debe realizar una operación de actualización de clúster mediante la utilidad de administración de despliegue.



== Actualice un clúster de varios nodos mediante Deploy

Puede utilizar la utilidad de administración de puesta en marcha como parte del procedimiento para actualizar los hipervisores ESXi de VMware que alojan un clúster multinodo de ONTAP Select.

.Acerca de esta tarea
Debe realizar este procedimiento de actualización para cada uno de los nodos del clúster, nodo a nodo. Si el clúster contiene cuatro nodos o más, debe actualizar los nodos en cada pareja de alta disponibilidad secuencialmente antes de continuar a la siguiente pareja de alta disponibilidad.

.Pasos
. Inicie sesión en la CLI de la utilidad de implementación mediante SSH con la cuenta de administrador.
. Mueva el nodo al estado fuera de línea:
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. Actualice el host del hipervisor donde ONTAP Select se ejecuta a ESXi 7,0 o posterior mediante el procedimiento proporcionado por VMware.
+
Consulte preparación para actualizar VMware ESXi si desea obtener más información.

. Pasar el nodo al estado en línea:
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. Después de que se produzca el nodo, compruebe que la conmutación por error de almacenamiento esté habilitada y que el clúster esté en buen estado.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.Después de terminar
Debe realizar el procedimiento de actualización de cada host que se utilice en el clúster de ONTAP Select. Después de actualizar todos los hosts ESXi, es necesario ejecutar una operación de actualización del clúster mediante la utilidad de administración Deploy.



== Actualice un clúster de un solo nodo sin poner en marcha

Puede actualizar el hipervisor ESXi de VMware que aloja un clúster de un solo nodo de ONTAP Select sin utilizar la utilidad de administración de puesta en marcha.

.Pasos
. Inicie sesión en la interfaz de línea de comandos de ONTAP y detenga el nodo.
. Utilice VMware vSphere para confirmar que la máquina virtual de ONTAP Select está apagada.
. Actualice el host del hipervisor donde ONTAP Select se ejecuta a ESXi 7,0 o posterior mediante el procedimiento proporcionado por VMware.
+
Consulte preparación para actualizar VMware ESXi si desea obtener más información.

. Con VMware vSphere, acceda a vCenter y realice lo siguiente:
+
.. Agregue una unidad de disquete a la máquina virtual ONTAP Select.
.. Encienda la máquina virtual de ONTAP Select.
.. Inicie sesión en la interfaz de línea de comandos de ONTAP mediante SSH con la cuenta de administrador.


. Después de que el nodo llegue, compruebe que el estado del clúster sea bueno.
+
Ejemplo:

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.Después de terminar
Debe realizar una operación de actualización de clúster mediante la utilidad de administración de despliegue.



== Actualice un clúster de varios nodos sin poner en marcha

Puede actualizar los hipervisores ESXi de VMware que alojan un clúster de varios nodos de ONTAP Select sin utilizar la utilidad de administración de la implementación.

.Acerca de esta tarea
Debe realizar este procedimiento de actualización para cada uno de los nodos del clúster, nodo a nodo. Si el clúster contiene cuatro nodos o más, debe actualizar los nodos en cada pareja de alta disponibilidad secuencialmente antes de continuar a la siguiente pareja de alta disponibilidad.

.Pasos
. Inicie sesión en la interfaz de línea de comandos de ONTAP y detenga el nodo.
. Utilice VMware vSphere para confirmar que la máquina virtual de ONTAP Select está apagada.
. Actualice el host del hipervisor donde ONTAP Select se ejecuta a ESXi 7,0 o posterior mediante el procedimiento proporcionado por VMware.
. Con VMware vSphere, acceda a vCenter y realice lo siguiente:
+
.. Agregue una unidad de disquete a la máquina virtual ONTAP Select.
.. Encienda la máquina virtual de ONTAP Select.
.. Inicie sesión en la interfaz de línea de comandos de ONTAP mediante SSH con la cuenta de administrador.


. Después de que se produzca el nodo, compruebe que la conmutación por error de almacenamiento esté habilitada y que el clúster esté en buen estado.
+
.Mostrar ejemplo
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.Después de terminar
Debe realizar el procedimiento de actualización de cada host que se utilice en el clúster de ONTAP Select.
