---
sidebar: sidebar 
permalink: concept_lic_cp_restrictions.html 
keywords: license, licensing, Capacity Pools, restrictions 
summary: A continuación, se presentan las restricciones aplicables cuando se utiliza el modelo de licencias del pool de capacidad. 
---
= Restricciones de puesta en marcha para la gestión de licencias de pools de capacidad de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A continuación, se presentan las restricciones aplicables cuando se utiliza el modelo de licencias del pool de capacidad.

.Modelo de licencias consistente por clúster
Todos los nodos dentro de un único clúster de ONTAP Select deben usar el mismo modelo de licencia, niveles de capacidad o pools de capacidad. No se pueden mezclar los tipos de licencias para los nodos en un único clúster.

.Todos los nodos de un clúster utilizan la misma instancia de License Manager
Todos los nodos con una licencia de Capacity Pool en un clúster ONTAP Select deben usar la misma instancia de License Manager. Porque hay una instancia de License Manager dentro de cada instancia de Deploy, esta restricción es una reafirmación del requisito existente de que la misma instancia de Deploy debe gestionar todos los nodos en un clúster.

.Un pool de capacidad por nodo
Cada nodo puede arrendar almacenamiento desde exactamente un Pool de capacidad. Un nodo no puede usar dos o más pools.

.El mismo pool para nodos de una pareja de alta disponibilidad
Los dos nodos de un único par de alta disponibilidad deben arrendar almacenamiento desde el mismo pool de capacidad. Sin embargo, diferentes parejas de alta disponibilidad dentro del mismo clúster pueden arrendar almacenamiento de diferentes pools gestionados por el mismo administrador de licencias.

.Duración de la licencia de almacenamiento
Debe elegir una duración de la licencia cuando adquiera la licencia de almacenamiento de NetApp. Por ejemplo, una licencia podría ser válida por un año.

.Duración de la concesión del agregado de datos
Cuando un nodo de ONTAP Select solicita una concesión de almacenamiento para un agregado de datos, el administrador de licencias proporciona una concesión para un período específico en función de la configuración del pool de capacidad. Puede configurar la duración de la concesión para cada pool entre una hora y siete días. La duración de la concesión predeterminada es de 24 horas.

.Dirección IP estática asignada a la implementación
Debe asignar una dirección IP estática a la utilidad de administración de despliegue cuando se utilice la licencia de pools de capacidad.
