---
sidebar: sidebar 
permalink: concept_vpi_planning.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, planning 
summary: Antes de instalar y usar el complemento de vCenter para implementar, debe prepararse para garantizar el éxito. 
---
= Planifique utilizar el complemento de vCenter para poner en marcha
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de instalar y usar el complemento de vCenter para implementar, debe prepararse para garantizar el éxito.



== Requisitos de software

Existen varios requisitos de software que debe tener en cuenta como se describe en la siguiente tabla.

[cols="35,65"]
|===
| De NetApp | Versión compatible 


| Utilidad ONTAP Select Deploy | 2.11.2 o posterior 


| VSphere de VMware | 6.5 GA o posterior 


| Interfaz de usuario de VMware vSphere | HTML5 (la versión basada en Flash no es compatible) 


| ESXi | 6.5U2 o posterior 
|===


== Restricciones de tamaño del clúster

Hay varias restricciones relacionadas con el tamaño del clúster que debe tener en cuenta como se describe en la siguiente tabla.

[cols="35,65"]
|===
| Elemento | Máximo admitido 


| ONTAP Select ponga en marcha clústeres | 100 


| Nodos (máquinas virtuales) | 1000 


| Hosts | 800 
|===


== Privilegios de RBAC para las cuentas de usuario de vCenter

Se requieren varios privilegios de vCenter diferentes para gestionar el plugin y acceder a él. Estos privilegios corresponden a las acciones de las siguientes tres categorías:

* Gestión del plugin mediante la implementación:
+
** Instale
** Renovar
** Quitar


* Acceder al plugin a través del cliente vSphere
* Se valida el acceso del usuario al plugin mediante vSphere


Consulte link:concept_vpi_manage_before.html#preparing-the-vcenter-server-accounts["Preparar las cuentas de vCenter Server"] si quiere más información.



== Limitaciones de AutoSupport

El complemento Deploy vCenter proporciona una cantidad mínima de información de uso de la utilidad de administración de Deploy (incluida la URL del plugin). Sin embargo, AutoSupport incluye una tabla de los plugins instalados que se pueden mostrar mediante el visor de AutoSupport.


NOTE: No se puede descargar un paquete de AutoSupport a través del cliente web de vSphere mediante el plugin de implementación. Debe usar la interfaz de implementación nativa para descargar paquetes AutoSupport.



== Restricciones adicionales

Existen varias restricciones adicionales que debe tener en cuenta antes de instalar y usar el complemento de puesta en marcha de vCenter:

* Cada instancia del plugin de vCenter admite solo un servidor de vCenter.
* Las instancias de vCenter Server que están configuradas en modo vinculado no son compatibles.
* La interfaz gráfica de usuario del plugin de puesta en marcha en vSphere solo muestra clústeres con máquinas virtuales ONTAP Select gestionadas por el mismo servidor vCenter. No se incluyen los clústeres ONTAP Select que se ejecutan en hosts ESXi y KVM independientes.

