---
sidebar: sidebar 
permalink: concept_automate_ansible.html 
keywords: ansible, automation, configuration management, ontap, ontap select, na_ots_deploy, na_ots_cluster, ansible roles, ansible playbook 
summary: Use los roles de Ansible para automatizar las puestas en marcha de ONTAP Select. 
---
= Automatice las puestas en marcha de ONTAP Select con Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Use los libros de estrategia y roles de Ansible para automatizar las puestas en marcha de ONTAP Select.

Un rol de Ansible es una colección lógica de tareas, plantillas, controladores y variables en una estructura de archivos estandarizada. Utilice estos roles para facilitar, reutilizar y modular funcionalidad que se puede utilizar de forma independiente. Incluya roles y la lista de hosts a los que desea que se ejecuten, en un libro de estrategia para su ejecución. Después de instalar Ansible, actualizar los módulos necesarios y comprender los libros de estrategia, estará listo para descargar los roles de ONTAP Select (OTS) de GitHub de NetApp para crear y ejecutar su propio libro de estrategia para poner en marcha los clústeres de ONTAP Select.



== Funciones

Hay dos roles disponibles para ONTAP Select:



=== na_ots_deploy

Este rol descarga el archivo de instalación para ONTAP Select Deploy en un host de vCenter o ESXi. A continuación, crea y ejecuta el equipo virtual de puesta en marcha.

Este rol utiliza los siguientes valores de entrada:

* Credenciales de host vCenter o ESXi
* Ponga en marcha la creación de equipos virtuales e incluya información como:
+
** Dirección IP
** Nombre de host
** Inicio de sesión
** Contraseña
** Almacén de datos
** Red


* Ruta local al archivo OVA
+
Asegúrese de que el archivo de instalación esté disponible antes de ejecutar el libro de estrategia, incluida la función).




NOTE: La forma más sencilla de proporcionar estos valores de entrada es a través de un archivo de variables globales en formato YML. Superar este ARCHIVO DE YML en el libro de estrategia.

El rol tiene una única tarea que importa el archivo OVA de implementación en el host, crea la máquina virtual y lo ejecuta. Puede acceder a este rol y descargarlo desde Ansible GitHub de NetApp aquí: link:https://github.com/netapp-automation/na_ots_deploy["na_ots_deploy"^]



=== na_ots_cluster

Este rol utiliza las API de implementación de ONTAP Select para crear e implementar el clúster de ONTAP Select. Supone que se ha creado la VM de despliegue y está en funcionamiento manualmente o utilizando el rol *na_ots_Deploy*. Además, el rol supone que los hosts de selección se configuraron correctamente con las redes y el almacenamiento necesarios para el clúster ONTAP Select.

El rol utiliza los valores de entrada de las credenciales de vCenter o ESXI y pone en marcha credenciales de las máquinas virtuales para acceder a las API y toda la información relativa necesaria para crear el clúster de ONTAP Select y la máquina virtual del nodo.

El rol realiza las siguientes tareas:

* Añadir credenciales de host (vcenter o esxi)
* Obtener y registrar los ID de host
* Validación de la red interna (para clústeres de varios nodos)
* Cree el clúster
* Configurar los nodos
* Configurar la red y el pool de almacenamiento
* Implementar el clúster


Como resultado, el rol se completa con la máquina virtual del clúster en funcionamiento y el clúster ONTAP Select en su totalidad. Puede acceder a este rol y descargarlo desde Ansible GitHub de NetApp aquí: link:https://github.com/NetApp-Automation/na_ots_cluster["na_ots_cluster"^]



== Ejemplo de libro de aplicaciones

A continuación se muestra un libro de estrategia de ejemplo que llama a estas dos funciones de ONTAP Select. Tenga en cuenta que las variables de entrada se definen en archivos YML y se pasan a través de “var_files”. Puede encontrar más detalles en los archivos README en cada una de las funciones.

[listing]
----
—

– name: Create ONTAP Select deploy from OVA (ESXi)

vars_files:

– vars_deploy.yml                              # All Variables

– vars_deploy_pwd.yml                          # host_password & deploy_password

hosts: “{{ target_vcenter_or_esxi_host }}”     # Entry in Ansible ‘hosts’ file

gather_facts: false

connection: ‘local’

roles:

– na_ots_deploy

– name: Create ONTAP Select Cluster

vars_files:

– vars_cluster_test.yml

– vars_cluster_pwd.yml

hosts: “localhost”

gather_facts: false

roles:

– na_ots_cluster

----
Una vez creado y en ejecución el clúster de ONTAP Select con los roles anteriores, puede aprovechar el amplio conjunto de roles de Ansible de ONTAP disponibles para automatizar aún más las funciones y la funcionalidad de ONTAP. Se puede acceder a los roles de ONTAP disponibles link:https://github.com/NetApp/ansible["aquí"]. En resumen, los roles de Ansible ONTAP Select y los roles de ONTAP le permiten automatizar por completo el flujo de trabajo integral para gestionar el almacenamiento con ONTAP Select.
