---
sidebar: sidebar 
permalink: concept_api_rest.html 
keywords: rest api, deploy rest api, rest, architecture, resources, state, uri, http, json 
summary: 'La transferencia de estado representacional (REST) es un estilo para crear aplicaciones web distribuidas. Cuando se aplica al diseño de una API de servicios web, establece un conjunto de tecnologías y prácticas recomendadas para exponer recursos basados en servidor y administrar sus estados. Usa los protocolos y estándares más habituales para proporcionar una base flexible para la implementación y gestión de clústeres de ONTAP Select.' 
---
= Base de servicios web REST para poner en marcha y gestionar clústeres de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La transferencia de estado representacional (REST) es un estilo para crear aplicaciones web distribuidas. Cuando se aplica al diseño de una API de servicios web, establece un conjunto de tecnologías y prácticas recomendadas para exponer recursos basados en servidor y administrar sus estados. Usa los protocolos y estándares más habituales para proporcionar una base flexible para la implementación y gestión de clústeres de ONTAP Select.



== Con las restricciones clásicas y a la arquitectura

EL RESTO fue articulado formalmente por Roy Fielding en su doctorado https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm["disertación"] En UC Irvine en 2000. Define un estilo arquitectónico a través de un conjunto de restricciones, que han mejorado colectivamente las aplicaciones basadas en web y los protocolos subyacentes. Estas restricciones establecen una aplicación de servicios web RESTful basada en una arquitectura de cliente/servidor que utiliza un protocolo de comunicación sin estado.



== Recursos y representación estatal

Los recursos son los componentes básicos de un sistema basado en la Web. Al crear una aplicación DE SERVICIOS web DE REST, las tareas de diseño más tempranas incluyen:

* Identificación de los recursos basados en el sistema o en el servidor cada sistema utiliza y mantiene los recursos. Un recurso puede ser un archivo, una transacción comercial, un proceso o una entidad administrativa. Una de las primeras tareas en el diseño de una aplicación basada en servicios web DE REST es identificar los recursos.
* Definición de estados de recursos y operaciones estatales asociadas los recursos siempre se encuentran en uno de un número finito de estados. Los estados, así como las operaciones asociadas utilizadas para afectar los cambios de estado, deben estar claramente definidos.


Los mensajes se intercambian entre el cliente y el servidor para acceder y cambiar el estado de los recursos según el modelo genérico CRUD (Crear, Leer, Actualizar y Eliminar).



== Extremos de URI

Todos los recursos REST deben definirse y ponerse a disposición mediante un esquema de direccionamiento bien definido. Los extremos en los que se encuentran e identifican los recursos utilizan un identificador uniforme de recursos (URI). El URI proporciona un marco general para crear un nombre único para cada recurso de la red. El Localizador uniforme de recursos (URL) es un tipo de URI que se utiliza con los servicios web para identificar y acceder a los recursos. Los recursos normalmente se exponen en una estructura jerárquica similar a un directorio de archivos.



== Mensajes HTTP

El Protocolo de transferencia de hipertexto (HTTP) es el protocolo utilizado por el cliente y servidor de servicios web para intercambiar mensajes de solicitud y respuesta sobre los recursos. Como parte del diseño de una aplicación de servicios web, los verbos HTTP (como GET y POST) se asignan a los recursos y a las acciones de administración de estado correspondientes.

HTTP no tiene estado. Por lo tanto, para asociar un conjunto de solicitudes y respuestas relacionadas en una transacción, se debe incluir información adicional en los encabezados HTTP transportados con los flujos de datos de solicitud/respuesta.



== Formato JSON

Aunque la información se puede estructurar y transferir entre un cliente y un servidor de varias maneras, la opción más popular (y la que se usa con la API REST de deploy) es la notación de objetos JavaScript (JSON). JSON es un estándar del sector para representar estructuras de datos simples en texto sin formato y se utiliza para transferir información de estado que describe los recursos.
