---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: Después de implementar un clúster de ONTAP Select, puede actualizar la imagen de ONTAP de cada nodo según sea necesario mediante el procedimiento estándar de actualización del software ONTAP. 
---
= Actualizar los nodos ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Después de implementar un clúster de ONTAP Select, puede actualizar la imagen de ONTAP en cada nodo del clúster según sea necesario.


CAUTION: No se puede usar la utilidad de administración de implementación para realizar actualizaciones de los nodos ONTAP Select existentes. La utilidad de implementación solo se puede usar para crear clústeres de ONTAP Select nuevos.



== Procedimiento general

En un nivel superior, debe seguir los siguientes pasos para actualizar un nodo ONTAP Select existente.

. Desplácese hasta la página de descargas en el sitio de soporte de NetApp.
+
https://["Descargas de soporte de NetApp"^]

. Haga clic en *actualización de nodo ONTAP Select*.
. Seleccione y descargue la imagen de actualización adecuada respondiendo a todos los avisos según sea necesario.
. Consulte las notas de la versión para obtener información adicional y los procedimientos que se necesitan antes de actualizar un nodo ONTAP Select. Puede acceder a las notas de la versión de ONTAP Select en la página de la biblioteca de productos.
+
https://["Biblioteca de productos de ONTAP Select"^]

. Actualice el nodo ONTAP Select mediante los procedimientos de actualización estándar de ONTAP con el archivo de actualización de ONTAP Select.
+
https://["Documentación de ONTAP 9"^]





== Revertir un nodo ONTAP Select

No es posible revertir un nodo de ONTAP Select a una versión anterior a la versión que se instaló originalmente. Por ejemplo:

ONTAP Select 9.4 se instala inicialmente:: Puede actualizar el nodo a la versión 9.5 y volver a la versión 9.4, si fuera necesario.
ONTAP Select 9.5 se instala inicialmente:: No puede volver a la versión 9.4 porque esta versión es anterior a la versión que se instaló originalmente.




== Uso del controlador de red VMXNT3

A partir de ONTAP Select 9.5 con Deploy 2.10, VMXNEG3 es el controlador de red predeterminado que se incluye con las nuevas implementaciones de clúster en VMware ESXi. Si actualiza un nodo ONTAP Select existente a la versión 9.5, el controlador de red no se actualiza automáticamente. Debe actualizar manualmente a VMXNEL3. Debe ponerse en contacto con el soporte de NetApp para obtener ayuda con la actualización.
