---
sidebar: sidebar 
permalink: concept_lic_cp_benefits.html 
keywords: license, licensing, Capacity Pools, benefits 
summary: Cuando se usa el modelo de licencias de pools de capacidad en lugar del modelo de licencias de niveles de capacidad, se pueden obtener varios beneficios. 
---
= Resumen de las ventajas de las licencias de los pools de capacidad de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando se usa el modelo de licencias de pools de capacidad en lugar del modelo de licencias de niveles de capacidad, se pueden obtener varios beneficios.



== Un uso más eficiente de la capacidad de almacenamiento

Cuando se usa la licencia Capacity Tiers, se asigna una capacidad de almacenamiento fija a cada nodo. Cualquier espacio no utilizado no se puede compartir con los otros nodos y se desperdicia, en la práctica. Con la gestión de licencias de pools de capacidad, cada nodo solo consume la capacidad que necesita en función del tamaño de los agregados de datos.

La capacidad se ancla en un pool central donde puede compartirse entre muchos nodos de tu organización.



== Reducción considerable de los gastos administrativos, lo que supone un menor coste

Si usa licencias de nivel de capacidad, debe obtener e instalar una licencia para cada nodo. Cuando se usan pools de capacidad, hay una licencia para cada pool compartido. Esto puede reducir considerablemente los gastos administrativos y disminuir los costes.



== Métricas de uso mejoradas

La interfaz de usuario web de implementación proporciona información de uso mejorada para los pools de capacidad. Es posible determinar rápidamente cuánto almacenamiento se usa y está disponible en un pool de capacidad, qué nodos usan el almacenamiento desde un pool y a qué pools asigna la capacidad un clúster.
