---
sidebar: sidebar 
permalink: concept_vpi_manage_before.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, manage, managing 
summary: Hay varias cosas que debe hacer antes de instalar y gestionar el complemento de puesta en marcha de vCenter. 
---
= Antes de empezar
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay varias cosas que debe hacer antes de instalar y gestionar el complemento de puesta en marcha de vCenter.



== Decida si se utilizará la interfaz de usuario web de implementación o la CLI

En la mayoría de los casos, la interfaz de usuario web de puesta en marcha ofrece la opción más conveniente cuando se gestiona el plugin de vCenter y esta es la opción descrita en este procedimiento. Sin embargo, también puede gestionar el plugin mediante la interfaz de línea de comandos deploy. Para obtener más información, escriba los siguientes comandos en el símbolo del sistema de la CLI de Deploy:

* `deploy plugin ?` (Los subcomandos incluyen: Instalar, quitar, mostrar y actualizar)
* `deploy plugin-packages show`




== Preparación común a todas las tareas de gestión

Hay varios pasos que debe realizar independientemente de la tarea de administración. La preparación común incluye:

* Leer la sección primeros pasos para familiarizarse con el complemento de vCenter para la implementación.
* Garantía de que la utilidad de administración de implementación de ONTAP Select está instalada y en ejecución.
Consulte la documentación de instalación y puesta en marcha de clústeres para VMware para obtener más información.
* Adquiriendo las credenciales de cuenta:
+
** Implemente una cuenta de administrador
** Cuentas de vCenter Server


* Para garantizar que la utilidad de implementación tenga acceso de red al puerto 443 en vCenter Server.


En función de la tarea de gestión, es posible que se requiera una preparación adicional.



== Prepare las cuentas de vCenter Server

Antes de instalar y usar el plugin de implementación, debe crear las cuentas de vCenter con los privilegios requeridos. Puede crear una única cuenta con todos los privilegios necesarios o crear varias cuentas con un solo privilegio. Para mayor simplicidad, el siguiente ejemplo distribuye los privilegios de vCenter en tres roles independientes que luego se pueden asignar a las tres cuentas correspondientes.



=== Validar el acceso del usuario final al plugin

Se necesita una cuenta para validar el acceso al plugin mediante vSphere. La cuenta debe tener el siguiente privilegio de vCenter: sessions.validate.session. Una vez creada la cuenta en vCenter, debe definirla en la utilidad de administración de implementación. En la interfaz de usuario web de Deploy, haga clic en la pestaña Administration y, a continuación, Credentials para proporcionar la ubicación y las credenciales del servidor de vCenter.

Esta cuenta se utiliza de las siguientes formas:

* El servidor vCenter con nombre pasa a estar disponible como destino de instalación en la ventana de diálogo de registro del plugin.
* La cuenta se utiliza en Deploy para validar las solicitudes de usuario de vSphere para acceder al plugin después de haber instalado el plugin.




=== Gestione el plugin

En la interfaz de usuario web de implementación, puede instalar el plugin y, a continuación, actualizarlo o quitarlo. Cada vez que realiza una de estas acciones de gestión, se le pedirá una cuenta de vCenter en la ventana emergente. Cada una de las acciones de gestión se controla mediante un privilegio de vCenter independiente.

Para instalar, actualizar y quitar el plugin, debe asignar los siguientes privilegios:

* Extensión
+
** Registrar extensión
** Actualizar extensión
** Cancele el registro de la extensión




Puede crear una sola función y cuenta con los tres privilegios o dividir los privilegios entre varias cuentas según sea necesario.



=== Acceda al plugin

Los usuarios finales pueden acceder al plugin mediante vSphere. Debe asignar el siguiente privilegio a las cuentas que utilizarán el plugin:

* NetApp
+
** Puesta en marcha de ONTAP Select
+
*** Administrador





