---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: El modelo de licencia de pools de capacidad es diferente del modelo de niveles de capacidad. En lugar de dedicar capacidad de almacenamiento a cada nodo individual, la capacidad de almacenamiento se asigna a un pool y se comparte entre muchos nodos. Se crearon componentes y procesos adicionales para admitir el modelo de pools de capacidad. 
---
= Detalles operativos del modelo de licencias de pools de capacidad de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El modelo de licencia de pools de capacidad es diferente del modelo de niveles de capacidad. En lugar de dedicar capacidad de almacenamiento a cada nodo individual, la capacidad de almacenamiento se asigna a un pool y se comparte entre muchos nodos. Se crearon componentes y procesos adicionales para admitir el modelo de pools de capacidad.



== Administrador de licencias

El Administrador de licencias se ejecuta como un proceso independiente dentro de cada instancia de la utilidad de administración de despliegue. Algunas de las funciones proporcionadas por LM son:

* Genere un número de serie único de veinte dígitos para cada nodo en función del número de serie de licencia de Capacity Pool
* Cree concesiones para capacidad a partir de los pools de capacidad compartida según solicitudes de los nodos ONTAP Select
* Informe de la información de uso del pool a través de la interfaz de usuario de despliegue




== Características del arrendamiento

El almacenamiento asignado para cada agregado de datos en un nodo utilizando una licencia de Capacity Pool debe tener una concesión asociada. El nodo solicita una concesión de almacenamiento y si la capacidad está disponible, License Manager responde con una concesión. Cada concesión tiene los siguientes atributos explícitos o implícitos:

* Administrador de licencias
+
Cada nodo ONTAP Select está asociado a una instancia de License Manager

* Pool de capacidad
+
Cada nodo ONTAP Select está asociado con un grupo de capacidad

* Asignación de almacenamiento
+
Se asigna un valor de capacidad específico en el contrato de arrendamiento

* Fecha y hora de caducidad
+
Los arrendamientos tienen una duración de entre una hora y siete días dependiendo de la configuración de usuario.





== ID de bloqueo de licencia

Cada instancia del Administrador de licencias y, por lo tanto, cada instancia correspondiente de la utilidad de despliegue se identifica con un número único de 128 bits. Este Núm. Se combina con el Núm. De serie de licencia de nueve dígitos Capacity Pool para bloquear el pool a una instancia específica del Administrador de licencias (que es efectivamente una instancia de despliegue). Debe proporcionar ambos valores en el sitio de soporte de NetApp como parte de la generación del archivo de licencia de NetApp (NLF).

Puede determinar el ID de bloqueo de licencia para la instancia de implementación mediante la interfaz de usuario web de las siguientes formas:

* Página de introducción
+
Deploy muestra esta página cuando inicias sesión por primera vez. También puedes abrir el cuadro desplegable en la parte superior derecha de la página y seleccionar *Getting Started* para mostrar esta página. El LLID aparece en la sección Add Licenses.

+
Selecciona la pestaña *Administración* en la parte superior de la página, luego selecciona *Sistemas* y *Configuración*.





== Operaciones de arrendamiento básicas

Un nodo ONTAP Select debe localizar o solicitar un contrato de capacidad válido cada vez que se crea, amplía o modifica un agregado de datos. Puedes usar un contrato obtenido de una solicitud anterior que todavía sea válido, o puedes solicitar uno nuevo si lo necesitas. El nodo ONTAP Select realiza los siguientes pasos para localizar un contrato de un grupo de capacidad:

. Si hay una concesión existente en el nodo, se usa siempre que sean ciertas siguientes:
+
** El arrendamiento no ha caducado
** La solicitud de almacenamiento para el agregado no supera la capacidad de concesión


. Si no se puede encontrar una concesión existente, el nodo solicita una nueva concesión al Administrador de licencias.




== Devolver la capacidad de almacenamiento a un pool de capacidad

La capacidad de almacenamiento se asigna desde un pool de capacidad según sea necesario y cada solicitud nueva puede reducir el almacenamiento disponible en el pool. La capacidad de almacenamiento se devuelve al pool en varias situaciones, como:

* El arrendamiento de un agregado de datos caduca y no lo ha renovado el nodo
* El agregado de datos se elimina



NOTE: Si se elimina una máquina virtual ONTAP Select, todas las concesiones activas seguirán en vigor hasta que caduquen. Cuando esto sucede, la capacidad se devuelve al pool.
