---
sidebar: sidebar 
permalink: concept_terminology.html 
keywords: terminology, key concepts, concepts 
summary: Al comenzar a explorar ONTAP Select y planificar una implementación, es útil familiarizarse con la terminología y los conceptos clave. 
---
= Terminología y conceptos clave
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Al comenzar a explorar ONTAP Select y planificar una implementación, es útil familiarizarse con la terminología y los conceptos clave.

Puesta en marcha de ONTAP Select:: ONTAP Select Deploy es la utilidad de administración que se utiliza para poner en marcha clústeres de ONTAP Select. La utilidad Deploy se ejecuta en una máquina virtual dedicada de Linux. Puede acceder a la utilidad de implementación mediante la interfaz de usuario web, el shell de gestión de la interfaz de línea de comandos y la API DE REST.
Máquina virtual basada en kernel:: La máquina virtual basada en kernel (KVM) es una característica de virtualización del kernel de Linux, que le permite actuar como una plataforma de hipervisor. Se admite una amplia gama de sistemas operativos invitados.
Host de hipervisor frente a nodo ONTAP Select:: Un _hypervisor host_ es la plataforma de hardware principal que aloja una máquina virtual ONTAP Select. Cuando se implementa una máquina virtual ONTAP Select y está activa en un host de hipervisor, se considera un _ONTAP Select node_.
Clúster de ONTAP Select:: Puede crear un _ONTAP Select cluster_ compuesto por uno, dos, cuatro, seis u ocho nodos. Los clústeres de varios nodos siempre contienen uno o más pares de alta disponibilidad. Por ejemplo, un clúster de cuatro nodos consta de dos parejas de alta disponibilidad. Un único clúster de nodo no proporciona funcionalidades de alta disponibilidad.
Preparación del entorno de host del hipervisor:: Antes de usar la utilidad de administración Deploy para poner en marcha un clúster de ONTAP Select, debe preparar los hosts de hipervisor donde se ejecutará ONTAP Select, incluidos los entornos de almacenamiento y redes. Esta configuración previa del host se realiza fuera del producto de ONTAP Select de acuerdo con los requisitos y las limitaciones actuales.
Evaluación frente a implementaciones de producción:: Cada nodo ONTAP Select se ejecuta con una _licencia de evaluación_ o con una _licencia adquirida_. Una licencia de evaluación permite evaluar ONTAP Select antes de implementarla en un entorno de producción. La licencia de evaluación se genera y aplica automáticamente. Si implementa un clúster en un entorno de producción, debe adquirir una licencia que suponga elegir:
+
--
* Modelo de licencias
* Capacidad de almacenamiento
* Oferta de licencia de plataforma


--
Modelo de licencias por niveles de capacidad:: El modelo de licencias de niveles de capacidad es la opción original al otorgar licencias del almacenamiento para una implementación de ONTAP Select. Se basa en el modelo de ONTAP utilizado con AFF y FAS de NetApp. Se necesita una licencia aparte para cada nodo. La capacidad de almacenamiento está bloqueada en el nodo y es perpetua (sin necesidad de renovación).
Modelo de licencias de pools de capacidad:: El modelo de licencia de pools de capacidad se introdujo con ONTAP Select 9.5 mediante Deploy 2.10. Se requiere una licencia aparte para cada pool de capacidad de almacenamiento. La licencia del pool de capacidad se bloquea en una instancia de License Manager (que es una instancia de implementación) y debe renovarse según las condiciones de compra. Es posible utilizar la licencia y cualquier cantidad de pools de capacidad en la organización. Sin embargo, como los nodos ONTAP Select comparten los pools de capacidad, normalmente se necesitan menos licencias que las licencias de niveles de capacidad.
Administrador de licencias:: License Manager es un componente de software que admite licencias de pools de capacidad. Actualmente forma parte de la utilidad de administración de despliegue. LM alquila almacenamiento a los nodos ONTAP Select de los pools compartidos que gestiona. El _License Lock ID_ es una cadena numérica que identifica de forma exclusiva cada instancia LM y, por lo tanto, cada instancia de implementación. Se deben usar el número de serie de licencia del pool de capacidad y LLID para generar un archivo de licencia.
Ofertas de licencias de plataformas:: Hay tres ofertas de licencia disponibles que determinan el tamaño de las capacidades de la máquina virtual de ONTAP Select al comprar una licencia:
+
--
* Estándar
* Premium
* Premium XL


--


Para obtener más información, consulte las dos secciones _Plan_ y _License_.

Pools de almacenamiento frente a almacenes de datos:: Un _pool de almacenamiento_ de ONTAP Select es un contenedor de datos lógico diseñado para extraer y ocultar el almacenamiento físico subyacente. Un pool de almacenamiento no depende del hipervisor. Cuando se pone en marcha en un host de hipervisor ESXi, el pool de almacenamiento de ONTAP Select es sinónimo de VMware _datastore_.
MTU del clúster:: La MTU de clúster es una función de que permite configurar el tamaño de MTU usado en la red interna que se usa con un clúster de varios nodos de ONTAP Select. La utilidad de administración de puesta en marcha ajusta el tamaño de MTU a medida que configura las parejas de alta disponibilidad para adaptarse al entorno de red. También puede establecer manualmente el valor.
VNAS de ONTAP Select:: La solución vNAS de ONTAP Select permite que un nodo ONTAP Select acceda a los almacenes de datos de VMware en almacenamiento externo. Con vNAS de ONTAP Select, ya no es necesario un controlador RAID local; el almacenamiento remoto asume que la función RAID es proporcionada. VNAS de ONTAP Select puede configurarse de las siguientes maneras:
+
--
* VSAN de VMware
* Cabina de almacenamiento externo genérica


--


En ambos casos, el almacenamiento externo debe configurarse antes de crear un clúster de ONTAP Select o ampliar la capacidad de almacenamiento de un nodo existente.

Realojamiento del nodo en la máquina virtual ESXi:: Cuando pone en marcha un clúster que utiliza almacenamiento externo disponible a través de la solución vNAS de ONTAP Select (VMware VSAN o una cabina de almacenamiento externo genérica), la máquina virtual ESXi que aloja el nodo ONTAP Select puede moverse por medio de acciones utilizando las siguientes funciones de VMware:
+
--
* VMotion
* Alta disponibilidad
* Planificador de recursos distribuidos (DRS, Distributed Resource Scheduler)
+
La utilidad ONTAP Select Deploy detecta el movimiento de la máquina virtual como parte de la ejecución de una operación en el clúster, por ejemplo:

* clúster en línea
* clúster sin conexión
* adición de almacenamiento
+
Cuando se mueve una máquina virtual, la utilidad Deploy actualiza su base de datos interna y configura el nuevo host ESXi. Todas las acciones realizadas en el nodo ONTAP Select se bloquean hasta que se completa el movimiento de la máquina virtual y las actualizaciones de implementación.



--
Abra vSwitch para KVM:: Open vSwitch (OVS) es una implementación de software de un switch virtual que admite varios protocolos de red. OVS es de código abierto y está disponible de acuerdo con la licencia Apache 2,0.
Servicio de mediación:: La utilidad de puesta en marcha de ONTAP Select incluye un servicio de mediador que se conecta a los nodos en los clústeres de dos nodos activos. Este servicio supervisa cada par de alta disponibilidad y ayuda a gestionar los fallos.



CAUTION: Si tiene uno o varios clústeres de dos nodos activos, la máquina virtual ONTAP Select Deploy que administra los clústeres debe ejecutarse siempre. Si la máquina virtual de puesta en marcha está detenida, el servicio del mediador no estará disponible y se perderán funcionalidades de alta disponibilidad para los clústeres de dos nodos.

SDS de MetroCluster:: El almacenamiento definido por software de MetroCluster es una función que proporciona una opción de configuración adicional al implementar un clúster de ONTAP Select de dos nodos. A diferencia de una típica puesta en marcha robo de dos nodos, los nodos SDS de MetroCluster pueden separarse con una distancia mucho mayor. Esta separación física proporciona casos de uso adicionales como la recuperación ante desastres. Debe tener una licencia premium o superior para usar SDS de MetroCluster. Además, la red entre los nodos debe admitir un requisito mínimo de latencia.
Almacén de credenciales:: El almacén de credenciales de despliegue es una base de datos segura que contiene credenciales de cuenta. Se utiliza principalmente para registrar hosts de hipervisor como parte de la creación de un clúster nuevo. Consulte la sección _Plan_ para obtener más información.
Eficiencia del almacenamiento:: ONTAP Select ofrece opciones de eficiencia del almacenamiento similares a las opciones de eficiencia del almacenamiento presentes en las cabinas FAS y AFF. Conceptualmente, ONTAP Select con unidades SSD de almacenamiento de conexión directa (DAS) (con una licencia premium) es similar a una cabina AFF. Las configuraciones que utilizan DAS con HDD y todas las configuraciones vNAS deben considerarse similares a las de una cabina FAS. La principal diferencia entre las dos configuraciones es que ONTAP Select con SSD DAS admite la deduplicación a nivel de agregado en línea y la deduplicación en segundo plano a nivel de agregado. El resto de opciones de eficiencia del almacenamiento están disponibles para ambas configuraciones.
+
--
Las configuraciones predeterminadas de vNAS habilitan una característica de optimización de escritura conocida como registro de datos de instancia única (SIDL). Con ONTAP Select 9.6 y versiones posteriores, las funciones de eficiencia del almacenamiento de ONTAP en segundo plano están certificadas con SIDL habilitado. Consulte la sección _Deep bucve_ para obtener más información.

--
Actualización del clúster:: Después de crear un clúster, puede realizar cambios en la configuración del clúster o de máquinas virtuales fuera de la utilidad de puesta en marcha mediante las herramientas de administración de ONTAP o del hipervisor. También puede migrar una máquina virtual que cause cambios en la configuración. Cuando se producen estos cambios, la utilidad de implementación no se actualiza automáticamente y puede quedar sin sincronizar con el estado del clúster. Puede utilizar la función de actualización de clúster para actualizar la base de datos de configuración de despliegue. La actualización del clúster se encuentra disponible a través de la interfaz de usuario web de Deploy, el shell de gestión de la interfaz de línea de comandos y la API DE REST.
RAID de software:: Al usar almacenamiento de conexión directa (DAS), la funcionalidad RAID se proporciona tradicionalmente a través de una controladora RAID de hardware local. En su lugar, puede configurar un nodo para que utilice _software RAID_ donde el nodo ONTAP Select proporciona la funcionalidad RAID. Si utiliza RAID de software, ya no se necesita una controladora RAID de hardware.
Instalación de imagen ONTAP Select:: A partir de la implementación de ONTAP Select 2.8, la utilidad de administración de implementación sólo contiene una versión de ONTAP Select. La versión incluida es la más actual disponible en el momento de la publicación. La función de instalación de imagen de ONTAP Select le permite añadir versiones anteriores de ONTAP Select a su instancia de la utilidad de implementación, que se puede utilizar posteriormente al implementar un clúster de ONTAP Select. Consulte link:task_cli_deploy_image_add.html["Añada imágenes ONTAP Select para obtener más información"].



NOTE: Sólo debe agregar una imagen ONTAP Select con una versión anterior a la versión original incluida con la instancia de implementación. No se admite la adición de versiones posteriores de ONTAP Select sin también actualizar Deploy.

Administrar un clúster de ONTAP Select después de haberse puesto en marcha:: Después de implementar un clúster de ONTAP Select, puede configurar el clúster como lo haría con un clúster de ONTAP basado en hardware. Por ejemplo, puede configurar un clúster de ONTAP Select mediante System Manager o la interfaz de línea de comandos estándar de ONTAP.


.Información relacionada
link:task_cli_deploy_image_add.html["Agregue una imagen ONTAP Select para implementarla"]
