---
sidebar: sidebar 
permalink: concept_lic_cp_serial_number.html 
keywords: license, licensing, Capacity Pools, node serial numbers 
summary: Con el modelo de licencia de Capacity Tiers, el número de serie del nodo de nueve dígitos es el mismo que el número de serie de la licencia asignado al nodo. Sin embargo, los números de serie asignados a los nodos que utilizan el modelo de licencia de pools de capacidad tienen un formato diferente. 
---
= Números de serie de nodos para el modelo de gestión de licencias de pools de capacidad de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con el modelo de licencia de Capacity Tiers, el número de serie del nodo de nueve dígitos es el mismo que el número de serie de la licencia asignado al nodo. Sin embargo, los números de serie asignados a los nodos que utilizan el modelo de licencia de pools de capacidad tienen un formato diferente.

El número de serie de un nodo que utiliza la gestión de licencias de los pools de capacidad tiene el formato siguiente:

`999 ppppppppp nnnnnnnn`


NOTE: Se han añadido espacios para mayor claridad, pero no forman parte del número de serie real.

Cada sección del número de serie del nodo se describe en la siguiente tabla, de izquierda a derecha.

[cols="15,85"]
|===
| Sección | Descripción 


| '999' | Valor constante de tres dígitos reservado por NetApp. 


| ppppppppppppppp | Número de serie de licencia de nueve dígitos variable asignado al pool de capacidad por NetApp 


| nnnnnnnn | Valor variable de ocho dígitos generado por el administrador de licencias para cada nodo que utiliza el pool de capacidad 
|===

NOTE: Atención: Al abrir un caso en compatibilidad con NetApp que implica un nodo que utiliza una licencia de Capacity Pool, no puede proporcionar el número de serie del nodo de veinte dígitos completo. En su lugar, debe proporcionar el número de serie de la licencia de nueve dígitos del pool de capacidad. Puede derivar el número de serie de la licencia del número de serie del nodo tal como se muestra anteriormente. Omita los primeros tres dígitos del número de serie del nodo ('999') y extraiga los siguientes nueve dígitos (ppppppppppppppp).
