---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: Después de implementar un clúster de ONTAP Select, puede actualizar la imagen de ONTAP de cada nodo según sea necesario mediante el procedimiento estándar de actualización del software ONTAP. 
---
= Actualice los nodos ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Después de implementar un clúster de ONTAP Select, puede actualizar la imagen de ONTAP en cada nodo del clúster según sea necesario.


CAUTION: No se puede usar la utilidad de administración de implementación para realizar actualizaciones de los nodos ONTAP Select existentes. La utilidad de implementación solo se puede usar para crear clústeres de ONTAP Select nuevos.



== Procedimiento general

En un nivel superior, debe seguir los siguientes pasos para actualizar un nodo ONTAP Select existente.

. Desplácese hasta la página de descargas en el sitio de soporte de NetApp.
+
https://mysupport.netapp.com/site/downloads["Descargas de soporte de NetApp"^]

. Haga clic en *actualización de nodo ONTAP Select*.
. Seleccione y descargue la imagen de actualización adecuada respondiendo a todos los avisos según sea necesario.
+
Consulte las notas de la versión para obtener información adicional y los procedimientos que se necesitan antes de actualizar un nodo ONTAP Select.

. Actualice el nodo ONTAP Select mediante los procedimientos de actualización estándar de ONTAP con el archivo de actualización de ONTAP Select. Para obtener información sobre las rutas de actualización admitidas, consulte link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["Rutas de actualización de ONTAP admitidas"^].




== Revierte un nodo ONTAP Select

No puede revertir un nodo ONTAP Select a una versión anterior a la que estaba instalado originalmente. Por ejemplo:

ONTAP Select 9,7 está instalado inicialmente:: Puede actualizar el nodo a la versión 9,8 y después revertir a la versión 9,7 si es necesario.
ONTAP Select 9,8 está instalado inicialmente:: No puede volver a la versión 9,7 porque esta versión es anterior a la versión que estaba instalada originalmente.




== Utilice el controlador de red VMXNet3

VMXNet3 es el controlador de red predeterminado que se incluye con las puestas en marcha de clústeres nuevos en VMware ESXi. Si actualiza un nodo ONTAP Select existente que ejecuta ONTAP Select 9,4 o una versión anterior, el controlador de red no se actualiza automáticamente. Debe actualizar manualmente a VMXNEL3. Debe ponerse en contacto con el soporte de NetApp para obtener ayuda con la actualización.

.Información relacionada
* link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["Información general de la actualización de ONTAP"^]

