---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: Mientras QUE REST establece un conjunto común de tecnologías y prácticas recomendadas, los detalles de cada API pueden variar en función de las opciones de diseño. Debe tener en cuenta los detalles y las características operativas de la API de implementación de ONTAP Select antes de usar la API. 
---
= ONTAP Select implementa características operativas básicas de API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mientras QUE REST establece un conjunto común de tecnologías y prácticas recomendadas, los detalles de cada API pueden variar en función de las opciones de diseño. Debe tener en cuenta los detalles y las características operativas de la API de implementación de ONTAP Select antes de usar la API.



== Host de hipervisor frente a nodo ONTAP Select

Un _hypervisor host_ es la plataforma de hardware principal que aloja una máquina virtual ONTAP Select. Cuando se implementa una máquina virtual ONTAP Select y está activa en un host de hipervisor, la máquina virtual se considera un _ONTAP Select node_. Con la versión 3 de la API DE REST de implementación, los objetos de host y nodo son distintos y separados. Esto permite una relación de uno a varios, donde uno o varios nodos ONTAP Select pueden ejecutarse en el mismo host de hipervisor.



== Identificadores de objeto

A cada instancia u objeto de recurso se le asigna un identificador único cuando se crea. Estos identificadores son globalmente únicos dentro de una instancia específica de la implementación de ONTAP Select. Después de emitir una llamada API que crea una nueva instancia de objeto, el valor de id asociado se devuelve al llamador en la `location` Encabezado de la respuesta HTTP. Puede extraer el identificador y utilizarlo en llamadas posteriores cuando haga referencia a la instancia del recurso.


NOTE: El contenido y la estructura interna de los identificadores de objeto pueden cambiar en cualquier momento. Solo se deben usar los identificadores en las llamadas API aplicables según sea necesario cuando se hacen referencia a los objetos asociados.



== Identificadores de solicitudes

A cada solicitud API de éxito se le asigna un identificador único. El identificador se muestra en la `request-id` Encabezado de la respuesta HTTP asociada. Puede utilizar un identificador de solicitud para hacer referencia colectivamente a las actividades de una única transacción específica de solicitud y respuesta de API. Por ejemplo, puede recuperar todos los mensajes de eventos de una transacción basándose en el ID de solicitud



== Llamadas síncronas y asíncronas

Hay dos formas principales de que un servidor realice una solicitud HTTP recibida desde un cliente:

* Síncrono el servidor realiza la solicitud inmediatamente y responde con un código de estado de 200, 201 o 204.
* Asincrónica el servidor acepta la solicitud y responde con un código de estado de 202. Esto indica que el servidor ha aceptado la solicitud de cliente y ha iniciado una tarea en segundo plano para completar la solicitud. El éxito o el fallo final no están disponibles de forma inmediata y se deben determinar mediante llamadas API adicionales.




== Confirmar que se ha completado un trabajo de ejecución prolongada

Por lo general, cualquier operación que puede tardar mucho tiempo en completarse se procesa de forma asíncrona mediante una tarea en segundo plano en el servidor. Con la API Deploy REST, cada tarea en segundo plano está anclada por un objeto Job que realiza un seguimiento de la tarea y proporciona información, como el estado actual. Un objeto Job, incluido su identificador único, se devuelve en la respuesta HTTP después de crear una tarea en segundo plano.

Puede consultar el objeto Job directamente para determinar el éxito o el error de la llamada API asociada. Consulte _procesamiento asíncrono mediante el objeto Job_ para obtener información adicional.

Además de utilizar el objeto Job, existen otras formas de determinar el éxito o el fallo de una solicitud, entre las que se incluyen:

* Mensajes de eventos puede recuperar todos los mensajes de eventos asociados con una llamada API específica utilizando el ID de solicitud devuelto con la respuesta original. Los mensajes de eventos normalmente contienen una indicación de éxito o fallo, y también pueden ser útiles al depurar una condición de error.
* Estado o estado de recurso varios de los recursos mantienen un valor de estado o estado al que puede consultar para determinar indirectamente el éxito o el error de una solicitud.




== Seguridad

La API de implementación utiliza las siguientes tecnologías de seguridad:

* Seguridad de la capa de transporte todo el tráfico enviado a través de la red entre el servidor de implementación y el cliente se cifra a través de TLS. No se admite el uso del protocolo HTTP a través de un canal no cifrado. Se admite la versión 1.2 de TLS.
* Autenticación HTTP la autenticación básica se utiliza para cada transacción de API. A cada solicitud se agrega un encabezado HTTP, que incluye el nombre de usuario y la contraseña en una cadena base64.

