---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: La puesta en marcha de un clúster de dos nodos con alta disponibilidad implica la misma planificación y configuración que se utiliza con otras configuraciones de nodos de clúster. Sin embargo, debe tener en cuenta varias diferencias al crear un clúster de dos nodos. 
---
= Clústeres de dos nodos de ONTAP Select con alta disponibilidad
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La puesta en marcha de un clúster de dos nodos con alta disponibilidad implica la misma planificación y configuración que se utiliza con otras configuraciones de nodos de clúster. Sin embargo, debe tener en cuenta varias diferencias al crear un clúster de dos nodos.

.Entorno objetivo
El clúster de dos nodos consta de un par de alta disponibilidad y está específicamente diseñado para la puesta en marcha de oficinas remotas y sucursales.


NOTE: Aunque se diseñó principalmente para el entorno de la oficina remota y la sucursal, también puede implementar un clúster de dos nodos en el centro de datos, si fuera necesario.

.Licencia
Un clúster de dos nodos se puede poner en marcha con cualquier licencia de VMware vSphere. Sin embargo, las licencias estándar y avanzada de VMware robo son perfectas para puestas en marcha remotas y sucursales.

.Servicio de mediación
Cuando un clúster consta de dos nodos, no es posible lograr el quórum necesario cuando un nodo falla o pierde la comunicación. Para resolver estos tipos de situaciones de cerebro dividido, cada instancia de la utilidad ONTAP Select Deploy incluye un servicio mediador. Este servicio se conecta a cada nodo en los clústeres de dos nodos activos para supervisar las parejas de alta disponibilidad y ayudar a gestionar fallos. El servicio del mediador mantiene la información de estado de alta disponibilidad en un destino iSCSI dedicado asociado a cada clúster de dos nodos.


CAUTION: Si tiene uno o más clústeres de dos nodos activos, la máquina virtual de ONTAP Select Deploy que administra los clústeres debe estar en ejecución permanente. Si la máquina virtual ONTAP Select Deploy se detiene o falla, el servicio de mediación no está disponible y se pierde la capacidad de alta disponibilidad para los clústeres de dos nodos.

.Ubicación del cluster y del servicio mediador
Debido a que los clústeres de dos nodos se suelen implementar en una oficina remota o sucursal, pueden estar alejados del centro de datos corporativo y de la utilidad ONTAP Select Deploy que proporciona soporte administrativo.  Con esta configuración, el tráfico de gestión entre la utilidad ONTAP Select Deploy y el clúster fluye a través de la WAN. Consulte las notas de la versión para obtener más información sobre las limitaciones y restricciones.

.Realizar una copia de seguridad de los datos de configuración de implementación
Es una buena prácticalink:task_cli_clusters.html["Realizar una copia de seguridad de los datos de configuración de ONTAP Select Deploy"] de forma regular, incluso después de crear un clúster. Esto cobra especial importancia en clústeres de dos nodos, debido a los datos de configuración del mediador incluidos en la copia de seguridad.

.Dirección IP estática asignada a la implementación
Debe asignar una dirección IP estática a la utilidad de administración ONTAP Select Deploy.  Este requisito se aplica a todas las instancias de ONTAP Select Deploy que administran uno o más clústeres de dos nodos de ONTAP Select .
