---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select ofrece compatibilidad total para la mayoría de las funcionalidades de ONTAP. Muchas de las funciones de ONTAP se conceden automáticamente con licencia para cada nodo cuando se pone en marcha un clúster. Sin embargo, algunas funciones requieren una licencia independiente. 
---
= Compatibilidad de ONTAP Select con las funciones de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select admite la mayoría de las funciones de ONTAP . Muchas de las funciones de ONTAP se licencian automáticamente para cada nodo al implementar un clúster. Sin embargo, algunas funciones requieren una licencia independiente.


NOTE: Las funciones de ONTAP con dependencias específicas de hardware generalmente no son compatibles con ONTAP Select.



== Funciones de ONTAP con licencia por defecto

Las siguientes funciones de ONTAP son compatibles con ONTAP Select y tienen licencia de forma predeterminada:

* Protección autónoma contra ransomware (ARP) (actualizaciones manuales)
* CIFS
* Deduplicación y compresión
* Gestión externa de claves mediante el protocolo de interoperabilidad de gestión de claves (KMIP)
+
La gestión externa de claves es la única gestión de claves soportada por ONTAP Select. Conoce más sobre link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["habilitación y configuración de la gestión externa de claves"^].

* FlexCache
+
ONTAP Select admite los volúmenes de caché FlexCache con write-back. Los volúmenes de origen FlexCache con write-back no son compatibles.

+
link:concept_ots_overview.html#flexcache-write-back-with-ontap-select["Más información sobre FlexCache write-back with ONTAP Select"]

* FlexClone
* ISCSI
* NDMP
* Cifrado de volúmenes de NetApp (solo países no restringidos)
* NFS
* NVMe sobre TCP
* Capacidad de multi-tenancy de ONTAP
* ONTAP S3
* SnapMirror S3
* SnapLock Select
+
SnapLock Select es la implementación de ONTAP SnapLock diseñada para ONTAP Select e incluye SnapLock Enterprise. No incluye SnapLock Compliance.

+
Más información link:https://docs.netapp.com/us-en/ontap/snaplock/index.html["ONTAP SnapLock"^]

* SnapMirror
* SnapRestore
* SnapVault
* Recuperación ante desastres de máquina virtual de almacenamiento (DR de SVM)
+
ONTAP Select admite SVM DR como origen y destino con un máximo de 16 relaciones. La compatibilidad con SVM DR se limita al uso de la versión de ONTAP de origen a las versiones +2. Por ejemplo, el origen de ONTAP Select 9.16.1 puede conectarse a las versiones de ONTAP de destino 9.16.1, 9.17.1 o 9.18.1.





== Funciones de ONTAP con licencias independientes

Es necesario adquirir una licencia independiente para cualquier función de ONTAP que no tenga licencia por defecto, incluyendo:

* FabricPool
+

NOTE: No necesita una licencia de FabricPool cuando utilice StorageGRID.

* SDS de MetroCluster (oferta de licencia premium de ONTAP Select)
* SnapMirror cloud
+
Necesitas link:https://mysupport.netapp.com/site/help["abrir un caso de asistencia no técnica"^] para obtener una licencia cloud de SnapMirror.

+
Más información link:https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["SnapMirror copias de seguridad en la nube en almacenamiento de objetos"^]



.Información relacionada
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["Compare ONTAP Select y ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Conoce las claves de licencia maestra de NetApp ONTAP"^]

