---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select ofrece compatibilidad total para la mayoría de las funcionalidades de ONTAP. Muchas de las funciones de ONTAP se conceden automáticamente con licencia para cada nodo cuando se pone en marcha un clúster. Sin embargo, algunas funciones requieren una licencia independiente. 
---
= Funciones de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select ofrece compatibilidad total para la mayoría de las funcionalidades de ONTAP. Muchas de las funciones de ONTAP se conceden automáticamente con licencia para cada nodo cuando se pone en marcha un clúster. Sin embargo, algunas funciones requieren una licencia independiente.


NOTE: Las funciones de ONTAP con dependencias específicas de hardware generalmente no son compatibles con ONTAP Select.



== Las funciones de ONTAP se habilitan automáticamente de forma predeterminada

Las siguientes funciones se incluyen con ONTAP Select y con licencia de forma predeterminada:

* CIFS
* Deduplicación y compresión
* FlexCache
* FlexClone
* ISCSI
* NDMP
* Cifrado de volúmenes de NetApp (solo países no restringidos)
* NFS
* NVMe sobre TCP
* Capacidad de multi-tenancy de ONTAP
* ONTAP S3
* SnapMirror
* SnapRestore
* SnapVault
* Recuperación ante desastres de máquina virtual de almacenamiento (DR de SVM)
+

NOTE: ONTAP Select 9.12.1 y versiones posteriores ahora admite la Recuperación ante desastres de SVM como origen y destino con un máximo de 16 relaciones. La compatibilidad con la recuperación ante desastres de SVM se limita al uso de la versión ONTAP de origen a las versiones +2. Por ejemplo, el origen de ONTAP Select 9.12.1 puede conectarse a las versiones 9.12.1, 9.13.1 o 9.14.1 de ONTAP de destino.





== Funciones de ONTAP con licencias independientes

Debe adquirir una licencia independiente para cualquier función ONTAP que no esté habilitada de forma predeterminada, como por ejemplo:

* Servicio de disponibilidad de datos
* FabricPool
* SDS de MetroCluster (oferta de licencia premium de ONTAP Select)
* SnapLock Enterprise (SnapLock Compliance no es compatible con ONTAP Select)
+
** Copias Snapshot a prueba de manipulaciones


* SyncMirror (coste cero)



NOTE: No necesita una licencia de FabricPool cuando utiliza StorageGRID Webscale.

.Información relacionada
* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9["Comparación entre ONTAP Select y ONTAP 9"]

