---
sidebar: sidebar 
permalink: reference_plan_ots_networking.html 
keywords: plan, planning, networking, network, drivers, vmxnet3, cluster mtu, firewall 
summary: Debe configurar la red del hipervisor correctamente antes de implementar ONTAP Select. 
---
= Consideraciones sobre la red
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe configurar la red del hipervisor correctamente antes de implementar ONTAP Select.



== Opciones de switch virtual

Debe configurar un switch virtual en cada uno de los hosts ONTAP Select para admitir la red externa y la red interna (solo clústeres de varios nodos). Como parte de la implementación de un clúster de varios nodos, debe probar la conectividad de red en la red de clúster interna.


NOTE: Si quiere más información sobre cómo configurar un vSwitch en un host de hipervisor y la función de interfaz de alta velocidad, consulte la link:concept_nw_concepts_chars.html["Redes profundas"] sección.



== Actualización a VMXNT3

A partir de ONTAP Select 9.5 con Deploy 2.10, VMXNEG3 es el controlador de red predeterminado que se incluye con las nuevas implementaciones de clúster en VMware ESXi. Si actualiza un nodo de ONTAP Select existente a la versión 9.5 o posterior, el controlador no se actualiza automáticamente.


NOTE: Por el momento no es necesario actualizar a VMXNNNT3. Sin embargo, si decide actualizar el controlador, debe realizar la actualización manualmente. En este caso, comuníquese con el soporte de NetApp para obtener ayuda.



== MTU del clúster

Se usa una red interna separada para conectar los nodos de ONTAP Select en un clúster de varios nodos. Generalmente, el tamaño de MTU para esta red es de 9000. Sin embargo, existen situaciones en las que este tamaño de MTU sea demasiado grande para la red que conecta los nodos de ONTAP Select. Para acomodar las tramas más pequeñas, el tamaño de MTU que utiliza ONTAP Select en la red interna puede estar en un rango de 7500-9000 bytes.

El tamaño de MTU se muestra en la sección Cluster Details de la página cluster Creation. El valor está determinado por la utilidad de administración de despliegue de la siguiente manera:

. Valor predeterminado inicial de 9000.
. Al añadir hosts y redes para los pares de alta disponibilidad, el valor MTU se reduce según sea necesario, en función de la configuración de los vSwitch en la red.
. El valor final de MTU del clúster para el clúster se establece después de haber añadido todas las parejas de alta disponibilidad y está listo para crear el clúster.



NOTE: Puede establecer manualmente el valor de MTU de clúster si es necesario, en función del diseño de la red.



== Host de dos NIC con vSwitch estándar

Para mejorar el rendimiento de ONTAP Select en una configuración de dos NIC, debe aislar el tráfico de red interno y externo mediante dos grupos de puertos. Esta recomendación se aplica a la siguiente configuración específica:

* Clúster multinodo ONTAP Select
* Dos NIC (NIC1 y NIC2)
* VSwitch estándar


En este entorno, debe configurar el tráfico mediante dos grupos de puertos de la siguiente manera:

.Grupo de puertos 1
* Red interna (clúster, RSM, tráfico de alta disponibilidad-IC)
* NIC1 está activo
* NIC2 en espera


.Grupo de puertos 2
* Red externa (tráfico de gestión y datos)
* NIC1 está en espera
* NIC2 en activo


Consulte link:concept_nw_concepts_chars.html["Redes profundas"] Para obtener más información acerca de las implementaciones de dos NIC.



== Host de cuatro NIC con vSwitch estándar

Para mejorar el rendimiento de ONTAP Select en una configuración de cuatro NIC, debe aislar el tráfico de red interno y externo utilizando cuatro grupos de puertos. Esta recomendación se aplica a la siguiente configuración específica:

* Clúster multinodo ONTAP Select
* Cuatro NIC (NIC1, NIC2, NIC3 y NIC4)
* VSwitch estándar


En este entorno, debe configurar el tráfico mediante cuatro grupos de puertos de la siguiente manera:

.Grupo de puertos 1
* Red interna (tráfico de clúster, RSM)
* NIC1 está activo
* NIC2, NIC3, NIC4 en espera


.Grupo de puertos 2
* Red interna (clúster, tráfico de alta disponibilidad-IC)
* NIC3 está activo
* NIC1, NIC2, NIC4 en espera


.Grupo de puertos 3
* Red externa (tráfico de gestión y datos)
* NIC2 está activo
* NIC1, NIC3, NIC4 en espera


.Grupo de puertos 4
* Red externa (tráfico de datos)
* NIC4 está activo
* NIC1, NIC2, NIC3 en espera


Consulte link:concept_nw_concepts_chars.html["Redes profundas"] Para obtener más información acerca de las implementaciones de cuatro NIC.



== Requisitos de tráfico de red

Debe asegurarse de que los firewalls están configurados correctamente para permitir que el tráfico de red fluya entre los distintos participantes en un entorno de implementación de ONTAP Select.

.Participantes
Hay varios participantes o entidades que intercambian tráfico de red como parte de una implementación de ONTAP Select. Se introducen y, a continuación, se utilizan en la descripción de resumen de los requisitos de tráfico de red.

* Implemente la utilidad de administración ONTAP Select Deploy
* VSphere/ESXi: Un servidor vSphere o un host ESXi, según cómo se gestione el host en la puesta en marcha de clúster
* Servidor del hipervisor host del hipervisor ESXi
* Nodo OTS nodo ONTAP Select
* Grupo OTS un clúster ONTAP Select
* Estación de trabajo administrativa local de WS de administración


.Resumen de los requisitos de tráfico de red
En la siguiente tabla se describen los requisitos de tráfico de red para una implementación de ONTAP Select.

[cols="20,45,35"]
|===
| Protocolo/Puerto | Dirección | Descripción 


| TLS (443) | Implemente en vCenter Server (gestionado) o ESXi (no administrado) | API VIX de VMware 


| 902 | Implemente en vCenter Server (gestionado) o ESXi (no administrado) | API VIX de VMware 


| ICMP | Puesta en marcha en servidor de hipervisor | Ping 


| ICMP | Despliegue en cada nodo OTS | Ping 


| SSH (22) | WS de administración a cada nodo OTS | Administración 


| TLS (443) | Despliegue en los nodos y clusters de OTS | Acceda a ONTAP 


| TLS (443) | Cada nodo OTS que se va a implementar | Puesta en marcha de acceso 


| ISCSI (3260) | Cada nodo OTS que se va a implementar | Mediador/disco de buzón 
|===