---
sidebar: sidebar 
permalink: reference_plan_ots_general.html 
keywords: plan, planning, general requirements 
summary: Hay varios requisitos generales que se deben tener en cuenta como parte de la planificación de una puesta en marcha de ONTAP Select. 
---
= Requisitos generales y consideraciones de planificación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Existen varios requisitos generales que se deben tener en cuenta como parte de la planificación de una puesta en marcha de ONTAP Select.



== Tamaño del clúster y consideraciones relacionadas

Hay varios problemas de planificación relacionados con el tamaño del clúster que debe tener en cuenta.

Número de nodos en el clúster:: Un clúster de ONTAP Select se compone de uno, dos, cuatro, seis u ocho nodos. Debe determinar el tamaño del clúster de acuerdo con los requisitos de la aplicación. Por ejemplo, si se necesita una capacidad de alta disponibilidad para una puesta en marcha empresarial, se debe utilizar un clúster de varios nodos.
Dedicado versus colubicado:: En función del tipo de aplicación, debe determinar si la implementación sigue el modelo dedicado o colubicado. Tenga en cuenta que el modelo de colocación puede ser más complejo debido a la diversidad de la carga de trabajo y a una integración más estrecha.




== Hosts de hipervisores

Existen varios problemas de planificación relacionados con el host del hipervisor que debe tener en cuenta.


CAUTION: No se debe modificar directamente la configuración de una máquina virtual de ONTAP Select a menos que el soporte de NetApp le indique hacerlo. Sólo se debe configurar y modificar una máquina virtual mediante la utilidad de administración de despliegue. Si se realizan cambios en una máquina virtual de ONTAP Select fuera de la utilidad de implementación sin la ayuda del soporte de NetApp, es posible que la máquina virtual falle y quede inutilizable.

Independiente del hipervisor:: Tanto ONTAP Select como la utilidad de administración de ONTAP Select Deploy son independientes del hipervisor. Los siguientes hipervisores son compatibles con ambos.
+
--
* VMware ESXi
* Máquina virtual basada en kernel (KVM)


--



NOTE: A partir de ONTAP Select 9.10.1, el hipervisor KVM ya no es compatible cuando se pone en marcha un clúster nuevo. Todavía puede utilizar KVM con una versión compatible anterior.

Consulte la información de planificación específica del hipervisor y las notas de la versión para obtener más detalles sobre las plataformas compatibles.

Hipervisor para nodos ONTAP Select y utilidad de administración:: Tanto la utilidad de administración de implementación como los nodos ONTAP Select se ejecutan como máquinas virtuales. El hipervisor que elija para la utilidad de puesta en marcha es independiente del hipervisor que elija para los nodos ONTAP Select. Dispone de flexibilidad completa al emparejar los dos:
+
--
* La utilidad de puesta en marcha que se ejecuta en VMware ESXi puede crear y gestionar clústeres de ONTAP Select en VMware ESXi o KVM
* La utilidad de puesta en marcha que se ejecuta en KVM puede crear y gestionar clústeres de ONTAP Select en VMware ESXi o KVM


--
Una o más instancias de nodo ONTAP Select por host:: Cada nodo ONTAP Select se ejecuta como máquina virtual dedicada. Puede crear varios nodos en el mismo host del hipervisor, con las siguientes restricciones:
+
--
* No se pueden ejecutar varios nodos desde un único clúster de ONTAP Select en el mismo host. Todos los nodos de un host específico deben tener clústeres de ONTAP Select diferentes.
* Debe usar almacenamiento externo.
* Si utiliza RAID de software, solo puede implementar un nodo ONTAP Select en el host.


--
Coherencia de hipervisores para los nodos dentro de un clúster:: Todos los hosts de un clúster de ONTAP Select deben ejecutarse en la misma versión y versión del software del hipervisor.
Número de puertos físicos en cada host:: Debe configurar cada host para que use uno, dos o cuatro puertos físicos. Aunque tiene flexibilidad al configurar los puertos de red, debe seguir estas recomendaciones cuando sea posible:
+
--
* Un host en un clúster de un solo nodo debería tener dos puertos físicos.
* Cada host de un clúster multinodo debería tener cuatro puertos físicos


--
Integración de ONTAP Select con un clúster basado en hardware de ONTAP:: No se puede añadir un nodo ONTAP Select directamente a un clúster basado en hardware de ONTAP. Sin embargo, de forma opcional, puede establecer una relación de paridad entre un clúster de ONTAP Select y un clúster de ONTAP basado en hardware.




== Reducida

Existen varios problemas de planificación relacionados con el almacenamiento host que se deben tener en cuenta.

Tipo de RAID:: Cuando se utiliza almacenamiento de conexión directa (DAS) en ESXi, debe decidir si se utilizará una controladora RAID de hardware local o la función RAID de software incluida con ONTAP Select. Si utiliza RAID de software, consulte link:reference_plan_ots_storage.html["Consideraciones sobre almacenamiento y RAID"] si quiere más información.
Almacenamiento local:: Cuando se utiliza el almacenamiento local gestionado por una controladora RAID, debe decidir lo siguiente:
+
--
* Si se utilizan uno o varios grupos RAID
* Si se deben usar una o más LUN


--
Almacenamiento externo:: Al utilizar la solución vNAS de ONTAP Select, debe decidir dónde se encuentran los almacenes de datos remotos y cómo se accede a ellos. VNAS de ONTAP Select admite las siguientes configuraciones:
+
--
* VSAN de VMware
* Cabina de almacenamiento externo genérica


--
Calcular el almacenamiento necesario:: Debe determinar la cantidad de almacenamiento que se requiere para los nodos ONTAP Select. Esta información es necesaria como parte de la adquisición de las licencias adquiridas con la capacidad de almacenamiento. Consulte restricciones de capacidad de almacenamiento si desea obtener más información.



NOTE: La capacidad de almacenamiento de ONTAP Select corresponde al tamaño total permitido de los discos de datos conectados a la máquina virtual ONTAP Select.

Modelo de licencias para la puesta en marcha de entornos de producción:: Debe seleccionar los niveles de capacidad o el modelo de licencia para pools de capacidad para cada clúster de ONTAP Select implementado en un entorno de producción. Consulte la sección _License_ para obtener más información.


.Información relacionada
* link:reference_plan_ots_storage.html["Consideraciones sobre almacenamiento y RAID"]

