---
sidebar: sidebar 
permalink: reference_api_workflow.html 
keywords: rest api, deploy rest api, rest, workflow, create cluster, curl, json 
summary: Puedes desplegar un clúster de un solo nodo ONTAP Select en un host VMware ESXi gestionado por vCenter. 
---
= Crear un clúster de evaluación de ONTAP Select de un solo nodo en ESXi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se puede poner en marcha un clúster de ONTAP Select de un solo nodo en un host VMware ESXi gestionado por vCenter. El clúster se crea con una licencia de evaluación.

El flujo de trabajo de creación del clúster difiere en las siguientes situaciones:

* El host ESXi no está gestionado por vCenter (host independiente).
* Dentro del clúster se utilizan varios nodos u hosts.
* El clúster está implementado en un entorno de producción con una licencia adquirida.
* Se utiliza el hipervisor KVM en lugar de VMware ESXi.




[[step-1-register-vcenter-server-credential]]
== Paso 1: Registrar la credencial del servidor vCenter

Al realizar una implementación en un host ESXi gestionado por un servidor vCenter, necesitas añadir una credencial antes de registrar el host. Luego, la utilidad de administración Deploy puede usar la credencial para autenticarse en vCenter.

[cols="15,15,70"]
|===
| Categoría | Verbo HTTP | Ruta 


| Puesta en marcha | PUBLICAR | /seguridad/credenciales 
|===
Rizo::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step01 'https://10.21.191.150/api/security/credentials'
----
Entrada JSON (paso 01)::


[source, json]
----
{
  "hostname": "vcenter.company-demo.com",
  "type": "vcenter",
  "username": "misteradmin@vsphere.local",
  "password": "mypassword"
}
----
Tipo de procesamiento:: Asíncrona
Salida::
+
--
* ID de credencial en la cabecera de respuesta de ubicación
* Objeto de trabajo


--




[[step-2-register-a-hypervisor-host]]
== Paso 2: Registrar un host de hipervisor

Añade un host de hipervisor donde se ejecutará la máquina virtual que contiene el nodo ONTAP Select.

[cols="15,15,70"]
|===
| Categoría | Verbo HTTP | Ruta 


| Clúster | PUBLICAR | /hosts 
|===
Rizo::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step02 'https://10.21.191.150/api/hosts'
----
Entrada JSON (paso 02)::


[source, json]
----
{
  "hosts": [
    {
      "hypervisor_type": "ESX",
      "management_server": "vcenter.company-demo.com",
      "name": "esx1.company-demo.com"
    }
  ]
}
----
Tipo de procesamiento:: Asíncrona
Salida::
+
--
* ID de host en el encabezado de respuesta de ubicación
* Objeto de trabajo


--




[[step-3-create-a-cluster]]
== Paso 3: crea un clúster

Cuando creas un clúster ONTAP Select, se registra la configuración básica del clúster y Deploy genera automáticamente los nombres de los nodos.

[cols="15,15,70"]
|===
| Categoría | Verbo HTTP | Ruta 


| Clúster | PUBLICAR | /cluster 
|===
Rizo:: Debes establecer el parámetro de consulta node_count en 1 para un clúster de un solo nodo.


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step03 'https://10.21.191.150/api/clusters? node_count=1'
----
Entrada JSON (paso 03)::


[source, json]
----
{
  "name": "my_cluster"
}
----
Tipo de procesamiento:: Síncrona
Salida::
+
--
* ID de clúster en el encabezado de respuesta de ubicación


--




[[step-4-configure-the-cluster]]
== Paso 4: configura el clúster

Debes especificar los siguientes atributos como parte de la configuración del clúster.

[cols="15,15,70"]
|===
| Categoría | Verbo HTTP | Ruta 


| Clúster | PARCHE | /cluster/{cluster_id} 
|===
Rizo:: Indica el ID del clúster.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step04 'https://10.21.191.150/api/clusters/CLUSTERID'
----
Entrada JSON (paso 04)::


[source, json]
----
{
  "dns_info": {
    "domains": ["lab1.company-demo.com"],
    "dns_ips": ["10.206.80.135", "10.206.80.136"]
    },
    "ontap_image_version": "9.5",
    "gateway": "10.206.80.1",
    "ip": "10.206.80.115",
    "netmask": "255.255.255.192",
    "ntp_servers": {"10.206.80.183"}
}
----
Tipo de procesamiento:: Síncrona
Salida:: Ninguno




[[step-5-retrieve-the-node-name]]
== Paso 5: obtener el nombre de nodo

La utilidad de administración Deploy genera automáticamente los identificadores y los nombres de los nodos al crear un clúster. Antes de poder configurar un nodo, necesitas obtener el ID asignado.

[cols="15,15,70"]
|===
| Categoría | Verbo HTTP | Ruta 


| Clúster | OBTENGA | /cluster/{cluster_id}/nodos 
|===
Rizo:: Indica el ID del clúster.


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/clusters/CLUSTERID/nodes?fields=id,name'
----
Tipo de procesamiento:: Síncrona
Salida::
+
--
* La matriz registra cada uno de ellos describiendo un solo nodo con el ID y el nombre únicos


--




[[step-6-configure-the-nodes]]
== Paso 6: configura los nodos

Proporciona la configuración básica del nodo, que es la primera de las tres llamadas a la API que se utilizan para configurar un nodo.

[cols="15,15,70"]
|===
| Categoría | Verbo HTTP | Ruta 


| Clúster | RUTA | /cluster/{cluster_id}/nodes/{node_id} 
|===
Rizo:: Indica el ID del clúster y el ID del nodo.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step06 'https://10.21.191.150/api/clusters/CLUSTERID/nodes/NODEID'
----
Entrada JSON (paso 06):: Indica el ID del host en el que se ejecutará el nodo ONTAP Select.


[source, json]
----
{
  "host": {
    "id": "HOSTID"
    },
  "instance_type": "small",
  "ip": "10.206.80.101",
  "passthrough_disks": false
}
----
Tipo de procesamiento:: Síncrona
Salida:: Ninguno




[[step-7-retrieve-the-node-networks]]
== Paso 7: Recuperar las redes de nodos

Identifica las redes de datos y de gestión que utiliza el nodo en el clúster de un solo nodo. La red interna no se utiliza en un clúster de un solo nodo.

[cols="15,15,70"]
|===
| Categoría | Verbo HTTP | Ruta 


| Clúster | OBTENGA | /cluster/{cluster_id}/nodes/{node_id}/redes 
|===
Rizo:: Indica el ID del clúster y el ID del nodo.


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/ clusters/CLUSTERID/nodes/NODEID/networks?fields=id,purpose'
----
Tipo de procesamiento:: Síncrona
Salida::
+
--
* Matriz de dos registros que describen una sola red para el nodo, incluyendo el identificador único y el propósito


--




[[step-8-configure-the-node-networking]]
== Paso 8: Configura la red del nodo

Configura las redes de datos y de gestión. La red interna no se utiliza en un clúster de un solo nodo.


NOTE: Emita la siguiente llamada API dos veces, una por cada red.

[cols="15,15,70"]
|===
| Categoría | Verbo HTTP | Ruta 


| Clúster | PARCHE | /cluster/{cluster_id}/nodes/{node_id}/networks/{network_id} 
|===
Rizo:: Indica el ID del clúster, el ID del nodo y el ID de red.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step08 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID/networks/NETWORKID'
----
Entrada JSON (paso 08):: Indica el nombre de la red.


[source, json]
----
{
  "name": "sDOT_Network"
}
----
Tipo de procesamiento:: Síncrona
Salida:: Ninguno




[[step-9-configure-the-node-storage-pool]]
== Paso 9: Configura el grupo de almacenamiento del nodo

El paso final de configurar un nodo es conectar un pool de almacenamiento. Se pueden determinar los pools de almacenamiento disponibles a través del cliente web de vSphere, o bien, de manera opcional, mediante la API DE REST Deploy.

[cols="15,15,70"]
|===
| Categoría | Verbo HTTP | Ruta 


| Clúster | PARCHE | /cluster/{cluster_id}/nodes/{node_id}/networks/{network_id} 
|===
Rizo:: Indica el ID del clúster, el ID del nodo y el ID de red.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step09 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID'
----
Entrada JSON (paso 09):: La capacidad del pool es 2 TB.


[source, json]
----
{
  "pool_array": [
    {
      "name": "sDOT-01",
      "capacity": 2147483648000
    }
  ]
}
----
Tipo de procesamiento:: Síncrona
Salida:: Ninguno




[[step-10-deploy-the-cluster]]
== Paso 10: implementa el clúster

Después de configurar el clúster y el nodo, puede implementar el clúster.

[cols="15,15,70"]
|===
| Categoría | Verbo HTTP | Ruta 


| Clúster | PUBLICAR | /cluster/{cluster_id}/deploy 
|===
Rizo:: Indica el ID del clúster.


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step10 'https://10.21.191.150/api/clusters/CLUSTERID/deploy'
----
Entrada JSON (paso 10):: Introduce la contraseña de la cuenta de administrador de ONTAP.


[source, json]
----
{
  "ontap_credentials": {
    "password": "mypassword"
  }
}
----
Tipo de procesamiento:: Asíncrona
Salida::
+
--
* Objeto de trabajo


--


.Información relacionada
link:deploy-evaluation-ontap-select-ovf-template.html["Ponga en marcha una instancia de evaluación de 90 días de un clúster de ONTAP Select"]
