---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: La versión actual incluye varias funciones o mejoras nuevas específicas para ONTAP Select. 
---
= Novedades en ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Obtenga más información sobre las nuevas funciones y mejoras que se ofrecen en las versiones compatibles de ONTAP Select.



== ONTAP Select 9.17.1

ONTAP Select 9.17.1 incluye varias características nuevas y mejoras.

Compatibilidad con RAID de software para discos NVMe conectados localmente en hosts KVM:: ONTAP Select 9.17.1 presenta soporte RAID de software para discos NVMe conectados localmente de ONTAP Select en un host de hipervisor de máquina virtual basada en kernel (KVM).
+
--
Para utilizar RAID de software para discos NVMe conectados localmente, necesita link:kvm-host-configuration-and-preparation-checklist.html["Configurar el paso a través de PCI (DirectPath IO)"] Al preparar el host KVM, esto proporciona acceso directo al host KVM a los discos NVMe conectados localmente, lo cual es necesario para las siguientes tareas:

* Configuración del host KVM para usar unidades NVMe
* Uso de RAID de software después de implementar el clúster


link:concept_stor_swraid_local.html["Obtenga información sobre los servicios de configuración RAID de software para el almacenamiento conectado localmente"] .

--
Soporte para expansión y contracción de clústeres en hosts KVM:: A partir de ONTAP Select 9.17.1, la función de expansión y contracción de clústeres es compatible con máquinas virtuales basadas en kernel (KVM) y hosts con hipervisor ESXi. En ONTAP Select 9.16.1 y 9.15.1, la expansión y contracción de clústeres solo es compatible con hosts con hipervisor ESXi.
+
--
Puede utilizar la función de expansión y contracción de clúster en un clúster ONTAP Select existente para aumentar el tamaño de un clúster de seis nodos a uno de ocho nodos o disminuir el tamaño de un clúster de ocho nodos a uno de seis nodos.

link:task_cluster_expansion_contraction.html["Obtenga información sobre la expansión y contracción del clúster y las versiones de hipervisor KVM y ESXi compatibles"] .

--
Soporte mejorado para la expansión y contracción de clústeres en hosts ESXi:: A partir de ONTAP Select 9.17.1, se admite la expansión y contracción de clústeres de entre seis y doce nodos en hosts ESXi:
+
--
--
Puede aumentar el tamaño del clúster de un clúster ESXi existente en los siguientes incrementos:

* De seis nodos a ocho, diez o doce nodos
* De ocho nodos a diez o doce nodos
* De diez a doce nodos


Puede reducir el tamaño del clúster de un clúster ESXi existente en los siguientes incrementos:

* De doce nodos a diez, ocho o seis nodos
* De diez nodos a ocho o seis nodos
* De ocho a seis nodos


--
link:task_cluster_expansion_contraction.html["Obtenga información sobre la expansión y contracción del clúster y las versiones de hipervisor KVM y ESXi compatibles"] .

--
Compatibilidad con las funciones de ONTAP:: A partir de ONTAP Select 9.17.1, las siguientes funciones con licencia de ONTAP son compatibles con ONTAP Select:
+
--
* Selección de SnapLock
+
A partir de ONTAP Select 9.17.1, las nuevas implementaciones tendrán la licencia SnapLock Select automáticamente.  Para las actualizaciones de ONTAP Select 9.16.1 y anteriores, deberá descargar la licencia de SnapLock Select desdelink:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^] y aplicarlo manualmente.

* Nube SnapMirror
+
A partir de ONTAP Select 9.17.1, SnapMirror Cloud es compatible con ONTAP Select. SnapMirror Cloud es una función con licencia de ONTAP que se habilita de forma predeterminada al implementar un clúster de ONTAP Select 9.17.1 o al actualizar un clúster de ONTAP Select existente a la versión 9.17.1.

+
https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["Obtenga más información sobre las copias de seguridad en la nube de SnapMirror en el almacenamiento de objetos"^] .



--
Compatibilidad con vSAN ESA en clústeres de varios nodos:: A partir de ONTAP Select 9.17.1, se amplía la compatibilidad con la arquitectura de almacenamiento vSAN Express (ESA) para implementar clústeres de múltiples nodos.  Esta mejora le permite implementar configuraciones de vSAN ESA.
+
--
vSAN ESA es una configuración específica de ESX y es una nueva arquitectura para VMware vSAN introducida en vSphere 8. vSAN ESA está diseñado para ofrecer mayor eficiencia, escalabilidad y rendimiento, particularmente cuando se utilizan dispositivos flash TLC basados en NVMe.

ONTAP Select Deploy y ONTAP Select for ESX admiten la configuración de un clúster de ONTAP Select de un solo nodo y de varios nodos, utilizando un vSAN o un tipo de matriz externa de almacén de datos para su grupo de almacenamiento.

[NOTE]
====
Para realizar operaciones en la biblioteca de contenido, necesitará acceso a niveles de permisos adicionales.  Esto es necesario para las implementaciones de vSAN ESA si está trabajando con roles restringidos.

link:https://docs.netapp.com/us-en/ontap-select/reference_plan_dep_vmware.html["Obtenga información sobre cómo acceder a los niveles de permisos para las operaciones de la biblioteca de contenido"^] .

====
--
Compatibilidad actualizada con controladores NDA:: A partir de ONTAP Select 9.17.1, el controlador de dispositivo NDA (Acceso Directo a NVMe) de FreeBSD reemplaza al NVD (controlador de disco NVMe Express). El controlador de FreeBSD proporciona compatibilidad con dispositivos de acceso directo mediante la implementación del protocolo de comandos NVMe. Al implementar un clúster de ONTAP Select 9.17.1 o actualizar un clúster de ONTAP Select existente a la versión 9.17.1, el controlador de FreeBSD se inicia de forma predeterminada al configurar los dispositivos NVMe.
+
--
Para ONTAP Select 9.16.1 y versiones anteriores, NVD continúa brindando soporte para dispositivos NVMe en su implementación de ONTAP Select .

--
Compatibilidad actualizada con hipervisor de KVM:: A partir de ONTAP Select 9.17.1, el hipervisor KVM es compatible con Red Hat Enterprise Linux (RHEL) 9.6 y Rocky Linux 9.6.




== ONTAP Select 9.16.1

ONTAP Select 9.16.1 incluye varias funciones y mejoras nuevas.

Se ha actualizado la compatibilidad con el archivo de licencia de NetApp:: A partir de ONTAP Select 9.16.1, se actualiza el soporte para el archivo de licencia de NetApp (NLF). El nuevo formato NLF incluye licencias para las funciones ARP, ONTAP S3 y S3 SnapMirror. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Leer más"].
+
--
Para una nueva implementación de ONTAP Select 9.16.1, se aplica automáticamente el nuevo formato NLF. Cuando se actualiza una implementación de ONTAP Select existente a 9.16.1, no se aplica el nuevo formato NLF. Para obtener las licencias de funciones ARP, ONTAP S3 y S3 SnapMirror, debe descargar la NLF actualizada después de la actualización. Si vuelve a ONTAP Select 9.15.1 o anterior, debe volver a instalar las licencias de funciones que tenía antes de la actualización.

--
Soporte para protección autónoma frente a ransomware:: ONTAP Select 9.16.1 presenta compatibilidad con la protección autónoma contra ransomware (ARP). ONTAP Select 9.16.1 solo admite actualizaciones manuales para ARP, no se admiten actualizaciones automáticas. La licencia de función ARP se incluye en NLF para ONTAP Select 9.16.1. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Leer más"].
Compatibilidad con VMware ESXi mejorada:: ONTAP Select 9.16.1 incluye compatibilidad con VMware ESXi 8.0 U3.
Compatibilidad actualizada con hipervisor de KVM:: A partir de ONTAP Select 9.16.1, el hipervisor KVM es compatible con RHEL 9.5 y Rocky Linux 9.5.




== ONTAP Select 9.15.1

ONTAP Select 9.15.1 incluye varias funciones y mejoras nuevas.

Compatibilidad actualizada con hipervisor de KVM:: A partir de ONTAP Select 9.15.1, el hipervisor de máquina virtual basada en kernel (KVM) es compatible con RHEL 9,4 y Rocky Linux 9,4.
Soporte para la expansión y la contracción de clústeres:: A partir de ONTAP Select 9.15.1, se admiten la expansión y contracción de clústeres.
+
--
* Ampliación de clúster desde clústeres de seis nodos a ocho nodos
+
Se puede aumentar el tamaño del clúster de un clúster de seis nodos a uno de ocho nodos con la función de ampliación de clústeres. Actualmente no se admiten las ampliaciones de clústeres de uno, dos o cuatro nodos a clústeres de seis u ocho nodos. link:task_cluster_expansion_contraction.html#expand-the-cluster["Leer más"].

* Contracción de clústeres de ocho nodos a clústeres de seis nodos
+
Puede reducir el tamaño del clúster de ocho nodos a un clúster de seis nodos con la función de contracción de clústeres. Actualmente no se admiten las contracciones de clústeres de seis o ocho nodos a uno, dos o cuatro clústeres de nodos. link:task_cluster_expansion_contraction.html#contract-the-cluster["Leer más"].



--



NOTE: El soporte para la ampliación y la contracción de clústeres se limita solo a clústeres ESX.



== ONTAP Select 9.14.1

ONTAP Select 9.14.1 incluye varias funciones y mejoras nuevas.

Compatibilidad con hipervisor KVM:: A partir de ONTAP Select 9.14.1, se ha restablecido el soporte para el hipervisor KVM. Anteriormente, en ONTAP Select 9.10.1 se eliminó la compatibilidad para poner en marcha un clúster nuevo en un hipervisor KVM y se eliminó la compatibilidad con la administración de hosts y clústeres KVM existentes, excepto para desconectar o eliminar, en ONTAP Select 9.11.1.
Ya no se admite la implementación del complemento de VMware vCenter:: A partir de ONTAP Select 9.14.1, ya no se admite el complemento para implementar VMware vCenter.
Soporte actualizado de ONTAP Select Deploy:: Si está ejecutando una versión de ONTAP Select Deploy 9.14.1 inferior a 9.14.1P2, debe actualizar a ONTAP Select Deploy 9.14.1P2 lo antes posible. Para obtener más información, consulte link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notas de la versión de ONTAP Select 9.14.1"^].
Compatibilidad con VMware ESXi mejorada:: ONTAP Select 9.14.1 incluye compatibilidad con VMware ESXi 8.0 U2.




== ONTAP Select 9.13.1

ONTAP Select 9.13.1 incluye varias funciones y mejoras nuevas.

Compatibilidad con NVMe sobre TCP:: Cuando actualice a ONTAP Select 9.13.1, debe tener la nueva licencia para admitir NVMe over TCP. Esta licencia se incluye automáticamente cuando se implementa ONTAP Select por primera vez desde la versión 9.13.1.
Se ha actualizado el soporte de VMware ESXi:: A partir de ONTAP 9.13,1, se admite VMware ESXi 8.0.1 GA (compilación 20513097) con las versiones de hardware 4 y posteriores.
Soporte actualizado de ONTAP Select Deploy:: A partir de abril de 2024, ONTAP Select Deploy 9.13.1 ya no está disponible en el sitio de soporte de NetApp. Si ejecuta ONTAP Select Deploy 9.13.1, debe actualizar a ONTAP Select Deploy 9.14.1P2 lo antes posible. Para obtener más información, consulte link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notas de la versión de ONTAP Select 9.14.1"^].




== ONTAP Select 9.12.1

ONTAP Select 9.12.1 se beneficia de la mayoría de los nuevos desarrollos en la versión actual del producto principal de ONTAP. No incluye ninguna nueva función ni mejora específica de ONTAP Select.

A partir de abril de 2024, ONTAP Select Deploy 9.12.1 ya no está disponible en el sitio de soporte de NetApp. Si ejecuta ONTAP Select Deploy 9.12.1, debe actualizar a ONTAP Select Deploy 9.14.1P2 lo antes posible. Para obtener más información, consulte link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notas de la versión de ONTAP Select 9.14.1"^].



== ONTAP Select 9.11.1

ONTAP Select 9.11.1 incluye varias características y mejoras nuevas.

Compatibilidad con VMware ESXi mejorada:: ONTAP Select 9.11.1 incluye compatibilidad con VMware ESXi 7.0 U3C.
Compatibilidad con NSX-T de VMware:: ONTAP Select 9.10.1 y versiones posteriores están cualificados para NSX-T de VMware, versión 3.1.2. No existen problemas ni deficiencias funcionales cuando se usa NSX-T con un clúster de un único nodo de ONTAP Select implementado con un archivo OVA y la utilidad de administración de ONTAP Select Deploy. Sin embargo, si utiliza NSX-T con un clúster de varios nodos de ONTAP Select, debería tener en cuenta la siguiente limitación para ONTAP Select 9.11.1:
+
--
* Comprobador de conectividad de red
+
El comprobador de conectividad de red disponible a través de la CLI de implementación genera errores cuando se ejecuta en una red basada en NSX-T.



--
Ya no se admite el hipervisor KVM::
+
--
* A partir de ONTAP Select 9.10.1, ya no es posible poner en marcha un clúster nuevo en el hipervisor KVM.
* A partir de ONTAP Select 9.11.1, toda la funcionalidad de capacidad de gestión ya no está disponible para los clústeres y hosts KVM existentes, excepto para las funciones de desconectar y eliminar.
+
NetApp recomienda a los clientes planificar y ejecutar una migración completa de datos desde ONTAP Select para KVM a cualquier otra plataforma ONTAP, incluido ONTAP Select para ESXi. Para obtener más información, consulte https://mysupport.netapp.com/info/communications/ECMLP2877451.html["Aviso de EOA"^]



--




== ONTAP Select 9.10.1

ONTAP Select 9.10.1 incluye varias características y mejoras nuevas.

Compatibilidad con NSX-T de VMware:: ONTAP Select 9.10.1 ha sido cualificado para VMware NSX-T versión 3.1.2. No existen problemas ni deficiencias funcionales cuando se usa NSX-T con un clúster de un único nodo de ONTAP Select implementado con un archivo OVA y la utilidad de administración de ONTAP Select Deploy. Sin embargo, si utiliza NSX-T con un clúster de varios nodos de ONTAP Select, debería tener en cuenta los siguientes requisitos y limitaciones:
+
--
* MTU del clúster
+
Debe ajustar manualmente el tamaño de MTU del clúster a 8800 antes de poner en marcha el clúster para tener en cuenta la sobrecarga adicional. Las directrices de VMware permiten un búfer de 200 bytes cuando se usa NSX-T.

* Configuración de red 4 x 10 GB
+
Para implementaciones de ONTAP Select en un host VMware ESXi configurado con cuatro NIC, la utilidad Deploy le solicitará que siga la práctica recomendada de dividir el tráfico interno entre dos grupos de puertos distintos y el tráfico externo entre dos grupos de puertos diferentes. Sin embargo, cuando se utiliza una red de superposición, esta configuración no funciona y debe ignorar la recomendación. En este caso, debería utilizar sólo un grupo de puertos interno y un grupo de puertos externo.

* Comprobador de conectividad de red
+
El comprobador de conectividad de red disponible a través de la CLI de implementación genera errores cuando se ejecuta en una red basada en NSX-T.



--
Ya no se admite el hipervisor KVM:: A partir de ONTAP Select 9.10.1, ya no es posible poner en marcha un clúster nuevo en el hipervisor KVM. Sin embargo, si actualiza un clúster de una versión anterior a la versión 9.10.1, puede seguir utilizando la utilidad Deploy para administrar el clúster.




== ONTAP Select 9.9.1

ONTAP Select 9.9.1 incluye varias características y mejoras nuevas.

Compatibilidad con la familia de procesadores:: A partir de ONTAP Select 9,9.1, solo los modelos de CPU de Intel Xeon Sandy Bridge o posteriores son compatibles con ONTAP Select.
Se ha actualizado el soporte de VMware ESXi:: La compatibilidad con VMware ESXi se ha mejorado con ONTAP Select 9.9.1. Ahora se admiten las siguientes versiones:
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

ONTAP Select 9.8 incluye varias funciones nuevas y modificadas.

Interfaz de alta velocidad:: La función de interfaz de alta velocidad mejora la conectividad de red al proporcionar una opción para 25 G (25 GbE) y 40 G (40 GbE). Para lograr el mejor rendimiento al usar estas velocidades superiores, debe seguir las prácticas recomendadas con respecto a las configuraciones de asignación de puertos, como se describe en la documentación de ONTAP Select.
Se ha actualizado el soporte de VMware ESXi:: ONTAP Select 9.8 tiene dos cambios relacionados con la compatibilidad con VMware ESXi.
+
--
* ESXi 7.0 es compatible (GA Build 15843807 y posterior)
* ESXi 6.0 ya no es compatible


--

