---
sidebar: sidebar 
permalink: reference_initial_state.html 
keywords: install, installing, initial state, cluster initial state 
summary: Debe conocer el estado inicial de un clúster después de haberse implementado y configurar el clúster según sea necesario para su entorno. 
---
= El estado inicial del clúster después de la implementación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe conocer el estado inicial de un clúster después de haberse implementado y configurar el clúster según sea necesario para su entorno.

Un clúster de ONTAP Select tiene varias características después de crearlo.


NOTE: La restricción de los roles y permisos de la cuenta de administrador de ONTAP puede limitar la capacidad de ONTAP Select Deploy de gestionar el clúster. Para obtener más información, consulte el artículo de la base de conocimientos link:https://kb.netapp.com/onprem/ontap/ONTAP_Select/OTS_Deploy_cluster_refresh_fails_with_error%3A_ONTAPSelectSysCLIVersionFailed_zapi_returned_bad_status_0%3A_None["El refrescamiento del cluster de despliegue de OTS falla con error"^].

.LIF
Hay dos tipos de LIF asignadas por el cliente:

* Gestión de clústeres (uno por clúster)
* Gestión de nodos (uno por nodo)


.SVM
Hay dos SVM administrativas activas:

* SVM predeterminada
* SVM de clúster


.Agregados
Se crea el agregado raíz.

.Funciones
Todas las funciones están sujetas a licencia y están disponibles. Tanto SnapLock como FabricPool requieren licencias independientes.


NOTE: No se crean SVM de datos. Además, el clúster de varios nodos tiene una red interna con LIF autogeneradas.

.Información relacionada
* link:reference_lic_ontap_features.html["Funciones de ONTAP habilitadas de forma predeterminada"]

