---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select ofrece compatibilidad total para la mayoría de las funcionalidades de ONTAP. Muchas de las funciones de ONTAP se conceden automáticamente con licencia para cada nodo cuando se pone en marcha un clúster. Sin embargo, algunas funciones requieren una licencia independiente. 
---
= Compatibilidad de ONTAP Select con las funciones de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select admite la mayoría de las funciones de ONTAP . Muchas de las funciones de ONTAP se licencian automáticamente para cada nodo al implementar un clúster. Sin embargo, algunas funciones requieren una licencia independiente.


NOTE: Las funciones de ONTAP con dependencias específicas de hardware generalmente no son compatibles con ONTAP Select.



== Las funciones de ONTAP se habilitan automáticamente de forma predeterminada

Las siguientes funciones de ONTAP son compatibles con ONTAP Select y tienen licencia de forma predeterminada:

* Protección autónoma contra ransomware (ARP) (actualizaciones manuales)
* CIFS
* Deduplicación y compresión
* FlexCache
* FlexClone
* ISCSI
* NDMP
* Cifrado de volúmenes de NetApp (solo países no restringidos)
* NFS
* NVMe sobre TCP
* Capacidad de multi-tenancy de ONTAP
* ONTAP S3
* SnapMirror S3
* SnapMirror
* Nube SnapMirror
* SnapRestore
* SnapVault
* Recuperación ante desastres de máquina virtual de almacenamiento (DR de SVM)
+

NOTE: ONTAP Select admite la recuperación de desastres de SVM como origen y destino con un máximo de 16 relaciones. La compatibilidad con la recuperación ante desastres de SVM se limita al uso de la versión ONTAP de origen a las versiones +2. Por ejemplo, el origen de ONTAP Select 9.12.1 puede conectarse a las versiones 9.12.1, 9.13.1 o 9.14.1 de ONTAP de destino.





== Funciones de ONTAP con licencias independientes

Debe adquirir una licencia independiente para cualquier función de ONTAP que no esté habilitada de forma predeterminada, incluidas:

* FabricPool
* SDS de MetroCluster (oferta de licencia premium de ONTAP Select)


[NOTE]
====
* Para ONTAP Select 9.16.1 y versiones anteriores, SnapLock Select Enterprise (incluido el bloqueo de instantáneas a prueba de manipulaciones) está disponible enlink:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^] .
* La SnapLock Compliance no es compatible con ONTAP Select.
* No necesita una licencia de FabricPool cuando utilice StorageGRID.


====
.Información relacionada
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["Comparación entre ONTAP Select y ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Claves de licencia maestra de ONTAP de NetApp"^]

