---
sidebar: sidebar 
permalink: reference_vpi_troubleshooting.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, troubleshooting 
summary: Debe saber cuáles son las técnicas de solución de problemas disponibles y los errores comunes como parte del soporte del plugin de implementación de vCenter. 
---
= Resolución de problemas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe saber cuáles son las técnicas de solución de problemas disponibles y los errores comunes como parte del soporte del plugin de implementación de vCenter.



== Errores de instalación, desinstalación y actualización

Si se produce un error durante un procedimiento de instalación, desinstalación o actualización, la API devuelve un mensaje de error que muestra la interfaz de implementación que se usa para iniciar el procedimiento (interfaz de usuario web o CLI).

Los errores comunes incluyen los siguientes:

* Credenciales incorrectas (nombre de usuario o contraseña)
* Falta el plugin especificado para la instalación o no es válido
* El servidor vCenter está fuera de línea o no se puede acceder a él


Para obtener información adicional sobre un error, examine los siguientes registros:

* Despliegue el registro del servidor
* Registro del servidor de vCenter




== Errores de plugin en vCenter

Si se produce un error durante una sesión con vCenter, se muestra un mensaje de error. Los errores comunes incluyen los siguientes:

* No se pudo cargar el contenido integrado en vCenter desde el servidor de implementación debido a que el certificado SSL del servidor de implementación no se aceptó en el explorador.
* El servidor de puesta en marcha no autoriza el ID de sesión para un usuario de vCenter que intenta acceder al plugin de puesta en marcha de vCenter. Se agota el tiempo de espera de la sesión.
* Privilegios insuficientes para acceder al complemento de vCenter de implementación.
* El servidor de despliegue está fuera de línea o no se puede acceder a él.


Para obtener más información sobre un error, consulte los siguientes registros:

* Registro del servidor de vCenter
* Despliegue el registro del servidor

