---
sidebar: sidebar 
permalink: reference_plan_ots_general.html 
keywords: plan, planning, general requirements 
summary: Hay varios requisitos generales que se deben tener en cuenta como parte de la planificación de una puesta en marcha de ONTAP Select. 
---
= Requisitos y consideraciones de planificación de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Existen varios requisitos generales que se deben tener en cuenta como parte de la planificación de una puesta en marcha de ONTAP Select.



== Conocimientos y habilidades de Linux necesarios para KVM

Linux con el hipervisor KVM es un entorno complejo en el que trabajar. Antes de implementar ONTAP Select en KVM, debe contar con los conocimientos y habilidades necesarios.

Distribución de servidores Linux:: Debe contar con experiencia con la distribución de Linux específica que se utilizará para la puesta en marcha de ONTAP Select. Específicamente, debe ser capaz de realizar las siguientes tareas:
+
--
* Instale la distribución de Linux
* Configure el sistema con la CLI
* Agregue paquetes de software, así como cualquier dependencia


--


Para obtener más información sobre la preparación del servidor Linux, incluidos los paquetes de software y configuración necesarios, consulte la lista de comprobación de configuración del host. Consulte los requisitos del hipervisor para las distribuciones de Linux actualmente compatibles.

Instalación y administración de KVM:: Debería estar familiarizado con los conceptos generales de virtualización. Además, existen varios comandos de la CLI de Linux que debe utilizar como parte de la instalación y administración de ONTAP Select en un entorno KVM:
+
--
* `virt-install`
* `virsh`
* `lsblk`
* `lvs`
* `vgs`
* `pvs`


--
Configuración de redes y Open vSwitch:: Debe estar familiarizado con los conceptos de red y la configuración de los switches de red. Además, deberías tener experiencia con Open vSwitch. Debe utilizar los siguientes comandos de red en parte de la configuración de la red de ONTAP Select en un entorno KVM:
+
--
* `ovs-vsctl`
* `ip`
* `ip link`
* `systemctl`


--




== Tamaño del clúster y consideraciones relacionadas

Hay varios problemas de planificación relacionados con el tamaño del clúster que debe tener en cuenta.

Número de nodos en el clúster:: Un clúster de ONTAP Select se compone de uno, dos, cuatro, seis u ocho nodos. Debe determinar el tamaño del clúster de acuerdo con los requisitos de la aplicación. Por ejemplo, si se necesita una capacidad de alta disponibilidad para una puesta en marcha empresarial, se debe utilizar un clúster de varios nodos.
Dedicado versus colubicado:: En función del tipo de aplicación, debe determinar si la implementación sigue el modelo dedicado o colubicado. Tenga en cuenta que el modelo de colocación puede ser más complejo debido a la diversidad de la carga de trabajo y a una integración más estrecha.




== Consideraciones del host del hipervisor

Existen varios problemas de planificación relacionados con el host del hipervisor que debe tener en cuenta.


CAUTION: No se debe modificar directamente la configuración de una máquina virtual de ONTAP Select a menos que el soporte de NetApp le indique hacerlo. Sólo se debe configurar y modificar una máquina virtual mediante la utilidad de administración de despliegue. Si se realizan cambios en una máquina virtual de ONTAP Select fuera de la utilidad de implementación sin la ayuda del soporte de NetApp, es posible que la máquina virtual falle y quede inutilizable.

Independiente del hipervisor:: Tanto ONTAP Select como la utilidad de administración de ONTAP Select Deploy son independientes del hipervisor. Los siguientes hipervisores son compatibles con ambos.
+
--
* VMware ESXi
* Máquina virtual basada en kernel (KVM)


--



NOTE: A partir de ONTAP Select 9.14.1, se ha restablecido el soporte para el hipervisor KVM. Anteriormente, en ONTAP Select 9.10.1 se eliminó la compatibilidad para poner en marcha un clúster nuevo en un hipervisor KVM y se eliminó la compatibilidad con la administración de hosts y clústeres KVM existentes, excepto para desconectar o eliminar, en ONTAP Select 9.11.1.

Consulte la información de planificación específica del hipervisor y las notas de la versión para obtener más detalles sobre las plataformas compatibles.

Hipervisor para nodos ONTAP Select y utilidad de administración:: Tanto la utilidad de administración de implementación como los nodos ONTAP Select se ejecutan como máquinas virtuales. El hipervisor que elija para la utilidad de puesta en marcha es independiente del hipervisor que elija para los nodos ONTAP Select. Dispone de flexibilidad completa al emparejar los dos:
+
--
* La utilidad de puesta en marcha que se ejecuta en VMware ESXi puede crear y gestionar clústeres de ONTAP Select en VMware ESXi o KVM
* La utilidad de puesta en marcha que se ejecuta en KVM puede crear y gestionar clústeres de ONTAP Select en VMware ESXi o KVM


--
Una o más instancias de nodo ONTAP Select por host:: Cada nodo ONTAP Select se ejecuta como máquina virtual dedicada. Puede crear varios nodos en el mismo host del hipervisor, con las siguientes restricciones:
+
--
* No se pueden ejecutar varios nodos desde un único clúster de ONTAP Select en el mismo host. Todos los nodos de un host específico deben tener clústeres de ONTAP Select diferentes.
* Debe usar almacenamiento externo.
* Si utiliza RAID de software, solo puede implementar un nodo ONTAP Select en el host.


--
Coherencia de hipervisores para los nodos dentro de un clúster:: Todos los hosts de un clúster de ONTAP Select deben ejecutarse en la misma versión y versión del software del hipervisor.
Número de puertos físicos en cada host:: Debe configurar cada host para que use uno, dos o cuatro puertos físicos. Aunque tiene flexibilidad al configurar los puertos de red, debe seguir estas recomendaciones cuando sea posible:
+
--
* Un host en un clúster de un solo nodo debería tener dos puertos físicos.
* Cada host de un clúster multinodo debería tener cuatro puertos físicos


--
Integración de ONTAP Select con un clúster basado en hardware de ONTAP:: No se puede añadir un nodo ONTAP Select directamente a un clúster basado en hardware de ONTAP. Sin embargo, de forma opcional, puede establecer una relación de paridad entre un clúster de ONTAP Select y un clúster de ONTAP basado en hardware.




== Consideraciones sobre el almacenamiento

Existen varios problemas de planificación relacionados con el almacenamiento host que se deben tener en cuenta.

Tipo de RAID:: Cuando se utiliza almacenamiento de conexión directa (DAS) en ESXi, debe decidir si se utilizará una controladora RAID de hardware local o la función RAID de software incluida con ONTAP Select. Si utiliza RAID de software, consulte link:reference_plan_ots_storage.html["Consideraciones sobre almacenamiento y RAID"] si quiere más información.
Almacenamiento local:: Cuando se utiliza el almacenamiento local gestionado por una controladora RAID, debe decidir lo siguiente:
+
--
* Si se utilizan uno o varios grupos RAID
* Si se deben usar una o más LUN


--
Almacenamiento externo:: Al utilizar la solución vNAS de ONTAP Select, debe decidir dónde se encuentran los almacenes de datos remotos y cómo se accede a ellos. VNAS de ONTAP Select admite las siguientes configuraciones:
+
--
* VSAN de VMware
* Cabina de almacenamiento externo genérica


--
Calcular el almacenamiento necesario:: Debe determinar la cantidad de almacenamiento que se requiere para los nodos ONTAP Select. Esta información es necesaria como parte de la adquisición de las licencias adquiridas con la capacidad de almacenamiento. Consulte restricciones de capacidad de almacenamiento si desea obtener más información.



NOTE: La capacidad de almacenamiento de ONTAP Select corresponde al tamaño total permitido de los discos de datos conectados a la máquina virtual ONTAP Select.

Modelo de licencias para la puesta en marcha de entornos de producción:: Debe seleccionar el modelo de licencia de niveles de capacidad o pools de capacidad para cada clúster de ONTAP Select puesto en marcha en un entorno de producción. Consulte la sección _License_ para obtener más información.




== Autenticación mediante el almacén de credenciales

El almacén de credenciales de despliegue de ONTAP Select es una base de datos que contiene información de cuenta. La implementación utiliza las credenciales de la cuenta para realizar la autenticación del host como parte de la creación y la gestión del clúster. Debe saber cómo se utiliza el almacén de credenciales como parte de la planificación de una implementación de ONTAP Select.


NOTE: La información de la cuenta se almacena de forma segura en la base de datos mediante el algoritmo de cifrado Advanced Encryption Standard (AES) y el algoritmo hash SHA-256.

Tipos de credenciales:: Se admiten los siguientes tipos de credenciales:
+
--
* host
+
La credencial *host* se utiliza para autenticar un host de hipervisor como parte de la implementación de un nodo ONTAP Select directamente en ESXi o KVM.

* vcenter
+
La credencial *vcenter* se utiliza para autenticar un servidor vCenter como parte de la implementación de un nodo ONTAP Select en ESXi cuando VMware vCenter administra el host.



--
Acceso:: Se accede al almacén de credenciales internamente como parte de la realización de tareas administrativas normales mediante la implementación, como la adición de un host de hipervisor. También puede gestionar el almacén de credenciales directamente a través de la interfaz de usuario web de implementación y la CLI.


.Información relacionada
* link:reference_plan_ots_storage.html["Consideraciones sobre almacenamiento y RAID"]

