---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: Existen varios problemas relacionados con los requisitos de hardware y planificación que debe tener en cuenta en relación con el entorno de VMware. 
---
= Consideraciones sobre hardware e hipervisor VMware de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Existen varios problemas relacionados con los requisitos de hardware y planificación que debe tener en cuenta en relación con el entorno de VMware.



== Requisitos de hipervisor

Hay varios requisitos relacionados con el hipervisor donde se ejecuta ONTAP Select.


NOTE: Deberías revisar ellink:reference_release_notes.html["Notas de la versión de ONTAP Select"] para cualquier otra restricción o limitación conocida.



=== Licencias de VMware

Para poner en marcha un clúster de ONTAP Select, su organización debe tener una licencia de VMware vSphere válida para los hosts de hipervisores donde se ejecuta ONTAP Select. Debe utilizar las licencias adecuadas para la implementación.



=== Compatibilidad de software

Puede implementar ONTAP Select en hipervisores KVM y ESXi.

[role="tabbed-block"]
====
.KVM
--
ONTAP Select admite las siguientes versiones de hipervisor KVM:

* KVM en Red Hat Enterprise Linux (RHEL) 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.2, 9.1, 9.0, 8.8, 8.7 y 8.6
* KVM en Rocky Linux 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 y 8.6


[NOTE]
====
Existen limitaciones de flujo de trabajo RAID por software para hipervisores KVM en hosts RHEL 10.1 y 10.0 y Rocky Linux 10.0. Para más información, consulta los siguientes artículos de la base de conocimientos:

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: Mensaje de advertencia al crear el clúster HWR con RHEL 10 y ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: Los grupos de almacenamiento y los discos de almacenamiento no son visibles para SWR en la página de creación de clústeres en hosts con RHEL10/Rocky 10"^]


====
--
.ESXi
--
ONTAP Select admite las siguientes versiones de hipervisor ESXi:

* VMware ESXi 9.0
* VMware ESXi 8,0 U3
* VMware ESXi 8,0 U2
* VMware ESXi 8,0 U1 (compilación 21495797)
* VMware ESXi 8,0 GA (compilación 20513097)



NOTE: NetApp es compatible con ONTAP Select en las versiones identificadas de ESXi siempre que VMware también siga siendo compatible con las mismas versiones.


NOTE: ESXi 7.0 GA ha alcanzado el fin de su estado de disponibilidad.  Si tiene clústeres ONTAP Select con esta versión, debe actualizarlos a las versiones compatibles según lo indicado en el documento. https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad (IMT)"^] .

--
====


=== VMware vCenter y hosts ESXi independientes

Si un host del hipervisor ESXi se gestiona mediante una instancia de vCenter Server, debe registrar el host en la utilidad de administración de puesta en marcha con las credenciales de vCenter. No es posible registrar el host como un host independiente con las credenciales ESXi.



== Requisitos centrales de hardware

El host del hipervisor físico en el que se ponga en marcha ONTAP Select debe cumplir varios requisitos de hardware. Puede elegir cualquier plataforma para el host del hipervisor, siempre que cumpla los requisitos mínimos de hardware. Los siguientes proveedores ofrecen plataformas de hardware compatibles: Cisco, Dell, HP, Fujitsu, Lenovo, Y Supermicro.


NOTE: A partir de ONTAP Select 9.9.1, solo se admiten modelos de CPU basados ​​en Intel Xeon Sandy Bridge o posteriores.

Consulte el documento https://mysupport.netapp.com/matrix["Herramienta de Matriz de Interoperabilidad,window=_blank"] si desea obtener más información.



=== Requisitos básicos de hardware

Existen varios requisitos de hardware comunes que se aplican a todas las plataformas independientemente del tipo de instancia del nodo o de la oferta de licencia.

.Procesador
Los microprocesadores compatibles incluyen procesadores Intel Xeon para servidor, consulte link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["Procesadores Intel Xeon,window=_blank"] Para más información.


NOTE: Los procesadores Advanced Micro Devices (AMD) no son compatibles con ONTAP Select.

.Configuración de Ethernet
El tamaño del clúster admite varias configuraciones de Ethernet.

[cols="2,3,3"]
|===
| Tamaño del clúster | Requisitos mínimos | Requisitos recomendados 


| Clúster de un solo nodo | 2 x 1 GbE | 2 x 10 GbE 


| Clúster de dos nodos o SDS de MetroCluster | 4 x 1 GbE o 1 x 10 GbE | 2 x 10 GbE 


| clúster de cuatro, seis, ocho, diez o doce nodos | 2 x 10 GbE | 4 x 10 GbE o 2 x 25 GbE 
|===


=== Requisitos de hardware adicionales basados en el tipo de instancia

Existen varios requisitos de hardware adicionales según el tipo de instancia del nodo.

Consulte link:concept_lic_platforms.html["Conozca las ofertas de licencias de la plataforma"] si quiere más información.

[cols="a1,a2,a2,a2"]
|===
| Tamaño del nodo | núcleos de CPU | Memoria | Oferta de licencia de plataforma requerida 


| Pequeño | Seis núcleos físicos o más, con cuatro reservados para ONTAP Select | 24 GB o más, con 16 GB reservados para ONTAP Select | Estándar, premium o premium XL 


| Mediano | Diez núcleos físicos o más, con ocho reservados para ONTAP Select | 72 GB o más, con 64 GB reservados para ONTAP Select | Premium o premium XL 


| Grande | Dieciocho núcleos físicos o más, con dieciséis reservados para ONTAP Select | 136 GB o más, con 128 GB reservados para ONTAP Select | Premium XL 
|===

NOTE: Existen requisitos de disco adicionales basados en la licencia de la plataforma. Consulte link:reference_plan_ots_storage.html["Almacenamiento y RAID"] si quiere más información.
