---
sidebar: sidebar 
permalink: sizing-capacity-pool-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: La licencia Capacity Tiers se basa en la capacidad de disco subyacente gestionada por cada nodo y no en la capacidad utilizable del nodo, HA-pair o clúster. Cada licencia Capacity Tiers se asigna a un número de serie de nodo individual para una capacidad especificada y requiere un contrato de soporte adjunto. 
---
= Consideraciones para dimensionar una licencia de ONTAP Select Capacity Pools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La capacidad licenciada de una licencia de Capacity Pool se expresa en unidades completas de TB, con un mínimo de 2 TB. Calculas la capacidad licenciada multiplicando la cantidad de espacio utilizable por el factor de sobrecarga. El factor de sobrecarga estima la capacidad de sobrecarga del software ONTAP Select que se deducirá del espacio utilizable y se aplica para determinar la capacidad de ONTAP Select para unidades NVMe, SSD, HDD o virtuales. El factor de sobrecarga varía entre los clústeres de un solo nodo y los de varios nodos (basados en pares de alta disponibilidad):

* El factor de sobrecarga para clústeres de un solo nodo es 1,13
* El factor de sobrecarga para clústeres multinodo es 2.67


Debes calcular la capacidad con licencia basándote en el espacio utilizable para asegurarte de que tienes suficiente para tu implementación. Por ejemplo, quieres 20 TB de capacidad utilizable para un par de alta disponibilidad (10 TB por nodo):

* Con un par de alta disponibilidad (HA), los datos se duplican entre ambos nodos para redundancia, así que para 20 TB de datos utilizables en un par de HA, necesitas tener 20 TB por nodo, en caso de que uno de los nodos quede fuera de línea.
* El factor de 2,67 duplica la capacidad de cada nodo y añade la capacidad de reserva (0,67) necesaria para que ONTAP Select funcione.
* La capacidad de la licencia por nodo es de 27 TB (10 × 2,67 = 26,7). Para el par de alta disponibilidad (HA), necesitas dos licencias de 27 TB para tener 20 TB de capacidad utilizable.


[cols="25,30,45"]
|===
| Descripción | Clúster de un solo nodo | Par de HA o combinación de par de HA y nodo único 


| Espacio utilizable | 20 TB | 10 TB por clúster de un solo nodo 20 TB por par de HA 


| Espacio licenciado | 23 TB (20 x 1,13 = 22,6, redondea al siguiente TB completo) | 54 TB (20 x 2,67 = 53,4, redondea al siguiente TB completo) 


| Espacio máximo utilizable por nodo *Nota*: El espacio máximo gestionado por nodo o par de HA es 400 TB | 353 TB (400 / 1.13)  a| 
Por cada nodo individual en un clúster:

149 TB (400 / 2.67)

Por cada par de HA en un clúster:

298 TB (2 x 149)

|===
.Qué sigue
link:task_lic_acquire_cp.html["Adquiere una licencia de Capacity Pools para ONTAP Select"]
