---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: Puede actualizar una máquina virtual de la utilidad de implementación existente en su sitio mediante la interfaz de línea de comandos. 
---
= Actualizar una instancia de despliegue de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede actualizar una máquina virtual de la utilidad ONTAP Select Deploy existente en el lugar mediante la CLI de la utilidad ONTAP Select Deploy.

.Antes de empezar
Asegúrese de que ONTAP Select Deploy no se utilice para realizar ninguna otra tarea durante la actualización.  Consulte las notas de la versión actual para obtener información y restricciones sobre la actualización de la utilidad ONTAP Select Deploy.

[NOTE]
====
Si tiene instalada una instancia anterior de la utilidad de administración de implementación de ONTAP Select, debe actualizar a la versión actual. El nodo de ONTAP Select y los componentes de puesta en marcha de ONTAP Select se actualizan de forma independiente. Consulte link:concept_adm_upgrading_nodes.html["Actualice los nodos ONTAP Select"^] para obtener más detalles.

Puede actualizar directamente a ONTAP Select Deploy 9.17.1 desde ONTAP Select Deploy 9.16.1 o 9.15.1. Para actualizar desde ONTAP Select Deploy 9.14.1 o una versión anterior, revise las notas de la versión de su versión de ONTAP Select .

====


== Paso 1: Descargue el paquete

Para comenzar el proceso de actualización, descargue el archivo de actualización de máquina virtual ONTAP Select Deploy apropiado desdelink:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^] . El paquete de actualización está en un único archivo comprimido.

.Pasos
. Acceda a link:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^] Usando un navegador web y elija *Descargas* en el menú Descargas.
. Desplácese hacia abajo y seleccione *Actualización de implementación de ONTAP Select*.
. Seleccione la versión deseada del paquete de actualización.
. Revise el Contrato de licencia de usuario final (EULA) y seleccione *Aceptar y continuar*.
. Seleccione y descargue el paquete adecuado, respondiendo a todos los avisos según sea necesario para su entorno.




== Paso 2: Cargue el paquete en la máquina virtual ONTAP Select Deploy

Después de descargar el paquete, debe cargar el archivo en la máquina virtual ONTAP Select Deploy.

.Acerca de esta tarea
Esta tarea describe un método para cargar el archivo en la máquina virtual ONTAP Select Deploy.  Podrían existir otras opciones más adecuadas para su entorno.

.Antes de empezar
* Verifique que el archivo de actualización esté disponible en su estación de trabajo local.
* Verifique que tenga la contraseña de la cuenta de usuario administrador.


.Pasos
. En un shell de comandos en su estación de trabajo local, utilice el `scp` Utilidad (Protocolo de copia segura) para cargar el archivo de imagen a la máquina virtual ONTAP Select Deploy.
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.Resultado
El archivo de actualización se almacena en el directorio inicial del usuario administrador.



== Paso 3: Aplicar el paquete de actualización

Después de cargar el archivo de actualización en la máquina virtual ONTAP Select Deploy, puede aplicar la actualización.

.Antes de empezar
* Verifique en qué directorio se ha colocado el archivo de actualización en la máquina virtual de la utilidad ONTAP Select Deploy.
* Verifique que ONTAP Select Deploy no se utilice para realizar ninguna otra tarea mientras se realiza la actualización.


.Pasos
. Sign in en la CLI de la utilidad ONTAP Select Deploy usando SSH con la cuenta de administrador.
. Realice la actualización con la ruta y el nombre de archivo del directorio adecuados:
+
`deploy upgrade -package-path FILEPATH`

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.Después de terminar
Antes de completar el procedimiento de actualización, se le solicitará que cree una copia de seguridad de la configuración de la máquina virtual ONTAP Select Deploy.  Además, debes borrar la memoria caché del navegador para poder ver las páginas de implementación de ONTAP Select recién creadas.
