---
sidebar: sidebar 
permalink: task_cli_connectivity.html 
keywords: administer, administering, cli, connectivity, network connectivity, network checker 
summary: Se puede probar la conectividad de red entre dos o más nodos ONTAP Select en la red de clúster interna. Normalmente, se ejecuta esta prueba antes de que se ponga en marcha un clúster de varios nodos para detectar problemas que podrían provocar errores en la operación. 
---
= Confirme la conectividad de red entre los nodos ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se puede probar la conectividad de red entre dos o más nodos ONTAP Select en la red de clúster interna. Normalmente, se ejecuta esta prueba antes de que se ponga en marcha un clúster de varios nodos para detectar problemas que podrían provocar errores en la operación.

.Antes de empezar
Todos los nodos ONTAP Select incluidos en la prueba deben estar configurados y encendidos.

.Acerca de esta tarea
Cada vez que inicie una prueba, se creará una nueva ejecución de proceso en segundo plano y se le asignará un identificador de ejecución único. Sólo una secuencia puede estar activa a la vez.

La prueba tiene dos modos que controlan su funcionamiento:

* Rápido este modo realiza una prueba básica sin interrupciones. Se realiza una prueba DE PING, así como una prueba del tamaño de MTU de red y del vSwitch.
* Este modo ampliado realiza una prueba más completa de todas las rutas de red redundantes. Si ejecuta esto en un clúster ONTAP Select activo, el rendimiento del clúster puede verse afectado.



NOTE: Se recomienda que siempre ejecute una prueba rápida antes de crear un clúster de varios nodos. Una vez finalizada la prueba rápida con éxito, puede realizar opcionalmente una prueba ampliada en función de sus requisitos de producción.

.Pasos
. Inicie sesión en la CLI de la utilidad de implementación mediante la cuenta de administrador.
. Muestre las ejecuciones actuales del comprobador de conectividad de red y compruebe que no hay ninguna ejecución activa:
+
`network connectivity-check show`

. Inicie el comprobador de conectividad de red y anote el identificador run en el resultado del comando:
+
`network connectivity-check start -host-names HOSTNAMES -vswitch-type VSWITCH_TYPE-mode MODE`

+
Ejemplo

+
[listing]
----
network connectivity-check start -host-names 10.234.81.14
10.234.81.15 -vswitch-type StandardVSwitch -mode quick
----
. Supervise el progreso del comprobador de conectividad de red en función del identificador de ejecución:
+
`network connectivity-check show -run-id RUN_ID`



.Después de terminar
El comprobador de conectividad de red normalmente borra todos los puertos temporales y direcciones IP añadidos al grupo de puertos ONTAP-interno. Sin embargo, si el comprobador de conectividad no quita los puertos temporales, debe realizar una operación de limpieza manual volviendo a ejecutar el comando CLI con la opción `-mode cleanup`. Si no se quitan los puertos temporales del grupo de puertos ONTAP-interno, es posible que la máquina virtual ONTAP Select no se cree correctamente.
