---
sidebar: sidebar 
permalink: task_cli_deploy_cluster.html 
keywords: administer, administering, cli, create cluster, deploy cluster 
summary: Puede usar la interfaz de línea de comandos proporcionada con la utilidad de administración ONTAP Select Deploy para crear un clúster de ONTAP Select de un solo nodo o varios nodos. 
---
= Ponga en marcha un clúster de ONTAP Select mediante la interfaz de línea de comandos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede usar la interfaz de línea de comandos proporcionada con la utilidad de administración ONTAP Select Deploy para crear un clúster de ONTAP Select de un solo nodo o varios nodos.



== Paso 1: Prepárese para la implementación

Antes de crear un clúster de ONTAP Select en un hipervisor, debe comprender la preparación necesaria.

.Pasos
. Prepárese para conectar el almacenamiento al nodo ONTAP Select
+
[role="tabbed-block"]
====
.RAID de hardware
--
Si utiliza un controlador RAID de hardware local, debe crear al menos un almacén de datos (ESX) o uno link:reference_chk_host_prep.html#create-storage-pool["grupo de almacenamiento (KVM)"] en cada nodo para los datos del sistema, así como para la raíz y los agregados de datos. Debe conectar el pool de almacenamiento como parte de la configuración del nodo ONTAP Select.

--
.RAID de software
--
Si utiliza RAID de software, debe crear al menos un almacén de datos (ESX) o uno link:reference_chk_host_prep.html#create-storage-pool["grupo de almacenamiento (KVM)"] para los datos del sistema y asegúrese de que las unidades SSD estén disponibles para la raíz y los agregados de datos. Debe conectar el pool de almacenamiento y los discos como parte de la configuración del nodo ONTAP Select.

--
====
. Versiones de ONTAP Select disponibles
+
La utilidad de administración de implementación contiene una sola versión de ONTAP Select. Si desea implementar clústeres utilizando una versión anterior de ONTAP Select, primero debe link:task_cli_deploy_image_add.html["añadir la imagen de ONTAP Select"] a su instancia de implementación.

. Licencia de ONTAP Select para una implementación de producción
+
Antes de implementar un clúster de ONTAP Select en un entorno de producción, debe adquirir una licencia de capacidad de almacenamiento y descargar el archivo de licencia asociado. Puede link:concept_lic_production.html["licenciar el almacenamiento en cada nodo"] utilizando el modelo _Niveles de capacidad_ o licenciar un grupo compartido utilizando el modelo _Grupos de capacidad_.





== Paso 2: Cargue y registre un archivo de licencia

Después de adquirir un archivo de licencia con capacidad de almacenamiento, debe cargar el archivo que contiene la licencia en la máquina virtual de implementación y registrarlo.


NOTE: Si está implementando un clúster solo para la evaluación, puede omitir este paso.

.Antes de empezar
Debe tener la contraseña de la cuenta de usuario administrador.

.Pasos
. En un shell de comandos de la estación de trabajo local, utilice la utilidad sftp para cargar el archivo de licencia en la máquina virtual Deploy.
+
Resultado de ejemplo

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put NLF-320000nnn.txt
exit
....
. Inicie sesión en la CLI de la utilidad de implementación con la cuenta de administrador mediante SSH.
. Registre la licencia:
+
[source, cli]
----
license add -file-name <file_name>
----
+
Introduzca la contraseña de la cuenta de administrador cuando se le solicite.

. Mostrar las licencias en el sistema para confirmar que la licencia se ha añadido correctamente:
+
[source, cli]
----
license show
----




== Paso 3: Agregar hosts de hipervisor

Debe registrar cada host de hipervisor en el que se ejecutará un nodo de ONTAP Select.

[role="tabbed-block"]
====
.KVM
--
Debe registrar un host del hipervisor en el que se ejecutará el nodo de ONTAP Select. Como parte de esto, la utilidad de administración de despliegue autentica en el host KVM.

.Acerca de esta tarea
Si se necesita más de un host de hipervisor, utilice este procedimiento para agregar cada host.

.Pasos
. Inicie sesión en la CLI de la utilidad de implementación mediante SSH con la cuenta de administrador.
. Registre el host:
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type KVM -username <KVM_username>
----
+
Resultado de ejemplo

+
[listing]
----
host register -name 10.234.81.14 -hypervisor-type KVM -username root
----
+
Proporcione la contraseña para la cuenta de host cuando se le solicite.

. Muestre el estado del host y confirme que se ha autenticado:
+
[source, cli]
----
host show -name <FQDN|IP> -detailed
----
+
Resultado de ejemplo

+
[listing]
----
host show -name 10.234.81.14 -detailed
----


--
.ESXi
--
Como parte de esto, la utilidad de administración de puesta en marcha autentica ya sea en el servidor vCenter que gestiona el host o directamente en el host independiente ESXi.

.Acerca de esta tarea
Antes de registrar un host gestionado por vCenter, es necesario añadir una cuenta de servidor de gestión para vCenter Server. Si el host no está gestionado por vCenter, puede proporcionar la credencial de host como parte del registro del host. Debe utilizar este procedimiento para añadir cada host.

.Pasos
. Inicie sesión en la CLI de la utilidad de implementación mediante SSH con la cuenta de administrador.
. Si el host está gestionado por un servidor de vCenter, añada la credencial de cuenta de vCenter:
+
[source, cli]
----
credential add -hostname <FQDN|IP> -type vcenter -username <vcenter_username>
----
+
Resultado de ejemplo

+
....
credential add -hostname vc.select.company-demo.com -type vcenter -username administrator@vsphere.local
....
. Registre el host:
+
** Registre un host independiente no gestionado por vCenter:
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type ESX -username <esx_username>
----
** Registre un host gestionado por vCenter:
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type ESX -mgmt-server <FQDN|IP>
----
+
Resultado de ejemplo

+
....
host register -name 10.234.81.14 -hypervisor-type ESX -mgmt-server vc.select.company-demo.com
....


. Muestra el estado del host y confirma que está autenticado.
+
[source, cli]
----
host show -name <FQDN|IP> -detailed
----
+
Resultado de ejemplo

+
....
host show -name 10.234.81.14 -detailed
....


--
====


== Paso 4: Crear y configurar un clúster de ONTAP Select

Debe crear y, a continuación, configurar el clúster ONTAP Select. Una vez que se configura el clúster, puede configurar los nodos individuales.

.Antes de empezar
Decide cuántos nodos contiene el clúster y ten la información de configuración asociada.

.Acerca de esta tarea
Cuando crea un clúster ONTAP Select, la utilidad Deploy genera automáticamente los nombres de nodo según el nombre del clúster y el número de nodos que proporcione. En la implementación también se generan los identificadores de nodo únicos.

.Pasos
. Inicie sesión en la CLI de la utilidad de implementación mediante SSH con la cuenta de administrador.
. Cree el clúster:
+
[source, cli]
----
cluster create -name <cluster_name> -node-count <count>
----
+
Resultado de ejemplo

+
....
cluster create -name test-cluster -node-count 1
....
. Configure el clúster:
+
[source, cli]
----
cluster modify -name <cluster_name> -mgmt-ip <IP_address> -netmask <netmask> -gateway <IP_address> -dns-servers <FQDN|IP>_LIST -dns-domains <domain_list>
----
+
Resultado de ejemplo

+
....
cluster modify -name test-cluster -mgmt-ip 10.234.81.20 -netmask 255.255.255.192
-gateway 10.234.81.1 -dns-servers 10.221.220.10 -dnsdomains select.company-demo.com
....
. Muestra la configuración y el estado del clúster:
+
[source, cli]
----
cluster show -name <cluster_name> -detailed
----




== Paso 5: Configurar un nodo ONTAP Select

Debe configurar cada uno de los nodos en el clúster de ONTAP Select.

.Antes de empezar
* Verifique que tenga la información de configuración del nodo.
* Verifique que el archivo de licencia de nivel de capacidad o de grupo de capacidad esté cargado e instalado en la utilidad de implementación.


.Acerca de esta tarea
Debe usar este procedimiento para configurar cada nodo. En este ejemplo, se aplica una licencia de nivel de capacidad al nodo.

.Pasos
. Inicie sesión en la CLI de la utilidad de implementación mediante SSH con la cuenta de administrador.
. Determine los nombres asignados a los nodos del clúster:
+
[source, cli]
----
node show -cluster-name <cluster_name>
----
. Seleccione el nodo y realice una configuración básica:
+
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -host-name <FQDN|IP> -license-serial-number <number> -instance-type TYPE -passthrough-disks false
----
+
Resultado de ejemplo

+
....
node modify -name test-cluster-01 -cluster-name test-cluster -host-name 10.234.81.14
-license-serial-number 320000nnnn -instance-type small -passthrough-disks false
....
+
La configuración RAID del nodo se indica con el parámetro _passThrough-disks_ . Si utiliza un controlador RAID de hardware local, este valor debe ser "false". Si utiliza RAID de software, este valor debe ser "true".

+
Se usa una licencia de nivel de capacidad para el nodo ONTAP Select.

. Mostrar la configuración de red disponible en el host:
+
[source, cli]
----
host network show -host-name <FQDN|IP> -detailed
----
+
Resultado de ejemplo

+
....
host network show -host-name 10.234.81.14 -detailed
....
. Realice la configuración de red del nodo:
+
[role="tabbed-block"]
====
.Host ESXi
--
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -mgmt-ip IP -management-networks <network_name> -data-networks <network_name> -internal-network <network_name>
----
--
.Host KVM
--
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -mgmt-ip IP -management-vlans <vlan_id> -data-vlans <vlan_id> -internal-vlans <vlad_id>
----
--
====
+
Al implementar un clúster de un solo nodo, no necesita una red interna y debe eliminar "-internal-network".

+
Resultado de ejemplo

+
....
node modify -name test-cluster-01 -cluster-name test-cluster -mgmt-ip 10.234.81.21
-management-networks sDOT_Network -data-networks sDOT_Network
....
. Mostrar la configuración del nodo:
+
[source, cli]
----
node show -name <node_name> -cluster-name <cluster_name> -detailed
----
+
Resultado de ejemplo

+
....
node show -name test-cluster-01 -cluster-name test-cluster -detailed
....




== Paso 6: Adjuntar almacenamiento a los nodos de ONTAP Select

Configure el almacenamiento utilizado por cada nodo en el clúster ONTAP Select . Cada nodo debe tener asignado siempre al menos un pool de almacenamiento. Cuando se usa software RAID, cada nodo también debe asignarse al menos una unidad de disco.

.Antes de empezar
Cree el grupo de almacenamiento mediante VMware vSphere. Si utiliza RAID de software, también necesita al menos una unidad de disco disponible.

.Acerca de esta tarea
Si utiliza una controladora RAID de hardware local, debe realizar los pasos del 1 al 4. Al utilizar el software RAID, debe realizar los pasos del 1 al 6.

.Pasos
. Inicie sesión en la CLI de la utilidad de implementación mediante SSH con las credenciales de cuenta de administrador.
. Visualice las agrupaciones de almacenamiento disponibles en el host:
+
[source, cli]
----
host storage pool show -host-name <FQDN|IP>
----
+
Resultado de ejemplo

+
[listing]
----
host storage pool show -host-name 10.234.81.14
----
+
También se pueden obtener los pools de almacenamiento disponibles mediante VMware vSphere.

. Conecte un pool de almacenamiento disponible al nodo ONTAP Select:
+
[source, cli]
----
node storage pool attach -name <pool_name> -cluster-name <cluster_name> -node-name <node_name> -capacity-limit <limit>
----
+
Si incluye el parámetro "-capacity-limit", especifique el valor como GB o TB.

+
Resultado de ejemplo

+
[listing]
----
node storage pool attach -name sDOT-02 -cluster-name test-cluster -
node-name test-cluster-01 -capacity-limit 500GB
----
. Muestre los pools de almacenamiento conectados al nodo:
+
[source, cli]
----
node storage pool show -cluster-name <cluster_name> -node-name <node_name>
----
+
Resultado de ejemplo

+
[listing]
----
node storage pool show -cluster-name test-cluster -node-name testcluster-01
----
. Si utiliza RAID de software, conecte la unidad o las unidades disponibles:
+
[source, cli]
----
node storage disk attach -node-name <node_name> -cluster-name <cluster_name> -disks <list_of_drives>
----
+
Resultado de ejemplo

+
[listing]
----
node storage disk attach -node-name NVME_SN-01 -cluster-name NVME_SN -disks 0000:66:00.0 0000:67:00.0 0000:68:00.0
----
. Si utiliza RAID de software, muestre los discos conectados al nodo:
+
[source, cli]
----
node storage disk show -node-name <node_name> -cluster-name <cluster_name>`
----
+
Resultado de ejemplo

+
[listing]
----
node storage disk show -node-name sdot-smicro-009a -cluster-name NVME
----




== Paso 7: Implementar un clúster ONTAP Select

Después de configurar el clúster y los nodos, puede implementar el clúster.

.Antes de empezar
Ejecute el comprobador de conectividad de red utilizando el link:task_adm_connectivity.html["interfaz de usuario web"] o el link:task_cli_connectivity.html["CLI"] para confirmar la conectividad entre los nodos del clúster en la red interna.

.Pasos
. Inicie sesión en la CLI de la utilidad de implementación mediante SSH con la cuenta de administrador.
. Implemente el clúster de ONTAP Select:
+
[source, cli]
----
cluster deploy -name <cluster_name>
----
+
Resultado de ejemplo

+
[listing]
----
cluster deploy -name test-cluster
----
+
Introduzca la contraseña que se utilizará para la cuenta de administrador de ONTAP cuando se le solicite.

. Muestre el estado del clúster para determinar cuándo se ha implementado correctamente:
+
[source, cli]
----
cluster show -name <cluster_name>
----


.Después de terminar
Debe realizar una copia de seguridad de los datos de configuración de implementación de ONTAP Select.
