---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: Agrega una imagen de ONTAP Select a tu instancia de la utilidad de administración Deploy. Después de la instalación, puedes usarla al desplegar un clúster ONTAP Select. 
---
= Agregue una imagen ONTAP Select para implementarla
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Agrega una imagen de ONTAP Select a tu instancia de la utilidad de administración Deploy. Después de que la imagen se haya instalado, puedes usarla al desplegar un clúster ONTAP Select.

.Antes de empezar
Antes de agregar cualquier imagen ONTAP Select nueva para implementar, primero debe quitar todas las imágenes innecesarias.


NOTE: Sólo debe agregar una imagen ONTAP Select con una versión anterior a la versión original incluida con la instancia de la utilidad de implementación. No se admite la adición de versiones posteriores de ONTAP Select a medida que están disponibles en NetApp.



== Paso 1: Descarga la imagen de instalación

Para iniciar el proceso de adición de una imagen de ONTAP Select a una instancia de la utilidad de implementación, debe descargar la imagen de instalación del sitio de soporte de NetApp. La imagen de instalación de ONTAP Select tiene el formato de archivo comprimido único.

.Pasos
. Accede a la página link:https://mysupport.netapp.com/site/downloads/["NetApp Support Site descargas"^].
. Desplázate hacia abajo y selecciona *ONTAP Select Image*.
. Selecciona la versión que quieres de la imagen de instalación.
. Revise el Contrato de licencia de usuario final (EULA) y seleccione *Aceptar y continuar*.
. Selecciona y descarga el paquete *ONTAP Select Image Install* adecuado. Responde a todas las preguntas según sea necesario.




== Paso 2: Cargar la imagen de instalación en Deploy

Después de adquirir la imagen de instalación de ONTAP Select, deberá cargar el archivo en la máquina virtual de implementación.

.Antes de empezar
Verifica que tienes el archivo de imagen de instalación disponible en tu estación de trabajo local. También debes tener la contraseña de la cuenta de usuario administrador de Deploy.

.Acerca de esta tarea
En esta tarea se describe un método para cargar el archivo en la máquina virtual de implementación. Es posible que haya otras opciones más adecuadas para su entorno.

.Paso
. En una terminal de comandos de su estación de trabajo local, cargue el archivo de imagen en la máquina virtual de implementación, como se muestra en los siguientes ejemplos:
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Resultado
El archivo de instalación del nodo se almacena en el directorio inicial del usuario administrador.



== Paso 3: Agregar la imagen de instalación

Agregue la imagen de instalación de ONTAP Select al directorio de imágenes de implementación para que esté disponible al implementar un nuevo clúster.

.Antes de empezar
Debe saber en qué directorio se ha colocado el archivo de imagen de instalación en la máquina virtual de la utilidad de implementación. Se supone que el archivo está en el directorio principal del administrador.

.Pasos
. Inicie sesión en la CLI de la utilidad de implementación mediante SSH con la cuenta de administrador (admin).
. Inicie el shell Bash:
+
[source, cli]
----
shell bash
----
. Coloque el archivo de imagen de instalación en el directorio de imágenes, como se muestra en el siguiente ejemplo:
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Paso 4: Mostrar las imágenes de instalación disponibles

Muestra las imágenes de ONTAP Select que están disponibles al implementar un nuevo clúster.

.Pasos
. Acceda a la página web de documentación en línea de la máquina virtual de la utilidad de implementación e inicie sesión mediante la cuenta de administrador (admin):
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Usar el nombre de dominio o la dirección IP de la máquina virtual de implementación.

. Navegue hasta la parte inferior de la página y seleccione *Implementar* y luego seleccione *OBTENER /imágenes*.
. Seleccione *¡Pruébelo!* para mostrar las imágenes disponibles de ONTAP Select .
. Confirme que la imagen deseada está disponible.

