---
sidebar: sidebar 
permalink: task_vpi_adm_clusters.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, clusters 
summary: Existen varias tareas relacionadas que puede realizar para administrar un clúster de ONTAP Select. 
---
= Clústeres ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Existen varias tareas relacionadas que puede realizar para administrar un clúster de ONTAP Select.



== Mueva un clúster de ONTAP Select a los estados sin conexión y en línea

Después de crear un clúster, puede cambiar su estado a sin conexión o en línea según sea necesario.

.Pasos
. Haga clic en *clústeres ONTAP Select* en el panel *Listas de inventario globales*.
. Haga clic con el botón derecho en el clúster deseado para mostrar las acciones disponibles.
. Haga clic en *desconectar* o *poner en línea* según corresponda y haga clic en *Sí* para confirmar la solicitud.




== Eliminar un clúster de ONTAP Select

Es posible eliminar un clúster de ONTAP Select cuando ya no se necesita.

.Antes de empezar
El clúster debe estar en el estado sin conexión.

.Pasos
. Haga clic en *clústeres ONTAP Select* en el panel *Listas de inventario globales*.
. Haga clic con el botón derecho en el clúster deseado para mostrar las acciones disponibles.
. Haga clic en *Eliminar clúster* y haga clic en *Sí* para confirmar la solicitud.
+
Si la opción de eliminación no está disponible, el clúster no tiene el estado sin conexión.


