---
sidebar: sidebar 
permalink: task_lic_acquire_cp.html 
keywords: license, licensing, acquire, capacity pools 
summary: Debe adquirir un archivo de licencia para cada pool de capacidad que utilizan los nodos ONTAP Select. El archivo de licencia define la capacidad de almacenamiento y la caducidad del pool. Se bloquea en el Administrador de licencias mediante una combinación del número de serie de licencia único que asigna NetApp y el ID de bloqueo de licencia asociado con la instancia de implementación. 
---
= Adquirir una licencia de pool de capacidad de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe adquirir un archivo de licencia para cada pool de capacidad que utilizan los nodos ONTAP Select. El archivo de licencia define la capacidad de almacenamiento y la caducidad del pool. Se bloquea en el Administrador de licencias mediante una combinación del número de serie de licencia único que asigna NetApp y el ID de bloqueo de licencia asociado con la instancia de implementación.

.Antes de empezar
Debe tener el número de serie de licencia de nueve dígitos asignado por NetApp al pool de capacidad. Antes de intentar adquirir un archivo de licencia, debe esperar al menos veinte cuatro horas después de la fecha de envío de su orden de compra.

.Acerca de esta tarea
Debe realizar esta tarea en cada pool de capacidad que utilizan los nodos ONTAP Select.

.Pasos
. Acceda al sitio de soporte de NetApp mediante un navegador web e inicie sesión.
. Haga clic en *sistemas* en la parte superior y, a continuación, haga clic en *licencias de software*.
. Escriba el número de serie de la licencia para el pool de capacidad y haga clic en *Go!*.
. En la página de detalles de la licencia, vaya a la columna *Detalles del producto*.
. Haga clic en *obtener archivo de licencia de NetApp* en la fila correspondiente.
. Escriba el ID de bloqueo de licencia para la instancia de ONTAP Select Deploy y haga clic en *Enviar*.
. Seleccione el método de entrega adecuado y haga clic en *Enviar*.
. Haga clic en *Aceptar* en la ventana de confirmación de entrega.


.Después de terminar
Para que un nodo de ONTAP Select pueda usar el pool de capacidad, debe cargar el archivo de licencia en la utilidad de administración de implementación.
