---
sidebar: sidebar 
permalink: task_vpi_access.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, access, accessing 
summary: Puede acceder al plugin de vCenter de implementar mediante el cliente web de vSphere. 
---
= Acceder al plugin de vCenter mediante vSphere
:allow-uri-read: 


[role="lead"]
Puede acceder al plugin de vCenter de implementar mediante el cliente web de vSphere.

.Antes de empezar
Se debe instalar el complemento de vCenter. Además, la cuenta de vCenter que utilice al iniciar sesión en vSphere debe tener el siguiente privilegio:

* NetApp
+
** Puesta en marcha de ONTAP Select
+
*** Administrador






.Pasos
. Si inició sesión en vSphere Web Client, cierre la sesión.
. Inicie sesión en vCenter mediante el cliente web de vSphere, seleccione HTML5 y acepte el certificado SSL.
+
Al cerrar la sesión y, a continuación, volver a actualizar la información de configuración de vCenter.

. Haga clic en *Listas de inventario globales*.


.Resultado
Las opciones *clústeres ONTAP Select* y *implementación ONTAP Select* están disponibles en el panel de la izquierda. Si no se muestran, debe cerrar sesión y volver a iniciar sesión.
