---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: A partir de ONTAP Select 9.15.1, puede aumentar o disminuir el tamaño de un clúster existente. 
---
= Expandir o contraer un clúster ONTAP Select en un host ESXi o KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aumentar o disminuir el tamaño del clúster de un clúster ONTAP Select existente para hosts de hipervisor ESXi y KVM.  Para ambos tipos de host, puede aumentar y disminuir el tamaño del clúster en incrementos de entre cuatro y doce nodos.

Las siguientes expansiones y contracciones de clúster no son compatibles con los hosts ESXi y KVM:

* Expansiones de grupos de uno o dos nodos a grupos de seis, ocho, diez o doce nodos.
* Contracción de grupos de seis, ocho, diez o doce nodos a grupos de uno o dos nodos.


[NOTE]
====
Para cambiar la cantidad de nodos de un clúster a un tamaño que no sea compatible con la expansión o contracción del clúster, debe realizar las siguientes tareas:

. Implemente un nuevo clúster de múltiples nodos mediante el uso de link:task_cli_deploy_cluster.html["CLI"] o el link:task_deploy_cluster.html["interfaz de usuario web"] proporcionado con la utilidad de administración ONTAP Select Deploy.
. Si corresponde, migre los datos al nuevo clúster mediante link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["Replicación de SnapMirror"^] .


====
Puede iniciar los procedimientos de expansión y contracción del clúster desde ONTAP Select Deploy mediante la CLI, la API o la interfaz web.



== Consideraciones sobre hardware y almacenamiento

La función de expansión y contracción del clúster es compatible con los siguientes hosts de hipervisor KVM y ESXi.

[role="tabbed-block"]
====
.ESXi
--
A partir de ONTAP Select 9.15.1, la expansión y contracción de clústeres se admite en los hosts de hipervisor ESXi.

La expansión y contracción del clúster es compatible con las siguientes versiones de hipervisor ESXi:

* ESXi 9.0
* ESXi 8,0 U3
* ESXi 8,0 U2
* ESXi 8,0 U1
* ESXi 8,0GA


--
.KVM
--
A partir de ONTAP Select 9.17.1, la expansión y contracción de clústeres se admite en los hosts de hipervisor KVM.

La expansión y contracción del clúster es compatible con las siguientes versiones de hipervisor KVM:

* Red Hat Enterprise Linux (RHEL) 64-bit 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 y 8.6
* Rocky Linux 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 y 8.6


--
====


== Expanda el clúster

Utilice la función de expansión de clúster para aumentar el tamaño de un clúster ONTAP Select existente.

Puede aumentar el tamaño de un clúster existente en un host ESXi o KVM en los siguientes incrementos:

* De cuatro nodos a seis, ocho, diez o doce nodos
* De seis nodos a ocho, diez o doce nodos
* De ocho nodos a diez o doce nodos
* De diez a doce nodos


.Acerca de esta tarea
Para preparar la expansión del clúster, se añaden nuevos hosts ESXi y KVM al inventario y se asignan los detalles de los nuevos nodos. Antes de iniciar el proceso de expansión del clúster, se realiza una comprobación previa de la red para verificar la red interna seleccionada.

.Antes de empezar
* Al implementar un clúster multinodo, debe familiarizarse con el verificador de conectividad de red. Puede ejecutarlo mediante el link:task_adm_connectivity.html["interfaz de usuario web"] o el link:task_cli_connectivity.html["CLI"] .
* Compruebe que tiene los detalles de la licencia para los nodos nuevos.


.Pasos
. Inicie sesión en la interfaz de usuario web de la utilidad de implementación mediante la cuenta de administrador.
. Seleccione la pestaña *Cluster* en la parte superior de la página y seleccione el clúster deseado de la lista.
. En la página de detalles del clúster, seleccione el icono de engranaje a la derecha de la página y seleccione *Expandir clúster*.
. Navega a la sección *HA Pair 4*.
. Elija los siguientes detalles de configuración de par de alta disponibilidad (HA) para el cuarto par de HA:
+
** Tipo de instancia
** Nombres de nodo
** Hosts de hipervisores asociados
** Direcciones IP del nodo
** Licencias
** Configuración de redes
** Configuración del almacenamiento (tipo de RAID y pools de almacenamiento)


. Seleccione *Guardar par HA* para guardar los detalles de la configuración.
. Proporcione las credenciales de ONTAP y seleccione *Expandir clúster*.
. Seleccione *Siguiente* y ejecute la comprobación previa de la red seleccionando *Ejecutar*.
+
La comprobación previa de red valida que la red interna seleccionada para el tráfico del clúster de ONTAP funcione correctamente.

. Seleccione *Expand Cluster* para comenzar el proceso de expansión del cluster y luego seleccione *OK* en el cuadro de diálogo.
+
El clúster puede tardar hasta 45 minutos en ampliarse.

. Supervise el proceso de expansión del cluster en varios pasos para confirmar que el cluster se ha expandido correctamente.
. Consulte la pestaña *Eventos* para obtener actualizaciones periódicas sobre el progreso de la operación. La página se actualiza automáticamente a intervalos regulares.


.Después de terminar
Tras expandir el clúster, deberíalink:task_cli_clusters.html["Realizar una copia de seguridad de los datos de configuración de ONTAP Select Deploy"] .



== Contraiga el clúster

Utilice la función de contracción de clúster para disminuir el tamaño de un clúster ONTAP Select existente.

Puede reducir el tamaño de un clúster existente en un host ESXi o KVM en los siguientes incrementos:

* De doce nodos a diez, ocho, seis o cuatro nodos
* De diez nodos a ocho, seis o cuatro nodos
* De ocho a seis o cuatro nodos
* De seis a cuatro nodos


.Acerca de esta tarea
El par de nodos de alta disponibilidad deseado en el clúster se ha seleccionado para preparar la contracción del clúster durante el procedimiento.

.Pasos
. Inicie sesión en la interfaz de usuario web de la utilidad de implementación mediante la cuenta de administrador.
. Seleccione la pestaña *Cluster* en la parte superior de la página y seleccione el clúster deseado de la lista.
. En la página de detalles del clúster, seleccione el icono de engranaje a la derecha de la página y, a continuación, seleccione *Clúster de contrato*.
. Seleccione los detalles de configuración del par de alta disponibilidad para cualquier par de alta disponibilidad que desee eliminar y proporcione las credenciales de ONTAP, luego seleccione * Clúster de contrato *.
+
El clúster puede tardar hasta 30 minutos en contratarse.

. Supervise el proceso de contracción del cluster de varios pasos para confirmar que el cluster se ha contraído correctamente.
. Consulte la pestaña *Eventos* para obtener actualizaciones periódicas sobre el progreso de la operación. La página se actualiza automáticamente a intervalos regulares.

