---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: A partir de ONTAP Select 9.15.1, puede aumentar el tamaño de un clúster existente de seis a ocho nodos y reducir el tamaño del clúster de ocho a seis nodos. 
---
= Expanda o contraiga el clúster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir de ONTAP Select 9.15.1, puede aumentar el tamaño de un clúster existente de seis a ocho nodos y reducir el tamaño del clúster de ocho a seis nodos. No se admite ningún otro escenario de expansión o contracción de cluster.

El procedimiento se inicia desde la puesta en marcha de ONTAP Select a través de la CLI, la API o la interfaz web.



== Consideraciones sobre hardware y almacenamiento

Las funcionalidades de expansión y contracción del cluster están restringidas de las siguientes maneras:

* La compatibilidad se limita a los clústeres creados en hosts de hipervisores ESX. Las siguientes versiones de ESX son compatibles con ONTAP Select 9.15.1:
+
** ESXi 8.0U2
** ESXi 8.0U1
** ESXi 8,0GA
** ESXi 7.0U3
** ESXi 7,0




Actualmente no se admiten las siguientes expansiones y contracciones de cluster:

* Expansión de uno, dos o cuatro clústeres de nodos a clústeres de seis u ocho nodos.
* Contracción de seis u ocho clústeres de nodos a uno, dos o cuatro clústeres de nodos.




== Expanda el clúster

Es posible aumentar el tamaño de un clúster existente de seis nodos a uno de ocho nodos con la función de ampliación de clúster.

.Acerca de esta tarea
Como preparación para el procedimiento de ampliación del clúster, se añaden nuevos hosts ESX al inventario y se asignan los detalles de los nuevos nodos. Antes de iniciar el proceso de expansión del clúster, una comprobación previa de red verifica la red interna seleccionada.

.Antes de empezar
* Cuando ponga en marcha un clúster multinodo, debería estar familiarizado con el link:https://docs.netapp.com/us-en/ontap-select/task_adm_connectivity.html["comprobador de conectividad de red"].
* Compruebe que tiene los detalles de la licencia para los nodos nuevos.


.Pasos
. Inicie sesión en la interfaz de usuario web de la utilidad de implementación mediante la cuenta de administrador.
. Seleccione la pestaña *Cluster* en la parte superior de la página y seleccione el clúster deseado de la lista.
. En la página de detalles del clúster, seleccione el icono de engranaje a la derecha de la página y seleccione *Expandir clúster*.
. Navega a la sección *HA Pair 4*.
. Elija los detalles de la configuración del par de alta disponibilidad para el cuarto par de alta disponibilidad, entre los que se incluyen:
+
** Tipo de instancia
** Nombres de nodo
** Hosts de hipervisores asociados
** Direcciones IP del nodo
** Licencias
** Configuración de redes
** Configuración del almacenamiento (tipo de RAID y pools de almacenamiento)


. Seleccione *Guardar par HA* para guardar los detalles de la configuración.
. Proporcione las credenciales de ONTAP, luego seleccione *Expandir clúster*.
. Seleccione *Siguiente* y ejecute la comprobación previa de la red seleccionando *Ejecutar*.
+
La comprobación previa de red valida que la red interna seleccionada para el tráfico del clúster de ONTAP funcione correctamente.

. Seleccione *Expand Cluster* para comenzar el proceso de expansión del cluster y luego seleccione *OK* en el cuadro de diálogo.
+
El clúster puede tardar hasta 45 minutos en ampliarse.

. Supervise el proceso de expansión del cluster en varios pasos para confirmar que el cluster se ha expandido correctamente.
. Consulte la pestaña *Eventos* para obtener actualizaciones periódicas sobre el progreso de la operación. La página se actualiza automáticamente a intervalos regulares.


.Después de terminar
Después de expandir el clúster, debe crear un backup de los datos de configuración de ONTAP Select Deploy.



== Contraiga el clúster

Puede reducir el tamaño de un clúster existente de ocho nodos a uno de seis nodos con la función de contracción de clústeres.

.Acerca de esta tarea
El par de nodos de alta disponibilidad deseado en el clúster se ha seleccionado para preparar la contracción del clúster durante el procedimiento.

.Pasos
. Inicie sesión en la interfaz de usuario web de la utilidad de implementación mediante la cuenta de administrador.
. Seleccione la pestaña *Cluster* en la parte superior de la página y seleccione el clúster deseado de la lista.
. En la página de detalles del clúster, seleccione el icono de engranaje a la derecha de la página y, a continuación, seleccione *Clúster de contrato*.
. Seleccione los detalles de configuración del par de alta disponibilidad para cualquier par de alta disponibilidad que desee eliminar y proporcione las credenciales de ONTAP, luego seleccione * Clúster de contrato *.
+
El clúster puede tardar hasta 30 minutos en contratarse.

. Supervise el proceso de contracción del cluster de varios pasos para confirmar que el cluster se ha contraído correctamente.
. Consulte la pestaña *Eventos* para obtener actualizaciones periódicas sobre el progreso de la operación. La página se actualiza automáticamente a intervalos regulares.

