---
sidebar: sidebar 
permalink: task_vpi_manually_remove.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, vcenter, remove, removing, manually removing 
summary: Es posible quitar manualmente el plugin de puesta en marcha de vCenter Server. 
---
= Quitar manualmente el plugin de implementación de vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible quitar manualmente el plugin de puesta en marcha de vCenter Server.



== Antes de empezar

Para comenzar, siempre es necesario eliminar el plugin mediante el explorador de objetos gestionados de VMware (MOB) y, a continuación, quitarlo de los directorios de vSphere dentro del servidor vCenter.

Existen varias instancias en las que debe quitar manualmente el plugin:

* El plugin se quitó mediante la interfaz de usuario nativa de la utilidad de implementación, pero el servidor de vCenter no se pudo reiniciar.
* La utilidad de despliegue se ha retirado del servicio sin quitar el complemento.




== Utilice VMware MOB para quitar el plugin

El MOB es una aplicación VMware que permite ver y gestionar los objetos en un servidor VMware vCenter. Es posible utilizar el MOB para quitar el complemento de implementación de vCenter.

.Pasos
. Acceda al MOB en vCenter Server mediante un explorador e inicio de sesión:
+
`\https://<FQDN_or_IP-address>/mob`

. Haga clic en *content* y, a continuación, en *ExtensionManager*.
. Confirme que la extensión que se va a eliminar está presente en función del nombre completo:
+
`com.netapp.selectdeploy`

. Haga clic en *UnregisterExtension*.
. Escriba el nombre de la extensión y haga clic en *InvokeMethod*.


.Resultado
El complemento se elimina de la lista de extensiones.



== Quite el plugin de la carpeta de la interfaz de usuario de vSphere

Debe examinar el directorio de la interfaz de usuario de vSphere en el servidor de vCenter y quitar el plugin de implementación, si existen.

.Antes de empezar
Debe tener la contraseña de la cuenta de raíz en el servidor vCenter. Debe quitar el plugin mediante el MOB de vSphere.

.Pasos
. Utilice SSH para acceder al vCenter Server e iniciar sesión:
+
`ssh root@<FQDN_or_IP-address>`

. Escriba *shell* y pulse *Intro* para iniciar el shell Bash.
. Desplácese hasta la `vsphere-client-serenity` directorio del servicio vSphere-UI:
+
`cd /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity`

. Determine si hay directorios del formulario `com.netapp.selectdeploy` que se debe eliminar:
+
`ls -al`

. Detenga el cliente web HTML5 vSphere-UI:
+
`service-control --stop vsphere-ui`

. Quite el directorio que contiene las extensiones de la interfaz de usuario:
+
`rm -rf com.netapp.selectdeploy-1.0.0`

. Reinicie el cliente web HTML5 vSphere-UI:
+
`service-control --start vsphere-ui`



.Después de terminar
El complemento de implementación puede tardar varios minutos en reiniciarse y estar disponible.



== Quite el plugin de la carpeta del cliente de vSphere

Si se encuentra, debe examinar el directorio de vSphere Client en el servidor de vCenter y quitar el plugin de implementación. Aunque el complemento Deploy no utiliza Flash, se recomienda examinar este directorio como parte del procedimiento de eliminación del plugin.

.Antes de empezar
Debe tener la contraseña de la cuenta de raíz en el servidor vCenter. Es necesario quitar el plugin mediante el MOB de vSphere y quitar el plugin del directorio de la interfaz de usuario de vSphere.

.Pasos
. Utilice SSH para acceder al vCenter Server e iniciar sesión:
+
`ssh root@<FQDN_or_IP-address>`

. Escriba *shell* y pulse *Intro* para iniciar el shell Bash.
. Desplácese hasta la `vsphere-client-serenity` directorio del servicio vSphere-Client:
+
`cd /etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity`

. Determine si hay directorios del formulario `com.netapp.selectdeploy` que se debe eliminar:
+
`ls -al`

. Detenga el cliente web HTML5 vSphere-UI:
+
`service-control --stop vsphere-client`

. Quite el directorio que contiene las extensiones del cliente:
+
`rm -rf com.netapp.selectdeploy-1.0.0`

. Reinicie el cliente web HTML5 vSphere-UI:
+
`service-control --start vsphere-client`



.Después de terminar
El complemento de implementación puede tardar varios minutos en reiniciarse y estar disponible.
