---
sidebar: sidebar 
permalink: task_vpi_adm_network.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, network, networking 
summary: Hay varios aspectos de la red que puede explorar y mostrar. 
---
= Confirmación de la conectividad de red
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay varios aspectos de la red que puede explorar y mostrar.



== Confirmación de la conectividad de red

Se puede probar la conectividad de red entre dos o más nodos ONTAP Select en la red de clúster interna. Normalmente, se debe ejecutar esta prueba antes de que se ponga en marcha un clúster de varios nodos para detectar problemas que podrían provocar un error en la operación. También se puede ejecutar la prueba de conectividad después de que un clúster se ponga en marcha y esté en línea.

.Acerca de esta tarea
Cada vez que inicie la prueba, se crea un nuevo proceso en segundo plano y se le asigna un identificador de ejecución único. Sólo una secuencia puede estar activa a la vez.

La prueba siempre se ejecuta en modo rápido, lo que realiza una prueba no disruptiva básica. Se realiza una prueba DE PING, así como una prueba del tamaño de MTU de red y del vSwitch.

.Pasos
. Haga clic en *implementación de ONTAP Select* en el panel *Listas de inventario globales*.
. Haga clic en la ficha *Administración*.
. Expanda la opción *Red* y haga clic en *Comprobador de conectividad*.
. Haga clic en *Ejecutar nuevo* para iniciar la prueba.
. Opcionalmente, haga clic en *filtrado* y cree un filtro para limitar los detalles de la prueba que se muestran.




== Ver el estado del servicio del mediador

Cada clúster de dos nodos de ONTAP Select es supervisado por el servicio mediador, que ayuda a gestionar la funcionalidad de alta disponibilidad compartida por los nodos. Puede ver el estado del servicio de mediador de cada uno de los clústeres de dos nodos definidos en la utilidad de administración de implementación.

.Acerca de esta tarea
Puede ver la configuración de cada mediador, lo que incluye:

* Estado actual
* Dos nodos ONTAP Select
* Destino iSCSI donde se almacena la información de control de alta disponibilidad


.Pasos
. Haga clic en *implementación de ONTAP Select* en el panel *Listas de inventario globales*.
. Haga clic en la ficha *Administración*.
. Expanda la opción *Mediator* y haga clic en *Estado*.
. Opcionalmente, haga clic en *filtrado* y cree un filtro para personalizar la vista de los clústeres de dos nodos supervisados por el servicio mediador.

