---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: Si la utilidad ONTAP Select Deploy falla o no está disponible por algún motivo, se pierde la capacidad de administrar nodos y clústeres de ONTAP Select. Además, los clústeres de dos nodos pierden funcionalidad de alta disponibilidad porque el servicio mediador incluido en la puesta en marcha no está disponible. Si se produce un error irrecuperable, debe recuperar la instancia de la utilidad de instalación para restaurar la funcionalidad administrativa y de alta disponibilidad. 
---
= Recupere la utilidad ONTAP Select Deploy para un clúster de dos nodos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si la utilidad ONTAP Select Deploy falla o no está disponible por algún motivo, se pierde la capacidad de administrar nodos y clústeres de ONTAP Select. Además, los clústeres de dos nodos pierden funcionalidad de alta disponibilidad porque el servicio mediador incluido en la puesta en marcha no está disponible. Si se produce un error irrecuperable, debe recuperar la instancia de la utilidad de instalación para restaurar la funcionalidad administrativa y de alta disponibilidad.



== Antes de empezar

Debe prepararse antes de intentar recuperar una instancia de la utilidad Deploy para garantizar el éxito.

.Habilidades e información necesarias
Usted debe estar familiarizado con varios procedimientos administrativos y tener la información necesaria.

.Instalación de la máquina virtual de despliegue
Debe poder instalar una nueva instancia de la utilidad ONTAP Select Deploy en su entorno de hipervisor.

.Interfaz de línea de comandos de ONTAP
Debe poder iniciar sesión en la CLI de ONTAP del clúster de ONTAP Select y utilizar la interfaz de shell.

.Disponibilidad de backup de configuración de la utilidad Deploy
Debe determinar si tiene un backup de los datos de configuración desde la instancia de la utilidad de implementación errónea que contiene el clúster de dos nodos de ONTAP Select. Es posible que tenga un backup que no contenga el clúster.

.Restaurar una copia de seguridad de la configuración de despliegue
Debería poder restaurar un backup de los datos de configuración de puesta en marcha, según el procedimiento de recuperación utilizado.

.Dirección IP de la máquina virtual de implementación original
Debe conocer la dirección IP de la máquina virtual original de la utilidad de implementación que falló.

.Licencias por capacidad de almacenamiento
Debe determinar si se utilizan pools de capacidad o licencias por niveles de capacidad. Si utiliza la licencia de pools de capacidad, debe volver a instalar cada licencia del pool de capacidad después de recuperar o restaurar la instancia de implementación.

.Decisión del procedimiento de recuperación que se debe utilizar
Debe decidir qué procedimiento se debe utilizar al recuperar una instancia de la utilidad ONTAP Select Deploy. Su decisión se basa en si tiene o no un backup de los datos de configuración de la utilidad original failed Deploy que contiene el clúster de dos nodos de ONTAP Select.

[cols="35,65"]
|===
| ¿Tiene un backup de puesta en marcha que contenga el clúster de dos nodos? | Procedimiento de recuperación que se debe utilizar 


| Sí | Restaure una instancia de utilidad de despliegue mediante una copia de seguridad de configuración 


| No | Vuelva a configurar y recuperar una instancia de utilidad de despliegue 
|===


== Restaure una instancia de utilidad de despliegue mediante una copia de seguridad de configuración

Si tiene una copia de seguridad de la instancia de la utilidad de implementación con errores que contiene el clúster de dos nodos, puede restaurar los datos de configuración en la nueva instancia de la máquina virtual de implementación. A continuación, debe completar la recuperación realizando una configuración adicional de los dos nodos del clúster ONTAP Select.

.Antes de empezar
Debe tener un backup de los datos de configuración de la máquina virtual de implementación con error original que contiene el clúster de dos nodos. Debe poder iniciar sesión en la CLI de ONTAP del clúster de dos nodos y conocer los nombres ONTAP de los dos nodos.

.Acerca de esta tarea
Debido a que el backup de configuración que restaura contiene el clúster de dos nodos, los destinos iSCSI y los buzones del mediador se vuelven a crear en la nueva máquina virtual de la utilidad de implementación.

.Pasos
. Prepare una nueva instancia de la utilidad ONTAP Select Deploy:
+
.. Instale una nueva máquina virtual de la utilidad de implementación.
.. Restaure la configuración de despliegue desde una copia de seguridad anterior a la nueva máquina virtual.
+
Consulte las tareas relacionadas para obtener información más detallada sobre los procedimientos de instalación y restauración.



. Inicie sesión en la interfaz de línea de comandos de ONTAP del clúster de dos nodos ONTAP Select.
. Entre en el modo de privilegio avanzado:
+
`set adv`

. Si la dirección IP de la nueva máquina virtual de puesta en marcha es diferente de la máquina virtual de puesta en marcha original, debe eliminar los antiguos destinos iSCSI del mediador y agregar nuevos destinos:
+
....
storage iscsi-initiator remove-target -node * -target-type mailbox

storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>

storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
....
+
La `<ip_address>` Parameter es la dirección IP de la nueva máquina virtual de implementación.

+
Estos comandos permiten que los nodos de ONTAP Select descubran los discos de buzón en la nueva máquina virtual de la utilidad de implementación.

. Determine los nombres de los discos del mediador:
+
`disk show -container-type mediator`

. Asigne los discos del buzón a los dos nodos:
+
....
disk assign -disk <mediator-disk1-name> -owner <node1-name>
disk assign -disk <mediator-disk2-name> -owner <node2-name>
....
. Compruebe que la recuperación tras fallos del almacenamiento está activada:
+
`storage failover show`



.Después de terminar
Si utiliza la licencia de pools de capacidad, debe volver a instalar cada licencia de pool de capacidad. Consulte _Volver a instalar una licencia de pool de capacidad_ para obtener más detalles.



== Vuelva a configurar y recuperar una instancia de utilidad de despliegue

Si no tiene un backup de la instancia de la utilidad de implementación fallida que contiene el clúster de dos nodos, debe configurar el destino y buzón del mediador iSCSI en la nueva máquina virtual de implementación. A continuación, debe completar la recuperación realizando una configuración adicional de los dos nodos del clúster ONTAP Select.

.Antes de empezar
Debe tener el nombre del objetivo del mediador para la nueva instancia de la utilidad de despliegue. Debe poder iniciar sesión en la CLI de ONTAP del clúster de dos nodos y conocer los nombres ONTAP de los dos nodos.

.Acerca de esta tarea
Opcionalmente, se puede restaurar un backup de configuración en la nueva máquina virtual de implementación aunque no contenga el clúster de dos nodos. Debido a que el clúster de dos nodos no se vuelve a crear con la restauración, se debe añadir manualmente el destino iSCSI y el buzón mediador a la nueva instancia de la utilidad de implementación a través de la página web de documentación en línea de ONTAP Select en la implementación. Debe poder iniciar sesión en el clúster de dos nodos y conocer los nombres de ONTAP de los dos nodos.


NOTE: El objetivo del procedimiento de recuperación es restaurar el clúster de dos nodos a un estado en buen estado, donde se pueden realizar operaciones normales de toma de control de ha y devolución.

.Pasos
. Prepare una nueva instancia de la utilidad ONTAP Select Deploy:
+
.. Instale una nueva máquina virtual de la utilidad de implementación.
.. Si lo desea, puede restaurar la configuración de implementación desde un backup anterior a la nueva máquina virtual.
+
Si restaura una copia de seguridad anterior, la nueva instancia de implementación no contendrá el clúster de dos nodos. Consulte la sección de información relacionada para obtener información más detallada sobre los procedimientos de instalación y restauración.



. Inicie sesión en la interfaz de línea de comandos de ONTAP del clúster de dos nodos ONTAP Select.
. Entrar en el modo privilegiado avanzado:
+
`set adv`

. Obtenga el nombre del destino iSCSI del mediador:
+
`storage iscsi-initiator show -target-type mailbox`

. Acceda a la página web de documentación en línea de la nueva máquina virtual de la utilidad de implementación e inicie sesión mediante la cuenta de administrador:
+
`\http://<ip_address>/api/ui`

+
Se debe usar la dirección IP de la máquina virtual de implementación.

. Haga clic en *Mediator* y luego en *GET /mediadores*.
. Haga clic en *probar!* para mostrar una lista de mediadores mantenidos por despliegue.
+
Anote el ID de la instancia de mediador deseada.

. Haga clic en *Mediator* y luego en *POST*.
. Proporcione el valor para mediador_id
. Haga clic en *Modelo* junto a. `iscsi_target` y complete el valor de nombre.
+
Use el nombre de destino del parámetro IQN_name.

. Haga clic en *probar!* para crear el destino iSCSI del mediador.
+
Si la solicitud es correcta, recibirá el código de estado HTTP 200.

. Si la dirección IP de la nueva máquina virtual de implementación es diferente de la máquina virtual de implementación original, debe utilizar la interfaz de línea de comandos de ONTAP para eliminar los antiguos destinos iSCSI del mediador y agregar nuevos destinos:
+
....
storage iscsi-initiator remove-target -node * -target-type mailbox

storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>

storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
....
+
La `<ip_address>` Parameter es la dirección IP de la nueva máquina virtual de implementación.



Estos comandos permiten que los nodos de ONTAP Select descubran los discos de buzón en la nueva máquina virtual de la utilidad de implementación.

. Determine los nombres de los discos del mediador:
+
`disk show -container-type mediator`

. Asigne los discos del buzón a los dos nodos:
+
....
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
....
. Compruebe que la recuperación tras fallos del almacenamiento está activada:
+
`storage failover show`



.Después de terminar
Si utiliza la licencia de pools de capacidad, debe volver a instalar cada licencia de pool de capacidad. Consulte Volver a instalar una licencia de pool de capacidad para obtener detalles adicionales.

.Información relacionada
* link:task_install_deploy.html["Instale ONTAP Select Deploy"]
* link:task_cli_migrate_deploy.html#restoring-the-deploy-configuration-data-to-the-new-virtual-machine["Restaure los datos de configuración de implementación en la nueva máquina virtual"]
* link:task_adm_licenses.html#reinstalling-a-capacity-pool-license["Vuelva a instalar una licencia de grupo de capacidad"]

