---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: Puede actualizar una máquina virtual de la utilidad de implementación existente en su sitio mediante la interfaz de línea de comandos. 
---
= Actualizar una instancia de despliegue de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Actualiza una máquina virtual existente de la utilidad ONTAP Select Deploy in situ usando la CLI de la utilidad ONTAP Select Deploy.

.Antes de empezar
Verifica que ONTAP Select Deploy no se use para realizar ninguna otra tarea durante la actualización. Consulta la link:reference_release_notes.html["notas de la versión"] para información y restricciones sobre la actualización de la utilidad ONTAP Select Deploy.

[NOTE]
====
Si tiene instalada una instancia anterior de la utilidad de administración de implementación de ONTAP Select, debe actualizar a la versión actual. El nodo de ONTAP Select y los componentes de puesta en marcha de ONTAP Select se actualizan de forma independiente. Consulte link:concept_adm_upgrading_nodes.html["Actualice los nodos ONTAP Select"^] para obtener más detalles.

Puede actualizar directamente a ONTAP Select Deploy 9.18.1 desde ONTAP Select Deploy 9.17.1 o 9.16.1. Para actualizar desde ONTAP Select Deploy 9.15.1 o una versión anterior, revise las notas de la versión de su versión de ONTAP Select .

====


== Paso 1: descarga el paquete de actualización

Para comenzar el proceso de actualización, descarga el archivo de actualización de ONTAP Select Deploy desde el sitio de soporte de NetApp. El paquete de actualización está formateado como un solo archivo comprimido.

.Pasos
. Accede a la página link:https://mysupport.netapp.com/site/downloads/["NetApp Support Site descargas"^].
. Desplázate hacia abajo y selecciona *ONTAP Select Deploy*.
. Selecciona la versión de ONTAP Select que quieras.
. Revise el Contrato de licencia de usuario final (EULA) y seleccione *Aceptar y continuar*.
. Selecciona y descarga el paquete *ONTAP Select Deploy Upgrade* adecuado. Responde a todas las preguntas que sean necesarias.




== Paso 2: Cargue el paquete en la máquina virtual ONTAP Select Deploy

Después de descargar el paquete, debe cargar el archivo en la máquina virtual ONTAP Select Deploy.

.Acerca de esta tarea
Esta tarea describe un método para cargar el archivo en la máquina virtual ONTAP Select Deploy.  Podrían existir otras opciones más adecuadas para su entorno.

.Antes de empezar
* Verifique que el archivo de actualización esté disponible en su estación de trabajo local.
* Verifique que tenga la contraseña de la cuenta de usuario administrador.


.Pasos
. En una terminal de comandos de su estación de trabajo local, utilice `scp` (Protocolo de copia segura) utilidad para cargar el archivo de imagen a la máquina virtual ONTAP Select Deploy, como se muestra en el siguiente ejemplo:
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.Resultado
El archivo de actualización se almacena en el directorio inicial del usuario administrador.



== Paso 3: Aplicar el paquete de actualización

Después de cargar el archivo de actualización en la máquina virtual ONTAP Select Deploy, puede aplicar la actualización.

.Antes de empezar
* Verifique en qué directorio se ha colocado el archivo de actualización en la máquina virtual de la utilidad ONTAP Select Deploy.
* Verifique que ONTAP Select Deploy no se utilice para realizar ninguna otra tarea mientras se realiza la actualización.


.Pasos
. Sign in en la CLI de la utilidad ONTAP Select Deploy usando SSH con la cuenta de administrador.
. Realice la actualización con la ruta y el nombre de archivo del directorio adecuados:
+
[source, cli]
----
deploy upgrade -package-path <file_path>
----
+
Ejemplo de comando:

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.Después de terminar
Antes de completar el procedimiento de actualización, se le solicitará que cree una copia de seguridad de la configuración de la máquina virtual ONTAP Select Deploy.  Además, debes borrar la memoria caché del navegador para poder ver las páginas de implementación de ONTAP Select recién creadas.
