---
sidebar: sidebar 
permalink: task_vpi_deploy_cluster.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, deploy cluster, deploying cluster, create cluster, creating cluster 
summary: Es posible usar el plugin de vCenter mediante la interfaz de usuario web de vSphere para implementar clústeres de ONTAP Select. 
---
= Ponga en marcha un clúster de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible usar el plugin de vCenter mediante la interfaz de usuario web de vSphere para implementar clústeres de ONTAP Select.



== Antes de empezar

Debe prepararse para usar el plugin de vCenter de implementación antes de implementar un clúster de ONTAP Select.



=== Preparación común para clústeres de todos los tamaños

Hay varios pasos que debe realizar independientemente del tamaño del clúster:

* Lea la sección _Getting Started_ para familiarizarse con el complemento Deploy vCenter.
* Asegúrese de que la utilidad de administración de implementación de ONTAP Select esté instalada y en ejecución.
* Instale el complemento implemente vCenter.
* Prepare el host del hipervisor o los hosts en los que se ejecutará el clúster de ONTAP Select.
* Adquiera los archivos de licencia de almacenamiento necesarios para el nodo o los nodos del clúster.
* Adquiera las credenciales de las siguientes cuentas:
+
** Implemente una cuenta de administrador
** Cuenta de vCenter con acceso al plugin


* Si es necesario, instale el certificado de implementación SSL en el Administrador de certificados de Windows como una “entidad emisora de certificados raíz de confianza”.
* Compruebe que la utilidad de implementación tenga acceso de red al puerto 443 en vCenter Server.




=== Preparación adicional para un clúster multinodo

Además de la preparación común, debe estar familiarizado con el comprobador de red implementado antes de implementar un clúster multinodo.



== Añada un host de hipervisor

Puede añadir hipervisores hosts a la utilidad de implementación en la que se ejecutarán los nodos de ONTAP Select antes de implementar un clúster. Si es necesario, puede añadir los hosts como parte del cuadro de diálogo de creación del clúster.

.Antes de empezar
Debe revisar cómo prepararse para implementar un clúster de ONTAP Select.

.Acerca de esta tarea
Puede añadir uno o varios hosts según el tamaño del clúster.

.Pasos
. Inicie sesión en vCenter Server a través del HTML5 de vSphere mediante un explorador.
. En la barra de herramientas, haga clic en *Menú* y, a continuación, en *Listas de inventario globales*.
. En el panel de la izquierda, haga clic en *implementación de ONTAP Select* y, a continuación, haga clic en la ficha *hosts*.
. Haga clic en *Agregar* a la derecha.
. Proporcione el nombre de host o la dirección IP del host y, a continuación, haga clic en *Agregar* o *Agregar y salir*.




== Cree un clúster de un solo nodo

Puede utilizar el complemento de VMware vCenter a través del cliente web de vSphere para implementar un clúster de ONTAP Select que consta de un único nodo.

.Antes de empezar
Debe revisar cómo preparar la puesta en marcha de un clúster de ONTAP Select y añadir un host de hipervisor. Puede añadir el host en el que se ejecutará el nodo de ONTAP Select antes de crear el clúster o como parte de la creación del clúster de un solo nodo.

.Pasos
. Inicie sesión en vCenter Server a través del HTML5 de vSphere mediante un explorador.
. Haga clic en *Menú* en la parte superior y, a continuación, haga clic en *Listas de inventario globales*.
. Haga clic en *clústeres ONTAP Select* en el panel de la izquierda y, a continuación, haga clic en *Nueva ONTAP Select*.
+
Si todavía no ha aceptado el certificado SSL, haga clic en el enlace IP del mensaje de advertencia y acepte el certificado. A continuación, vuelva a la página de vCenter y haga clic en el enlace del mensaje de advertencia para volver a cargar la página.

. En la página *Nueva ONTAP Select*, introduzca los detalles del clúster y haga clic en *hecho*.
. En la sección *Configuración de nodos*, proporcione la configuración y seleccione una licencia.
+
Puede cambiar el nombre predeterminado del nodo y cargar una nueva licencia si es necesario.

. En la sección *Hypervisor y Red*, seleccione el tipo de instancia, host y redes.
+
Puede añadir un host si es necesario. La licencia del nodo debe alcanzar o superar el tipo de instancia.

. En la sección *almacenamiento*, seleccione la capacidad de almacenamiento y una agrupación de almacenamiento.
+
Opcionalmente, se puede habilitar RAID de software cuando se utiliza una licencia premium.

. Haga clic en *hecho* y revise la configuración del clúster.
+
Puede cambiar la configuración haciendo clic en Editar en cada sección según sea necesario.

. Haga clic en *Siguiente*.
. Proporcione la contraseña del administrador de ONTAP y haga clic en *Crear clúster* para iniciar el proceso de creación del clúster y, a continuación, haga clic en *Aceptar* en la ventana emergente de confirmación.
+
Es posible que el clúster se cree demore hasta 30 minutos.

. Actualice la página y seleccione el nuevo clúster y, a continuación, haga clic en *Resumen* y *Detalles* para supervisar el proceso de creación de clúster de varios pasos.
+

TIP: Si la operación de creación del clúster se ha iniciado pero no puede completar, la contraseña administrativa de ONTAP que define no se ha registrado. En este caso, puede acceder a la interfaz de gestión para el clúster de ONTAP Select mediante la contraseña `changeme123` con la `admin` cuenta.



.Después de terminar
* Confirme que la función ONTAP Select AutoSupport está habilitada.
* Realice un backup de los datos de configuración de implementación de ONTAP Select.




== Cree un clúster de varios nodos

Puede utilizar el complemento de VMware vCenter a través del cliente web de vSphere para implementar un clúster de ONTAP Select que consta de varios nodos.

.Antes de empezar
Debe revisar cómo preparar la puesta en marcha de un clúster de ONTAP Select y añadir un host de hipervisor. Puede añadir los hosts en los que se ejecutarán los nodos de ONTAP Select antes de crear el clúster o como parte de la creación del clúster multinodo.

.Acerca de esta tarea
Un clúster de varios nodos de ONTAP Select consta de un número par de nodos. Los nodos siempre están Unidos como pares de alta disponibilidad.

.Pasos
. Inicie sesión en vCenter Server a través del HTML5 de vSphere mediante un explorador.
. Haga clic en *Menú* en la parte superior y, a continuación, haga clic en *Listas de inventario globales*.
. Haga clic en *clústeres ONTAP Select* en el panel de la izquierda y, a continuación, haga clic en *Nueva ONTAP Select*
+
Si todavía no ha aceptado el certificado SSL, haga clic en el enlace IP del mensaje de advertencia y acepte el certificado. A continuación, vuelva a la página de vCenter y haga clic en el enlace del mensaje de advertencia para volver a cargar la página.

. En la página *Nueva ONTAP Select*, introduzca los detalles del clúster y haga clic en *hecho*.
+
A menos que tenga un motivo para establecer el tamaño de MTU del clúster, debe aceptar el valor predeterminado y permitir que la implementación realice todos los ajustes necesarios.

. En la sección *Configuración de nodos*, proporcione la configuración y seleccione las licencias para los dos nodos del par ha.
+
Puede cambiar los nombres de los nodos predeterminados y cargar nuevas licencias si es necesario.

. En la sección *Hypervisor y Red*, seleccione el tipo de instancia, host y redes para cada nodo.
+
Puede añadir un host si es necesario. Debe seleccionar las tres redes. La red interna no puede ser la misma que la red de gestión o de datos. Las licencias de los nodos deben alcanzar o superar el tipo de instancia.

. En la sección *almacenamiento*, seleccione la capacidad de almacenamiento y una agrupación de almacenamiento.
+
Opcionalmente, se puede habilitar RAID de software cuando se utiliza una licencia premium.

. Si el clúster tiene cuatro o más nodos, debe configurar los nodos en las parejas de alta disponibilidad adicionales siguiendo los mismos pasos que se usaron para el primer par de alta disponibilidad.
. Haga clic en *hecho* y revise la configuración del clúster.
+
Puede cambiar la configuración haciendo clic en *Editar* en cada sección según sea necesario.

. De manera opcional, ejecute el comprobador de conectividad de red para probar la conectividad entre los nodos en la red de clúster interna.
. Haga clic en *Siguiente*.
. Proporcione la contraseña del administrador de ONTAP y haga clic en *Crear clúster* para iniciar el proceso de creación del clúster y, a continuación, haga clic en *Aceptar* en la ventana emergente de confirmación.
+
Es posible que el clúster se cree demore hasta 30 minutos.

. Actualice la página y seleccione el nuevo clúster y, a continuación, haga clic en *Resumen* y *Detalles* para supervisar el proceso de creación de clúster de varios pasos.
+

TIP: Si la operación de creación del clúster se ha iniciado pero no puede completar, la contraseña administrativa de ONTAP que define no se ha registrado. En este caso, puede acceder a la interfaz de gestión para el clúster de ONTAP Select mediante la contraseña `changeme123` con la `admin` cuenta.



.Después de terminar
* Confirme que la función ONTAP Select AutoSupport está habilitada.
* Realice un backup de los datos de configuración de implementación de ONTAP Select.

