---
sidebar: sidebar 
permalink: task_lic_acquire_cp.html 
keywords: license, licensing, acquire, Capacity Pools 
summary: Debe adquirir un archivo de licencia para cada pool de capacidad que utilizan los nodos de ONTAP Select. El archivo de licencia define la capacidad de almacenamiento y la caducidad del pool. Se bloquea en el Administrador de licencias mediante una combinación del número de serie de licencia único que asigna NetApp y el ID de bloqueo de licencia asociado con la instancia de implementación. 
---
= Adquirir una licencia de ONTAP Select Capacity Pool
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe adquirir un archivo de licencia para cada pool de capacidad que utilizan los nodos de ONTAP Select. El archivo de licencia define la capacidad de almacenamiento y la caducidad del pool. Se bloquea en el Administrador de licencias mediante una combinación del número de serie de licencia único que asigna NetApp y el ID de bloqueo de licencia asociado con la instancia de implementación.

.Antes de empezar
* Debes tener el número de serie de licencia de nueve dígitos asignado al Capacity Pool por NetApp.
* Deberías esperar al menos 24 horas después de la fecha de envío de tu orden de compra antes de adquirir un archivo de licencia.
* Has revisado la link:sizing-capacity-pool-license.html["consideraciones para dimensionar una licencia de Capacity Pools"].


.Acerca de esta tarea
Debe ejecutar esta tarea en cada pool de capacidad utilizado por los nodos ONTAP Select.

.Pasos
. Inicia sesión en link:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^].
. Selecciona *Systems* > *Software Licenses*.
. Escribe el número de serie de la licencia para el Capacity Pool y selecciona *¡Go!*.
. En la página de detalles de la licencia, vaya a la columna *Detalles del producto*.
. Selecciona *Get NetApp License File* en la fila correspondiente.
. Escribe el ID de bloqueo de licencia de tu instancia de ONTAP Select Deploy y selecciona *Submit*.
. Selecciona el método de entrega apropiado y haz clic en *Submit*.
. Selecciona *OK* en la ventana de confirmación de entrega.


.Después de terminar
Debes cargar el archivo de licencia en la utilidad de administración Deploy antes de que un nodo ONTAP Select pueda usar el Capacity Pool.
