---
sidebar: sidebar 
permalink: task_lic_acquire_ct.html 
keywords: license, licensing, acquire, Capacity Tiers 
summary: Cuando se usa la licencia Capacity Tiers, es necesario adquirir un archivo de licencia para cada nodo de ONTAP Select. El archivo de licencia define la capacidad de almacenamiento del nodo y se bloquea en el nodo a través del número de serie único de nueve dígitos que asigna NetApp. 
---
= Adquiera una licencia de nivel de capacidad de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando se usa la licencia Capacity Tiers, es necesario adquirir un archivo de licencia para cada nodo de ONTAP Select. El archivo de licencia define la capacidad de almacenamiento del nodo y se bloquea en el nodo a través del número de serie único de nueve dígitos que asigna NetApp.

.Antes de empezar
Debe tener el número de serie de licencia de nueve dígitos que asigna NetApp al nodo. Antes de intentar adquirir un archivo de licencia, debe esperar al menos veinte cuatro horas después de la fecha de envío de su orden de compra.

.Acerca de esta tarea
Debe realizar esta tarea en cada nodo ONTAP Select que requiera una licencia de nivel de capacidad.

.Pasos
. Acceda al sitio de licencias de ONTAP Select mediante un explorador web:
+
`https://register.netapp.com/register/getlicensefile`

. Inicie sesión con sus credenciales de cuenta de NetApp.
. En la página *Generador de licencias*, seleccione la oferta de licencia deseada en el cuadro desplegable.
. Rellene los campos restantes de la misma página, incluido el *número de serie del producto*, que es el número de serie del nodo ONTAP Select.
. Haga clic en *Enviar*.
. Después de validar la solicitud, seleccione el método de entrega de la licencia.
+
Puede hacer clic en *Licencia de descarga* o *Licencia de correo electrónico*.

. Confirme que ha recibido el archivo de licencia según el método de entrega seleccionado.


.Después de terminar
Debe cargar el archivo de licencia en la utilidad de administración de implementación para poder aplicarlo a un nodo ONTAP Select.
