---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: Si la utilidad ONTAP Select Deploy falla o no está disponible por algún motivo, se pierde la capacidad de administrar nodos y clústeres de ONTAP Select. Además, los clústeres de dos nodos pierden funcionalidad de alta disponibilidad porque el servicio mediador incluido en la puesta en marcha no está disponible. Si se produce un error irrecuperable, debe recuperar la instancia de la utilidad de instalación para restaurar la funcionalidad administrativa y de alta disponibilidad. 
---
= Recupere la utilidad ONTAP Select Deploy para un clúster de dos nodos
:allow-uri-read: 
:firstname: :hardbreaks:reints
:author: :hardbreaks:reints
:authorinitials: :
:authors: :hardbreaks:reints
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si la utilidad ONTAP Select Deploy falla o no está disponible por algún motivo, se pierde la capacidad de administrar nodos y clústeres de ONTAP Select. Además, los clústeres de dos nodos pierden funcionalidad de alta disponibilidad porque el servicio mediador incluido en la puesta en marcha no está disponible. Si se produce un error irrecuperable, debe recuperar la instancia de la utilidad de instalación para restaurar la funcionalidad administrativa y de alta disponibilidad.



== Prepárese para recuperar la utilidad Deploy

Para garantizar el éxito, debe prepararse antes de intentar recuperar una instancia de la utilidad Deploy.  Debes estar familiarizado con varios procedimientos administrativos y disponer de la información necesaria.

.Pasos
. Verifique que puede instalar una nueva instancia de la utilidad ONTAP Select Deploy en su entorno de hipervisor.
+
link:task_install_deploy.html["Aprenda cómo instalar la utilidad ONTAP Select Deploy"]

. Verifique que puede iniciar sesión en el clúster ONTAP Select y acceder al shell del clúster ONTAP (CLI).
. Determine si tiene una copia de seguridad de los datos de configuración de la instancia de la utilidad Deploy que falló y que contiene el clúster de dos nodos de ONTAP Select . Es posible que tenga una copia de seguridad que no contenga el clúster.
. Verifique que puede restaurar una copia de seguridad de los datos de configuración de Deploy, según el procedimiento de recuperación utilizado.
+
link:task_cli_migrate_deploy.html#step-3-restore-the-deploy-configuration-data-to-the-new-virtual-machine["Aprenda cómo restaurar los datos de configuración de Deploy en la nueva máquina virtual."]

. Dispones de la dirección IP de la máquina virtual de la utilidad Deploy original que falló.
. Determine si se utiliza el sistema de licencias de Grupos de Capacidad o de Niveles de Capacidad. Si utiliza licencias de grupos de capacidad, debe reinstalar cada licencia de grupo de capacidad después de recuperar o restaurar la instancia de implementación.
. Decida qué procedimiento utilizar al recuperar una instancia de la utilidad ONTAP Select Deploy. Su decisión se basa en si tiene una copia de seguridad de los datos de configuración de la utilidad de implementación original fallida que contiene el clúster de dos nodos de ONTAP Select .
+
[cols="35,65"]
|===
| ¿Tiene un backup de puesta en marcha que contenga el clúster de dos nodos? | Utilice el procedimiento de recuperación... 


| Sí | <<restore-deploy-backup,Restaure una instancia de utilidad de despliegue mediante una copia de seguridad de configuración>> 


| No | <<restore-and-recover-deploy,Vuelva a configurar y recuperar una instancia de utilidad de despliegue>> 
|===




== Restaure una instancia de utilidad de despliegue mediante una copia de seguridad de configuración

Si tiene una copia de seguridad de la instancia de la utilidad de implementación con errores que contiene el clúster de dos nodos, puede restaurar los datos de configuración en la nueva instancia de la máquina virtual de implementación. A continuación, debe completar la recuperación realizando una configuración adicional de los dos nodos del clúster ONTAP Select.

.Antes de empezar
Realice una copia de seguridad de los datos de configuración de la máquina virtual Deploy original que falló y que contiene el clúster de dos nodos. Debe poder iniciar sesión en la CLI de ONTAP del clúster de dos nodos y conocer los nombres de ONTAP de ambos nodos.

.Acerca de esta tarea
Debido a que el backup de configuración que restaura contiene el clúster de dos nodos, los destinos iSCSI y los buzones del mediador se vuelven a crear en la nueva máquina virtual de la utilidad de implementación.

.Pasos
. Prepare una nueva instancia de la utilidad ONTAP Select Deploy:
+
.. Instale una nueva máquina virtual de la utilidad de implementación.
.. Restaure la configuración de despliegue desde una copia de seguridad anterior a la nueva máquina virtual.
+
Consulte las tareas relacionadas para obtener información más detallada sobre los procedimientos de instalación y restauración.



. Inicie sesión en la interfaz de línea de comandos de ONTAP del clúster de dos nodos ONTAP Select.
. Entre en el modo de privilegio avanzado:
+
[source, cli]
----
set adv
----
. Si la dirección IP de la nueva máquina virtual de implementación es diferente a la de la máquina virtual de implementación original, elimine los destinos iSCSI del mediador antiguo y agregue nuevos destinos:
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
La `<ip_address>` Parameter es la dirección IP de la nueva máquina virtual de implementación.

+
Estos comandos permiten que los nodos de ONTAP Select descubran los discos de buzón en la nueva máquina virtual de la utilidad de implementación.

. Determine los nombres de los discos del mediador:
+
[source, cli]
----
disk show -container-type mediator
----
. Asigne los discos del buzón a los dos nodos:
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. Compruebe que la recuperación tras fallos del almacenamiento está activada:
+
[source, cli]
----
storage failover show
----


.Después de terminar
Si utiliza licencias de Capacity Pools, reinstale cada licencia de Capacity Pool.  Verlink:task_adm_licenses.html#reinstall-a-capacity-pool-license["Vuelva a instalar una licencia de Capacity Pool"] Para obtener más detalles.



== Vuelva a configurar y recuperar una instancia de utilidad de despliegue

Si no dispone de una copia de seguridad de la instancia de la utilidad Deploy que ha fallado y que contiene el clúster de dos nodos, configure el destino iSCSI del mediador y el buzón de correo en la nueva máquina virtual Deploy.  A continuación, se completa la recuperación realizando una configuración adicional de los dos nodos en el clúster ONTAP Select .

.Antes de empezar
Verifique que dispone del nombre del destino del mediador para la nueva instancia de la utilidad Deploy. Debe poder iniciar sesión en la CLI de ONTAP del clúster de dos nodos y conocer los nombres de ONTAP de ambos nodos.

.Acerca de esta tarea
Opcionalmente, se puede restaurar un backup de configuración en la nueva máquina virtual de implementación aunque no contenga el clúster de dos nodos. Debido a que el clúster de dos nodos no se vuelve a crear con la restauración, se debe añadir manualmente el destino iSCSI y el buzón mediador a la nueva instancia de la utilidad de implementación a través de la página web de documentación en línea de ONTAP Select en la implementación. Debe poder iniciar sesión en el clúster de dos nodos y conocer los nombres de ONTAP de los dos nodos.


NOTE: El objetivo del procedimiento de recuperación es restaurar el clúster de dos nodos a un estado en buen estado, donde se pueden realizar operaciones normales de toma de control de ha y devolución.

.Pasos
. Prepare una nueva instancia de la utilidad ONTAP Select Deploy:
+
.. Instale una nueva máquina virtual de la utilidad de implementación.
.. Si lo desea, puede restaurar la configuración de implementación desde un backup anterior a la nueva máquina virtual.
+
Si restaura una copia de seguridad anterior, la nueva instancia de implementación no contendrá el clúster de dos nodos. Consulte la sección de información relacionada para obtener información más detallada sobre los procedimientos de instalación y restauración.



. Inicie sesión en la interfaz de línea de comandos de ONTAP del clúster de dos nodos ONTAP Select.
. Entrar en el modo privilegiado avanzado:
+
[source, cli]
----
set adv
----
. Obtenga el nombre del destino iSCSI del mediador:
+
[source, cli]
----
storage iscsi-initiator show -target-type mailbox
----
. Acceda a la página web de documentación en línea de la nueva máquina virtual de la utilidad de implementación e inicie sesión mediante la cuenta de administrador:
+
`\http://<ip_address>/api/ui`

+
Se debe usar la dirección IP de la máquina virtual de implementación.

. Seleccione *Mediador* y luego *GET /mediators*.
. Seleccione *¡Pruébelo!* para mostrar una lista de mediadores mantenidos por Deploy.
+
Anote el ID de la instancia de mediador deseada.

. Seleccione *Mediador* y luego *POST*.
. Proporcione el valor para mediador_id
. Seleccione el *Modelo* que aparece junto a `iscsi_target` y complete el valor del nombre.
+
Use el nombre de destino del parámetro IQN_name.

. Seleccione *¡Pruébelo!* para crear el destino iSCSI del mediador.
+
Si la solicitud es correcta, recibirá el código de estado HTTP 200.

. Si la dirección IP de la nueva máquina virtual de implementación es diferente de la máquina virtual de implementación original, debe utilizar la interfaz de línea de comandos de ONTAP para eliminar los antiguos destinos iSCSI del mediador y agregar nuevos destinos:
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
La `<ip_address>` Parameter es la dirección IP de la nueva máquina virtual de implementación.

+
Estos comandos permiten que los nodos de ONTAP Select descubran los discos de buzón en la nueva máquina virtual de la utilidad de implementación.

. Determine los nombres de los discos del mediador:
+
[source, cli]
----
disk show -container-type mediator`
----
. Asigne los discos del buzón a los dos nodos:
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. Compruebe que la recuperación tras fallos del almacenamiento está activada:
+
[source, cli]
----
storage failover show
----


.Después de terminar
Si utiliza licencias de Capacity Pools, reinstale cada licencia de Capacity Pool.  Verlink:task_adm_licenses.html#reinstall-a-capacity-pool-license["Vuelva a instalar una licencia de Capacity Pool"] Para obtener más detalles.
